zenoss/zenoss-prodbin

Products/ZenModel/browser/DeviceList.py
Products/Zuul/catalog/indexable.py

Includes changes needed for [ZEN-27538](https://jira.zenoss.com/browse/ZEN-27538)

Add indexed property deviceClassPath

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceDetailBar.js
Products/Zuul/infos/device.py

add visual indicator when device collection is paused for renaming

---

Products/ZenUtils/tests/testMemcacheClientWrapper.py

Fix RelStorage test failure in testMemcacheClientWrapper.py

Fix RelStorage test failures

---

Products/Zuul/infos/device.py

[Jira](https://jira.zenoss.com/browse/ZEN-27768)

ZEN-27768 Group total incorrect

---

Products/ZenModel/IpInterface.py

http://platform-jenkins.zenoss.eng/job/product-assembly/job/develop/job/resmgr-pipeline/241/consoleFull
The cache wasn't being invalidated when a local ip was added or removed via setIpAddresses().  Also only invalidate the cache in removeIpAddress() if the call actually removes an ip.
```
Failure in test test_cmode (ZenPacks.zenoss.NetAppMonitor.tests.testCMode.TestCMode)
Traceback (most recent call last):
File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
testMethod()
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.NetAppMonitor-3.5.0-py2.7.egg/ZenPacks/zenoss/NetAppMonitor/tests/testCMode.py", line 252, in test_cmode
self.assertEquals(iface_ipAddresses, "169.254.30.2/16,169.254.34.158/16")
File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual …
```

Invalidate cache when a local ip is added

---

Products/ZenModel/DeviceClass.py
Products/ZenUI3/browser/resources/js/zenoss/DeviceDetailBar.js
Products/ZenUI3/browser/resources/js/zenoss/devdetail.js
Products/Zuul/routers/device.py

* added context-sensitive visual indicator on device details page for paused collection status during rename
* added context-sensitive manual resetting of rename-in-progress flag on device details page

ZEN-27660 UI indicator for rename-in-progress

---

Products/ZenModel/skins/zenmodel/zenoss_error_message.pt
Products/ZenModel/skins/zenmodel/zenoss_feedback_error_message.pt

changed url to current valid url

community forum link fix / update

---

Products/ZenUI3/browser/eventconsole/export.py

Fixes ZEN-26387
some how lost this line in the backport.

Add details assignment back

---

Products/ZenModel/migrate/addDebugZopesSvcDef.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.1.5-addDebugZopesSvcDef.json

fix/ZEN-27857: the zendebug Vhost on Zproxy should be disabled by default

fix/ZEN-27868: Merge pull request #2462 from zenoss/feature/ZEN-27854_ZEN-27857

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js
Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js
Products/Zuul/facades/__init__.py

Remove Device Status column for 5.2.6

Remove Device Status column

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml
Products/ZenModel/migrate/improveModeledDevices.py

port from https://github.com/zenoss/zenoss-prodbin/pull/2482
[Jira](https://jira.zenoss.com/browse/ZEN-27853)

ZEN-27853 Negative Values on 'Modeled Devices' graph

---

Products/ZenModel/migrate/createNetworksCache.py

This method does all the initialization:
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenModel/IpNetwork.py#L271

ZEN-27824: initialize networks cache

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js
Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js
Products/Zuul/facades/__init__.py

https://jira.zenoss.com/browse/ZEN-27879

ZEN-27879 Improving loading time of Infrastructure page

---

Products/ZenModel/BatchDeviceDumper.py

https://jira.zenoss.com/browse/ZEN-27937
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCSCentral/pull/87

ZEN-27937 Proper loading of  Cisco UCS devices with zenbatchload

---

Products/ZenModel/BatchDeviceDumper.py

https://jira.zenoss.com/browse/ZEN-27605
backport of https://github.com/zenoss/zenoss-prodbin/pull/2509

ZEN-27605 Proper loading of  Cisco UCS devices with zenbatchload

---

Products/Zuul/catalog/legacy.py

Part of ZEN-27671 because zennetworkclean uses it.

Add __len__ to legacy adapters

---

Products/ZenModel/ZDeviceLoader.py

this is port from https://github.com/zenoss/zenoss-prodbin/pull/2506
[JIRA](https://jira.zenoss.com/browse/ZEN-23132)

ZEN-23132: change debug to error log and raise an exception

---

Products/Jobber/manager.py

ZEN-28123 don't log all job args anymore

---

bin/metrics/zenossStatsView.py

Add whitelisted prefix to metric tag for zope data. Handle exceptions in the instance loop so if we fail to connect to a zope, we'll still try the others.

Add whitelisted prefix to metric tag for zope data.

---

Products/DataCollector/zenmodeler.py

modeledDevices and the number of failures are kept track of.

ZEN-28165: Instrument zenmodeler for self-monitoring

---

Products/ZenEvents/events2/processing.py

https://jira.zenoss.com/browse/ZEN-27514

ZEN-27514 Processing transforms for non-Zenoss devices

---

Products/ZenModel/ZVersion.py

This is the string used for the about box in the RM UI.
Matches the value of `VERSION` in makefile.

Bump ZVersion.py for Thebe

---

Products/ZenWidgets/messaging.py

Since, its coming as a json response for a request.

ZEN-26742: Removed escaping html characters for body of message

---

Products/Zuul/facades/devicefacade.py

[Jira](https://jira.zenoss.com/browse/ZEN-28274)

ZEN-28274 Datastore sort by allocation is random

---

Products/Zuul/routers/application.py

https://jira.zenoss.com/browse/ZEN-28190

ZEN-28190 Fixing  audit message about changing application state

---

Products/Zuul/routers/application.py

https://jira.zenoss.com/browse/ZEN-28303
port https://github.com/zenoss/zenoss-prodbin/pull/2612

ZEN-28303 Fixing  audit message about changing application state

---

Products/ZenModel/migrate/addThebeLogFilters.py
Products/ZenModel/migrate/data/pythondaemon-6.0.0.conf
Products/ZenModel/migrate/data/supervisord-6.0.0.conf
Products/ZenModel/migrate/data/z2_access_logs-6.0.0.conf
Products/ZenModel/migrate/data/zappdaemon-6.0.0.conf
Products/ZenModel/migrate/data/zeneventserver-6.0.0.conf
Products/ZenModel/migrate/data/zope-6.0.0.conf
Products/ZenModel/migrate/tests/test_addThebeLogFilters.py

Wraps up the fixes for ZEN-27982

ZEN-27982: migrate the standard set of log filters

---

Products/ZenUI3/browser/resources/js/zenoss/Reports.js

https://jira.zenoss.com/browse/ZEN-28269

ZEN-28269 Delete subNodes together with a parentNode

---

Products/Zuul/facades/devicefacade.py

port from https://github.com/zenoss/zenoss-prodbin/pull/2604
[Jira](https://jira.zenoss.com/browse/ZEN-22906)

ZEN-22906 Datastore sort by allocation is random

---

Products/ZenUI3/browser/resources/js/zenoss/Reports.js

https://jira.zenoss.com/browse/ZEN-28316
port https://github.com/zenoss/zenoss-prodbin/pull/2617/commits

ZEN-28316 Delete subNodes together with a parentNode

---

Products/ZenEvents/events2/processing.py

https://jira.zenoss.com/browse/ZEN-28181
port https://github.com/zenoss/zenoss-prodbin/pull/2582

ZEN-28181 Processing transforms for non-Zenoss devices

---

Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js

https://jira.zenoss.com/browse/ZEN-28184
port https://github.com/zenoss/zenoss-prodbin/pull/2611

ZEN-28184 Removing paging toolbar for NonPaginated store

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

https://jira.zenoss.com/browse/ZEN-26937

ZEN-26937 Display full class path in device banner

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

https://jira.zenoss.com/browse/ZEN-28354
port https://github.com/zenoss/zenoss-prodbin/pull/2638

ZEN-28354 Display full class path in device banner

---

Products/ZenUtils/CmdBase.py
Products/ZenUtils/ZenScriptBase.py
Products/Zuul/catalog/model_catalog_init.py

Added should_log parameter to avoid oversubscribing of loggers in CmdBase

Fix for SOLR log duplicates

---

Products/ZenModel/WinService.py
Products/Zuul/infos/component/winservice.py

https://jira.zenoss.com/browse/ZEN-28278
port https://github.com/zenoss/zenoss-prodbin/pull/2602

ZEN-28278 Allow Disabled WinService to be monitored via gui

---

Products/ZenModel/MibModule.py
Products/ZenRelations/ImportRM.py
Products/Zuul/routers/mibs.py
makefile

Includes fixes for https://jira.zenoss.com/browse/ZEN-28477

Fixes for531

---

Products/ZenEvents/EventClass.py
Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js
Products/ZenUI3/browser/resources/js/zenoss/Renderers.js
Products/ZenUI3/browser/resources/js/zenoss/form/EventAction.js
Products/ZenUI3/browser/resources/js/zenoss/form/configPropertyPanel.js
Products/ZenUI3/browser/resources/js/zenoss/form/modelerPluginPanel.js
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js
Products/ZenUI3/browser/zenoss.jsb2

https://jira.zenoss.com/browse/ZEN-28364
port https://github.com/zenoss/zenoss-prodbin/pull/2657

ZEN-28364 UI improvements to Event Class Mapping Form

---

Products/ZenModel/PerformanceConf.py
Products/Zuul/facades/devicefacade.py
Products/Zuul/routers/device.py

backport from https://github.com/zenoss/zenoss-prodbin/pull/2667

ZEN-28357: new arguments to extend remodel API functionality

---

bin/metrics/mysqlmetrics.sh
bin/metrics/storagestats.py

Created mysqlmetrics.sh and storagestats.py to collect storage info from mariadb

ZEN-27336 Collect storage metrics from Maria and HBase

---

Products/ZenModel/migrate/removeEmptyProductClassRelationships.py

Part of the fix for ZEN-28515 and ZEN-28514
See Also https://github.com/zenoss/product-assembly/pull/529

Allow RemoveEmptyProductClassRelationship migration to be run twice

---

Products/ZenModel/BatchDeviceLoader.py
Products/ZenModel/ZDeviceLoader.py

https://jira.zenoss.com/browse/ZEN-28391

ZEN-28391 use setManageIP only during device creation

---

Products/ZenModel/migrate/data/zeneventserver-6.0.0.conf

This applies the new zeneventserver log filter for the migrations scheduled for thebe release. https://jira.zenoss.com/browse/ZEN-28566

Updated the zeneventserver.conf for the migrations.

---

Products/Zuul/search/routers.py
Products/Zuul/tests/test_searchrouter.py

port from: https://github.com/zenoss/zenoss-prodbin/pull/2701

ZEN-28476: Inefficient wildcard search causes Zope to hang

---

Products/ZenCollector/scheduler.py

https://jira.zenoss.com/browse/ZEN-28563
port https://github.com/zenoss/zenoss-prodbin/pull/2352

ZEN-28563 Fix data collection intervals

---

README.md
tests/README.md
tests/extjs_jasmine_test_guide.md
tests/locust.io/README.md

* add README for tests
* add guide for testing ExtJS using Jasmine

Add a README file for the project

---

Products/ZenModel/migrate/addToolboxLogsToKibana.py

[Jira](https://jira.zenoss.com/browse/ZEN-28564)

ZEN-28564 addToolboxLogsToKibana.py throwing exception

---

Products/Zuul/catalog/model_catalog_init.py

Our timeout was too short to wait for processes to finish their current batch.

Increase process join wait time

---

Products/Zuul/catalog/model_catalog.py

https://jira.zenoss.com/browse/ZEN-27920

Drop model catalog warning to debug level logging

---

Products/ZenModel/skins/zenmodel/editSettings.pt
Products/ZenModel/skins/zenmodel/editUserSettings.pt
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

port from https://github.com/zenoss/zenoss-prodbin/pull/2693

ZEN-27697 several fields incorrectly accept autofill

---

Products/ZenRRD/utils.py
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/threshold.js
Products/Zuul/facades/templatefacade.py
Products/Zuul/routers/template.py

This is a port from https://github.com/zenoss/zenoss-prodbin/pull/2706
[JIRA](https://jira.zenoss.com/browse/ZEN-27051)

ZEN-27051: add new button to show threshold with rpn

---

Products/ZenModel/UserSettings.py

[Jira](https://jira.zenoss.com/browse/ZEN-28630)

manager users can easily reset the RM admin password

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Fixed problem with click-to-zoom on area charts

ZEN-28639 Click to Zoom Area Charts

---

Products/ZenUtils/zenpack.py

https://jira.zenoss.com/browse/ZEN-28647

ZEN-28647 Make version of RM compatible with zphistory

---

Products/ZenModel/BatchDeviceLoader.py
Products/ZenModel/ZDeviceLoader.py

https://jira.zenoss.com/browse/ZEN-28391
port https://github.com/zenoss/zenoss-prodbin/pull/2700

ZEN-28521 use setManageIP only during device creation

---

Products/ZenHub/zenhub.py

port https://github.com/zenoss/zenoss-prodbin/pull/2747

ZEN-28624: ZenHUB logging messages with passwords

---

Products/ZenUtils/zenpack.py

https://jira.zenoss.com/browse/ZEN-28647

ZEN-28647 Get version of RM/Core/UCSPM from before upgrade

---

Products/ZenUI3/browser/resources/js/zenoss/Renderers.js
Products/ZenUI3/browser/resources/js/zenoss/date.js
Products/ZenUI3/browser/resources/js/zenoss/tests/date_fixture.js
Products/ZenUI3/browser/resources/js/zenoss/tests/date_spec.js
tests/jasmine/SpecRunner.html

Additional aids for handling timezones correctly.

---

Products/ZenModel/GraphPoint.py
Products/ZenUI3/browser/resources/css/zenoss.css

Improved padding for footers. Flare when trying to create a stacked line chart.

ZEN-28780 Graph Improvements

---

Products/ZenEvents/EventClass.py
Products/ZenReports/reports/Event_Reports/Disabled_Transforms.rpt

https://jira.zenoss.com/browse/ZEN-28588

ZEN-28588 Report for EventClasses with disabled transform

---

Products/ZenModel/MaintenanceWindow.py

ZEN-26444 Maintenance windows don't recover from a production state

---

Products/ZenModel/ZVersion.py
makefile

Updates ZVersion to 6.1.0 and ZMigrateVersion to 200.1.0.

Update versions for 6.1.0 (Ganymede).

---

Products/ZenUtils/patches/zodbpackmonkey.py
bin/zenossdbpack

ZEN-28370 zenossdbpack Workerized Build Tables Doesn't Re-establish

---

Products/ZenUI3/browser/resources/js/zenoss/form/ComponentGraphPanel.js

[Jira](https://jira.zenoss.com/browse/ZEN-23689)

ZEN-23689 Component Graphs need auto-refresh capability

---

Products/ZenModel/migrate/updateRateOptionsForSvcdefs.py
makefile

Sets the stage for a future 5.3.4 release

bump versions

---

Products/ZenModel/migrate/limitRabbitMQInstances.py
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances.py
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances_in.json
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances_out.json

https://jira.zenoss.com/browse/ZEN-27995
ref to https://github.com/zenoss/zenoss-service/pull/474

ZEN-27995 Migration script: Limit RabbitMQ's instances to 1

---

Products/ZenModel/migrate/limitRabbitMQInstances.py
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances.py
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances_in.json
Products/ZenModel/migrate/tests/test_limitRabbitMQInstances_out.json

https://jira.zenoss.com/browse/ZEN-29049
port https://github.com/zenoss/zenoss-prodbin/pull/2836

ZEN-29049 Migration script: Limit RabbitMQ's instances to 1

---

Products/Zuul/infos/component/__init__.py

[JIRA](https://jira.zenoss.com/browse/ZEN-28116)
Related PR https://github.com/zenoss/ZenPacks.zenoss.ComponentGroups/pull/24

ZEN-28116: add Production state on the CG page

---

Products/ZenUI3/browser/resources/js/zenoss/form/CustomPropertyPanel.js

Allow blank values for custom properties.

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js
Products/ZenUI3/browser/resources/js/zenoss/form/ComponentGraphPanel.js

Standardize the Auto-column behavior between Graphs and Component Graphs.

ZEN-29171 Graph Column Behavior

---

makefile

also bumping the schema version variables in makefile based on the "Schema Versions" tab in this sheet: https://docs.google.com/spreadsheets/d/1KdRVEvhtkFro6MeLtU14LWZJrS84HYvSbKFORY9hlSQ/edit#gid=45408309

bumping develop to 6.2.0

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt

Catch user-input of 100 chart height and adjust width to prevent backwards-compat code from adjusting height to 500.  Hide width row because width values are ignored.

ZEN-28772 Graph height 100

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt

Remove unused/unsupported Logarithmic scale option from graph report options.

ZEN-29241 Remove Log Scale Option

---

Products/ZenModel/BasicDataSource.py

this is port from https://github.com/zenoss/zenoss-prodbin/pull/2890
[JIRA](https://jira.zenoss.com/browse/ZEN-29284)

ZEN-29284: set zminionCommand in SNMP setup

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt
Products/ZenModel/skins/zenmodel/editGraphPoint.pt

Removes 'Display Full Value in Footer' option that is no longer supported.

ZEN-29239 Full Value Option

---

Products/ZenEvents/zentrap.py

https://jira.zenoss.com/browse/ZEN-28946

ZEN-28946 Revert OID's interfaces parsing

---

Products/ZenModel/skins/zenmodel/editGraphPoint.pt

Removes unused line width option from Multigraph Graph Point definition panel.

ZEN-29238 Multigraph Line Width

---

Products/ZenModel/skins/zenmodel/editGraphPoint.pt

Remove unused line color option from datapoint definition.

ZEN-29289 Multigraph Line Color

---

Products/ZenModel/skins/zenmodel/editGraphPoint.pt

Removes unused limit input field from datapoint customization panel.

ZEN-29237 Multigraph Datapoint Limit

---

Products/ZenCallHome/CallHomeStatus.py

https://jira.zenoss.com/browse/ZEN-28615

Fixed issue when pickle tried loads None value

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

Maintains visual state of device tree in side panel across refreshes.

ZEN-18523 Device tree collapses on refresh

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

CSS changes in support of narrow graph UI changes in central query

ZEN-29235 Poor narrow browser UI for graphs

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

Adjust logic to save and restore the tree layout from the right-click "Refresh Tree" context menu of a node.

ZEN-29385 Refresh Tree from context menu

---

Products/ZenUI3/browser/resources/js/zenoss/SubselectionPanel.js
Products/ZenUI3/browser/resources/js/zenoss/devdetail.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

[Jira](https://jira.zenoss.com/browse/ZEN-29341)

ZEN-29341 Device Tree refresh moves focus away from device class panel

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Adjusted logic to limit height of footer to 150px

ZEN-29436 Tall footer squishes chart

---

Products/ZenModel/migrate/addMemcachedForSessions.py

ZEN-29001 Move Zope session data to its own memcached instance.

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

CSS changes in support of narrow graph UI changes in central query
port from https://github.com/zenoss/zenoss-prodbin/pull/2927

ZEN-29235 Poor narrow browser graphs UI

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt

[Jira](https://jira.zenoss.com/browse/ZEN-28772)

set min value to graph height

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt

port https://github.com/zenoss/zenoss-prodbin/pull/2960

ZEN-29473-1 set min value to graph height

---

bin/remove_CatalogServiceZenPack.sh

[JIRA](https://jira.zenoss.com/browse/ZEN-29451)

ZEN-29451: add an instruction for manual removal of CatalogService

---

bin/remove_CatalogServiceZenPack.sh

[JIRA](https://jira.zenoss.com/browse/ZEN-29497)
port from
https://github.com/zenoss/zenoss-prodbin/pull/2955
https://github.com/zenoss/zenoss-prodbin/pull/2964

ZEN-29497: add an instruction for manual removal of CatalogService

---

Products/ZenModel/migrate/replicateCollectorRedis.py

port https://github.com/zenoss/zenoss-prodbin/pull/2967

ZEN-29517: Error: redis endpoint does not exist in RabbitMQ-Ceilometer

---

Products/Zuul/infos/metricserver.py

[Jira](https://jira.zenoss.com/browse/ZEN-29234)

Cannot add percent sign to multigraph summary legend numbers

---

Products/ZenModel/ZVersion.py

https://jira.zenoss.com/browse/ZEN-29325

ZEN-29325 bump version to 6.2.0

---

Products/ZenUtils/Auth0/Auth0.py

Store the roles in session and read them from the session when roles are requested for the principal

Read Roles from Auth0 Token

---

bin/fix_MultiRealmIPZenPack.sh

ZEN-29563: Cannot upgrade MultiRealmIP Zenpack from 2.2.2 to 2.2.3

---

Products/Zuul/catalog/model_catalog.py

https://jira.zenoss.com/browse/ZEN-29642
port https://github.com/zenoss/zenoss-prodbin/pull/2958

ZEN-29642 Method to return indexes for a specific object

---

Products/ZenUI3/browser/resources/css/zen-cse.css

CSE skin for quickstart wizard panels.

Update quickstart wizard with new CSE themes - light and dark.

---

Products/ZenUI3/browser/resources/js/zenoss/Tracker.js
Products/ZenUI3/browser/templates/base-new.pt

ZEN-29537 Google Analytics

---

jenkins_build.sh

The bin directory may also have changes that participate in PR testing.

Copy prodbin/bin/ contents to zenhome/bin.

---

Products/ZenUI3/browser/resources/css/zen-cse.css

css code cleanup plus adjustments for Azure & vSphere ZP dialogs.

Enterprise ZP css adjustments and code cleanup

---

Products/ZenUtils/MultiPathIndex.py

Allows graphs to load successfully.

Account for new cse virtual root when building graph query.

---

Products/DataCollector/zing/DatamapHandler.py
Products/DataCollector/zing/fact.py

- Add a connection timeout for connections to zing-connector
- If the fact data contains lists of something other than scalar, convert the non scalar values to string
- If zing-connector fails to process a batch of Facts returning a 500, re-try sending facts one by one

Datamap to Facts improvements

---

Products/ZenUI3/browser/resources/css/zen-cse.css

a bit too many filter icons across the grids.  returning those to blanks.

too many filter icons

---

Products/Zing/zing_connector.py

Build the URL for zing-connector admin endpoint using the hostname of the API endpoint + port 9000 + `/ping`

Update zing-connector admin endpoint with the right port nbr

---

Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenModel/IpAddress.py
Products/ZenModel/migrate/addDeviceIpAddrRelation.py
Products/ZenModel/tests/testDevice.py
Products/ZenUI3/browser/resources/css/zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/network.js
Products/ZenUtils/IpUtil.py
Products/Zuul/facades/devicefacade.py
Products/Zuul/infos/network.py
Products/Zuul/routers/network.py

This is port from https://github.com/zenoss/zenoss-prodbin/pull/2994

ZEN-29580: create IpAddress on device creation

---

Products/ZenCallHome/ZenossAppData.py

this is cherry-pick from 
https://github.com/zenoss/zenoss-prodbin/pull/3082
[JIRA](https://jira.zenoss.com/browse/ZEN-29841)

ZEN-29841: remove linked guests who's vSphere have been set to decomm

---

Products/ZenReports/reports/Event_Reports/All_EventMappings.rpt

Add friendly column labels for exported report

Fixes ZEN-23102

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Demo: https://jira.zenoss.com/secure/attachment/50237/ZEN-29855-fixed.mp4

 ZEN-29855 Device Chart > RMMonitor: Uncaught TypeError

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Demo: https://jira.zenoss.com/secure/attachment/50265/ZEN-29883-fixed.mp4

 ZEN-29883 Device Chart > RMMonitor: Uncaught TypeError (#3093)

---

Products/ZenMessaging/ChangeEvents/events.py
Products/ZenMessaging/ChangeEvents/interfaces.py
Products/ZenMessaging/queuemessaging/publisher.py
Products/ZenModel/RRDDataPointAlias.py
Products/ZenUtils/CSEUtils.py

This will be hooked by impact to forward relationships to zing-connector
See also https://github.com/zenoss/ZenPacks.zenoss.Impact/pull/506

Add post-publishing event

---

Products/ZenModel/migrate/tests/common.py

BLD-203: remove zen.migrate logs from unittest output

---

Products/ZenUI3/browser/resources/css/zen-cse.css
Products/ZenUI3/browser/resources/js/zenoss/form/RuleBuilder.js

Demo: https://jira.zenoss.com/secure/attachment/50661/ZEN-29949-demo.mp4

ZEN-29949 Match the Service Impact UI styling with the ZING UI styling

---

Products/Zuul/facades/triggersfacade.py

Masked password that haven't changed keeps current password.
Handle password fields that have been masked that are not named password.

ZEN-29814: Fix the way Notification settings was handling passwords

---

Products/ZenUI3/browser/resources/css/zen-cse.css

Demo: https://jira.zenoss.com/secure/attachment/50687/ZEN-29972-fixed.mp4

ZEN-29972 Hover color for device class link in Device details page makes it invisible

---

Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

Demo: https://jira.zenoss.com/secure/attachment/50995/zenapi.ip-10-111-23-31_cse_zport_dmd_itinfrastructure%20%284%29.png

ZEN-30013 Move "Cannot to connect to server" popup to a flare message in CZ

---

Products/ZenUI3/browser/resources/js/zenoss/network.js

[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30127?focusedCommentId=129369&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-129369)

ZEN-30127: add a tooltip to the delete button

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Remove resizer from combo list.

ZEN-30124 - Attempting to scroll down the device class list

---

Products/Zuul/catalog/global_catalog.py
Products/Zuul/infos/component/__init__.py
Products/Zuul/infos/device.py

Demo https://jira.zenoss.com/secure/attachment/51321/ZEN-30089-demo.png

ZEN-30089 The add to component group dialog is badly colored

---

Products/Zuul/infos/network.py

https://docs.python.org/3/library/string.html#format-specification-mini-language
[Jira](https://jira.zenoss.com/browse/ZEN-30128)

ZEN-30128 format free addresses  for IP addresses

---

Products/ZenUtils/Auth0/Auth0.py

Fix logout url

---

Products/Zuul/infos/organizer.py

[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30193?focusedCommentId=130091&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-130091)

ZEN-30193: add a cz# prefix to uid

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Add Zenoss.env.CSE_VIRTUAL_ROOT to "uid".

ZEN-30271 - Add Location issue on Infrastructure screen

---

Products/Zuul/routers/report.py

[Jira](https://jira.zenoss.com/browse/ZEN-30224)

ZEN-30224 fix TypeError when deleting a report

---

Products/ZenModel/MultiGraphReport.py

[Jira](https://jira.zenoss.com/browse/ZEN-30223)

ZEN-30223 fix for collections, graph definitions, graph groups

---

Products/ZenUI3/browser/resources/css/zen-cse.css

[Demo](https://jira.zenoss.com/secure/attachment/52349/ZEN-30299-fixed.PNG)

ZEN-30299: Fix hover color for tree in Events -> Triggers

---

Products/ZenUI3/browser/resources/css/zen-cse.css
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddDeviceView.js
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AutoDiscoveryView.js

[Demo](https://jira.zenoss.com/secure/attachment/52351/ZEN-30300-fixed.png)

ZEN-30300: Fix icon on dark theme

---

Products/ZenUI3/browser/resources/js/zenoss/form/LinkField.js

one by one check value type and display it.

ZING-594 - linkfield - handle object in setValue fn

---

Products/ZenModel/Commandable.py
Products/ZenModel/skins/zenmodel/userCommandDetailNew.pt

[Jira&Demo](https://jira.zenoss.com/browse/ZEN-30225)

ZEN-30225 fix edit command functionality

---

Products/Zuul/routers/report.py

[Jira](https://jira.zenoss.com/browse/ZEN-30323)

ZEN-30323 User cannot delete organizer reports

---

Products/ZenUtils/mib/smidump.py
Products/ZenUtils/mib/tests/test_smidump.py

Handle subprocess output correctly.

---

Products/ZenUI3/browser/resources/js/zenoss/triggers.js

Cherry-pick from commit: https://github.com/zenoss/zenoss-prodbin/commit/9e7979a241b190ddf4de7fc4c5ee43bb3f48d364

ZEN-29796: Trigger window contents ignore trigger window size

---

Products/ZenUtils/mib/smidump.py
Products/ZenUtils/mib/tests/test_smidump.py

ZEN-30361 Handle subprocess output correctly.

---

Products/ZenModel/skins/zenmodel/editUserSettings.pt

* Removed empty `<tr></tr>`
* Wrapped form in `tr>td[colspan="4"]`
* `tr`s inside `form` wrapped into a table
Backported from zenoss/zenoss-prodbin#3080

ZEN-29846: Fix mark-up validity

---

Products/ZenUI3/browser/resources/js/zenoss/form/IDField.js

We have to add cz prefix to request URL since otherwise, we will get 404 error.

ZEN-30379: Fix request url for IP Services

---

Products/ZenUI3/browser/resources/css/zen-cse.css

Enlarge only header font size, no need to add other styles.

ZEN-30390 - style changes for header text in panels

---

bin/metrics/zenossStatsView.py

[Jira](https://jira.zenoss.com/browse/ZEN-29775)

ZEN-29775 Zope Self-Monitoring Collection Needs a Timeout

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/dialog_addUserToAGroup.pt
Products/ZenModel/skins/zenmodel/dialog_addUserToGroup.pt

nonexistant users can now be added to groups, automatically created

---

Products/ZenUI3/browser/resources/js/zenoss/form/ComponentGraphPanel.js

Increased the width of comboboxes and drop-down lists to the size of the text in them.

ZEN-30395 - style changes for toolbar items

---

Products/ZenReports/reports/Performance_Reports/CPU_Utilization.rpt

[JIRA](https://jira.zenoss.com/browse/ZEN-30416)

ZEN-30416: fix link from CPU Utilization report to device

---

Products/ZenUI3/browser/resources/js/zenoss/form/DataSourceEditDialog.js

[Jira & Demo](https://jira.zenoss.com/browse/ZEN-30573?focusedCommentId=133901&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-133901)

ZEN-30573: Improve flexibility of layout

---

Products/ZenUtils/Auth0/Auth0.py

https://jira.zenoss.com/browse/ZEN-30611
RBAC role mappings come in the form "CZ0:CZAdmin", "CZ1:ZenOperator". If an Auth0 user logs in with any RBAC mapping, RM will only use the groups assigned to it's own CZ instance.  In other words, the above user when logging into cz0 will only have the CZAdmin role.  The same user logging
into cz1 will have the ZenOperator role.  If this user logs into cz2 he/she will have no roles.
In the absence of any RBAC style mappings, the list of roles from Auth0 will be returned as-is.  This means if you're using the zenoss-com connection and logging into a dev instance, you'll still have CZAdmin, even though you don't have any RBAC-assigned roles.
At some point in the future, group-role mappings in the Auth0 authorization extension will be removed, and the …

Add support for RBAC style role mappings

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

[Jira](https://jira.zenoss.com/browse/ZEN-29264)

Large multi-graph reports can't open in new tab due to long URLs

---

Products/ZenUI3/browser/resources/css/zen-cse.css

transparent background for UCS reports

ZPS-4225 - UCS Capacity Reports are broken on CZ

---

Products/ZenUtils/Auth0/Auth0.py

https://jira.zenoss.com/browse/ZING-805
https://jira.zenoss.com/browse/ZING-821 (minor fix)
ZING is storing the expiration in a cookie.  When we get sent to challenge(), we redirect them to ZING.  If they login, the expiration changes.  If the expiration stays the same then ZING has sent them back (they're already logged into Auth0) and we know they're trying to access an unauthorized page.  When we detect this (the cause of this infinite loop), we just redirect them to the ZING root.
There's something strange about the way the SessionInfo() object is persisted from memcached-session, and saving the token expiration in the session object from challenge() does **not** persist it between checks.  A local dictionary doesn't work across multiple zope instances, so I'm using memcached to store …

Detect unauthorized infinite redirect loops

---

Products/ZenModel/ZenModelBase.py
Products/ZenUI3/browser/eventconsole/export.py
Products/ZenUtils/Time.py

[Jira&Demo](https://jira.zenoss.com/browse/ZEN-28212)

ZEN-28212 Wrong time format on State at time

---

Products/DataCollector/zendisc.py

zendisc now discovers devices concurrently.

---

Products/ZenUtils/patches/mysqladaptermonkey.py

this is cherry-picking from https://github.com/zenoss/zenoss-prodbin/pull/3419
[JIRA](https://jira.zenoss.com/browse/ZEN-30866)

ZEN-30866: fix the path for objects that need to be patched

---

Products/ZenHub/zenhubworker.py
Products/ZenModel/migrate/data/zenhubworker.json
Products/ZenModel/migrate/tests/zenoss-resmgr-6.1.0-addZenHubWorkerService.json

Enable zenhub_answering healthcheck.

---

Products/ZenHub/interceptors.py
Products/ZenHub/tests/test_interceptors.py

Also fix serialization problem when sending data to sendEvent/sendEvents.
Fixes ZEN-30920.

Fix typo in WorkerInterceptor.

---

Products/ZenModel/skins/zenmodel/viewGraphReport.pt
Products/ZenModel/skins/zenmodel/viewMultiGraphReport.pt
Products/ZenReports/rasterize.js
Products/ZenUI3/browser/backcompat.zcml

This is a port from 
https://github.com/zenoss/zenoss-prodbin/pull/3422
https://github.com/zenoss/zenoss-prodbin/pull/3383
[JIRA](https://jira.zenoss.com/browse/ZEN-28763)

ZEN-28763: add graph support for reportmail functionality

---

Products/ZenUI3/browser/resources/css/zen-cse.css
Products/ZenWidgets/skins/zenui/dialogmacros.pt

[Jira & Demo](https://jira.zenoss.com/browse/ZEN-30904?focusedCommentId=138562&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-138562)

ZEN-30904: Fix reports popups on light theme

---

Products/ZenHub/tests/test_worklist.py
Products/ZenHub/tests/test_zenhub.py
Products/ZenHub/worklist.py
Products/ZenHub/zenhub.py

* The worker stats logging includes better information for the new higher priority jobs from user requested device modeling.
* Model pause checking has been abstracted into its own class
* Job prioritization is now handled by its own class.
Fixes ZEN-30892.

Updated logging for applyDataMaps user priority.

---

Products/Zuul/facades/devicefacade.py

This is cherry-picking from https://github.com/zenoss/zenoss-prodbin/pull/3179
[JIRA](https://jira.zenoss.com/browse/ZEN-30945)

ZEN-30945: show only local monitoring template

---

Products/ZenModel/skins/zenmodel/dialog_addCustomGraphPoint.pt
Products/ZenModel/skins/zenmodel/dialog_addDataPointGraphPoint.pt
Products/ZenModel/skins/zenmodel/dialog_addThresholdGraphPoint.pt
Products/ZenModel/skins/zenmodel/zenoss.css
Products/ZenUI3/browser/resources/css/backcompat.css
Products/ZenUI3/browser/resources/css/zenoss.css

[Jira & Demo](https://jira.zenoss.com/browse/ZEN-30931?focusedCommentId=138836&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-138836)

ZEN-30931: Fix pop-ups windows on the Edit a Report page

---

Products/ZenHub/invalidationmanager.py
Products/ZenHub/tests/testZenHub.py
Products/ZenHub/tests/test_PBDaemon.py
Products/ZenHub/tests/test_invalidationmanager.py
Products/ZenHub/tests/test_zenhub.py
Products/ZenHub/zenhub.py

* move zenhub invalidation functionality into InvalidationManager
* Fix failing legacy integration tests

ZEN-30840: Add InvalidationManager class

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30429?focusedCommentId=139272&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-139272)

ZEN-30429: do not select the text i search input on focus

---

Products/ZenHub/invalidationmanager.py
Products/ZenHub/tests/test_invalidationmanager.py

Fixes: ZEN-30983
* add yield for processor.processQueue to prevent blocking

ZEN-30983: Deduplicate oids before publishing for workers

---

Products/ZenHub/invalidationmanager.py
Products/ZenHub/tests/test_invalidationmanager.py

* Fixes StopItteration exceptions after an exception is raised from a pipeline segment

Add exception handling to Invalidation Pipeline

---

Products/ZenModel/DataRoot.py
Products/ZenModel/configure.zcml
Products/ZenModel/migrate/clearPageCommand.py
Products/ZenModel/skins/zenmodel/editSettings.pt
Products/ZenModel/zenbuild.py
Products/ZenTestCase/BaseTestCase.py

port https://github.com/zenoss/zenoss-prodbin/pull/3372/files

ZEN-30792: Make paging integration work better

---

Products/ZenModel/skins/zenmodel/datePicker.js
Products/ZenModel/skins/zenmodel/zenoss.css

backport https://github.com/zenoss/zenoss-prodbin/pull/3363 to CZ

ZEN-30771 CSE - Wrong time format on Reports page

---

Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js
Products/ZenUI3/browser/resources/js/zenoss/date.js

backport from 6.x https://github.com/zenoss/zenoss-prodbin/pull/3367

ZEN-31065 CSE - Make date range pickers drop-down a range selector

---

Products/ZenUI3/browser/templates/base-new.pt

Works with zproxy config changes in this [PR](https://github.com/zenoss/zenoss-service/pull/588)
See notes in ZEN-31143 for details

ZEN-31143 - Fix for URL rewrite bug

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js

Backport from zenoss/zenoss-prodbin#3380

ZEN-31030: Prevent hanging of events console

---

Products/ZenModel/ZVersion.py
etc/sudoers.d/zenoss_nmap
makefile

This release includes only the fix for ZEN-31184.

Release hotfix 7.0.8

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/ZenUI3/browser/resources/js/zenoss/viewGraph.js

ZEN-31299: Make "Link to this graph" graph option working

---

Products/ZenModel/ZVersion.py
makefile

ZEN-31343 (part of 7.0.9 release).

Bump version to 7.0.10

---

Products/ZenCollector/daemon.py
Products/ZenCollector/tests/test_daemon.py

ZEN-31219: fix error handling in maintenence cycle

---

Products/ZenCollector/daemon.py
Products/ZenCollector/tests/test_daemon.py

Fixes: ZEN-31424
Backport from ZEN-31219

ZEN-31424: fix error handling in maintenence cycle

---

Products/ZenUI3/browser/templates/base-new.pt

Should match the URL in https://github.com/zenoss/zing-deploy/blob/master/ui/pendoLoad.js

Fix URL for pendo content

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/tests/test_PBDaemon.py

ZEN-31388: build parent class options before own options

---

Products/ZenUI3/browser/modelapi/modelapi.py

Change name to conform with relationship name in RMMon. ZEN-31617

Change name to conform with relationship name in RMMon. ZEN-31617

---

Products/DataCollector/ApplyDataMap/__init__.py
Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/events.py
Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/reporter.py
Products/DataCollector/ApplyDataMap/tests/__init__.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_events.py
Products/DataCollector/ApplyDataMap/tests/test_incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_reporter.py
Products/DataCollector/tests/test_incrementalupdate_integration.py

ZEN-31735: add copyright headers

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-31751: Add handling for duplicate IDs in RelationshipMaps

---

Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py

fix potential TypeError in applyDataMap

---

Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py

ZEN-31761: fix potential TypeError in applyDataMap

---

Products/DataCollector/ApplyDataMap/configure.zcml
Products/DataCollector/ApplyDataMap/events.py
Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/metrics.py
Products/DataCollector/ApplyDataMap/tests/test_events.py
Products/DataCollector/ApplyDataMap/tests/test_metrics.py
Products/DataCollector/configure.zcml
Products/ZenHub/metricmanager.py
Products/ZenHub/zenhubworker.py

ZEN-26857: Push ADM processing time to TSDB

---

Products/DataCollector/ApplyDataMap/configure.zcml
Products/DataCollector/ApplyDataMap/events.py
Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/metrics.py
Products/DataCollector/ApplyDataMap/tests/test_events.py
Products/DataCollector/ApplyDataMap/tests/test_metrics.py
Products/DataCollector/configure.zcml
Products/ZenHub/metricmanager.py
Products/ZenHub/zenhubworker.py

ZEN-31700: Push ADM processing time to TSDB

---

Products/ZenUI3/browser/resources/js/zenoss/viewGraph.js

demo: https://youtu.be/agAjHBIpBWo

ZEN-31757: Unable to render a graph after editing Site Window Portlet.

---

Products/ZenModel/BasicDataSource.py
Products/ZenModel/Device.py
Products/ZenModel/PerformanceConf.py
Products/ZenRRD/zencommand.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenUI3/browser/command.py
Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js

* "Spelling change"
- 3addbc5295e53557ba7c704eb7ce976e6441afb4
* "Add backward compatibility"
- e3da3ab7c04adc53d4ffbd16eaa530adcee90447
* "ZEN-31038 Users need to be able to do connection debugging from the UI"
- 79ba021abb516076912d57735dfe7579fd3ac4ee.
Fixes ZEN-31841.

Revert these commits:

---

Products/ZenModel/BasicDataSource.py
Products/ZenModel/Device.py
Products/ZenModel/PerformanceConf.py
Products/ZenModel/RRDDataSource.py
Products/ZenRRD/zencommand.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenUI3/browser/command.py
Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js

The same that this https://github.com/zenoss/zenoss-prodbin/pull/3581, was reverted for 7.0.12 here: https://github.com/zenoss/zenoss-prodbin/pull/3629

Test button functionality for datasources with readable output

---

Products/ZenUI3/browser/stats/stats.py
bin/metrics/zenossStatsView.py

backport: https://github.com/zenoss/zenoss-prodbin/pull/3557

ZEN-31467: Add total requests taking over pre-specified number of seconds

---

Products/ZenHub/tests/test_PBDaemon.py

Fix testPBDaemon's buildOptions test.

---

Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_incrementalupdate.py

ZEN-31901: Add locked device handling to incremental data map

---

Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_incrementalupdate.py

ZEN-31902: Add locked device handling to incremental data map

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-31904: Validate objectMaps in RelationshipMaps

---

Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenModel/MonitorClass.py
Products/ZenModel/ZDeviceLoader.py
Products/ZenModel/tests/testDevice.py
Products/Zuul/facades/devicefacade.py

backport from https://github.com/zenoss/zenoss-prodbin/pull/3542

ZEN-31056: API allows devices to be added to non-existent collectors

---

Products/Zing/configure.zcml

ZEN-31911: register zing_add_datamap handler

---

Products/ZenHub/server/metrics.py

Metrology Counter has a 'count' attribute.

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/events.py
Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_events.py
Products/DataCollector/plugins/DataMaps.py
Products/DataCollector/plugins/tests/__init__.py
Products/DataCollector/plugins/tests/test_DataMaps.py
Products/Zing/configure.zcml
Products/Zing/datamaps.py
Products/Zing/tests/test_datamaps.py

ZEN-31948: fix datamap publishing for zing

---

Products/ZenEvents/zentrap.py

Backport for https://github.com/zenoss/zenoss-prodbin/pull/3643

zentrap createUser collectorCalls blocking

---

Products/ZenModel/migrate/addOOMParams.py

Remove unnecessary changes

---

Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_incrementalupdate.py

ZEN-31933: do not remove target without relname

---

Products/DataCollector/plugins/tests/__init__.py
Products/DataCollector/tests/plugins/test_DataMaps.py

ZEN-32034: move plugin unittests out of plugin folder

---

Products/ZenHub/server/metrics.py

Counters are bare integers.

---

Products/ZenStatus/PingCollectionPreferences.py
Products/ZenStatus/nmap/NmapPingTask.py

Allow ping down events without correlation.

---

Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py

Fix zenhubworker status report error.

---

Products/ZenModel/migrate/updateDisableCorrelatorDefaultText.py

Commit changes for zenping.conf update.

---

Products/ZenModel/migrate/tests/test_VerifyMigrateVersion.py

A new unit test to analyze all the migration scripts to verify that their migrate version does not exceed the version specified in Products.ZenModel.ZMigrateVersion.

Unit test to verify migrate versions

---

Products/ZenModel/migrate/tests/test_VerifyMigrateVersion.py

The test_VerifyMigrateVersion unit test analyzes all the migration scripts to verify that their migrate version does not exceed the version specified in Products.ZenModel.ZMigrateVersion.
Fixes ZEN-32173.

Unit test to verify migrate versions.

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-32180: handle NotFound exceptions in _get_relmap_target

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-32181: handle NotFound exceptions in _get_relmap_target

---

Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js

(cherry picked from commit b20c1ec) ZEN-30800

ZEN-32012: Unable to Sort when Editing Event Class Mappings under Sequence Tab

---

Products/ZenModel/skins/zenmodel/editCollection.pt
Products/ZenModel/skins/zenmodel/editCollectionItem.pt
Products/ZenModel/skins/zenmodel/editCustGraphDefinition.pt
Products/ZenModel/skins/zenmodel/editDeviceReport.pt
Products/ZenModel/skins/zenmodel/editGraphDefinition.pt
Products/ZenModel/skins/zenmodel/editGraphPoint.pt
Products/ZenModel/skins/zenmodel/editGraphReport.pt
Products/ZenModel/skins/zenmodel/editGraphReportElement.pt
Products/ZenModel/skins/zenmodel/editMultiGraphReport.pt
Products/ZenModel/skins/zenmodel/manageCollections.pt

ZEN-31353: change reports permissions from manager to czadmin

---

Products/ZenCollector/tests/test_daemon.py
Products/ZenUtils/metricwriter.py

ZEN-32484: Add anomaly logging to DerivativeTracker

---

Products/ZenHub/configure.zcml
Products/ZenHub/server/__init__.py
Products/ZenHub/server/executors/event.py
Products/ZenHub/server/executors/tests/test_event.py
Products/ZenHub/server/executors/tests/test_workers.py
Products/ZenHub/server/executors/workers.py
Products/ZenHub/server/main.py
Products/ZenHub/server/tests/test_main.py
Products/ZenHub/server/tests/test_workerpool.py
Products/ZenHub/server/tests/test_worklist.py
Products/ZenHub/server/workerpool.py
Products/ZenHub/server/worklist.py
Products/ZenHub/tests/testMetricPublisher.py
Products/ZenHub/tests/test_PBDaemon.py
Products/ZenHub/tests/test_zenhub.py
Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhub.py

ZEN-32526: Rewrite task/worker dispatch using queue semantics.

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js

(cherry picked from commit f8a2637e6df2fe8aef265ae52a1d370d92ff566f)
Signed-off-by: Roman Bakaleyko <roman.bakaleyko@gmail.com>

ZEN-32561: Event Archive Export to CSV fails

---

Products/ZenHub/configure.zcml
Products/ZenHub/tests/test_zenhub.py
Products/ZenHub/zenhub.py

ZEN-32588: simplify reactor metrics code

---

Products/ZenModel/ZenossInfo.py

Fixed getting of twisted version

---

Products/ZenModel/skins/zenmodel/editGraphGroup.pt

Update the old 'Manager' user permissions to czadmin

Fixes ZEN-32644

---

Products/ZenModel/ZenModelBase.py
Products/ZenUtils/relstorage/mysql/003.sql
Products/ZenUtils/tests/testMemcacheClientWrapper.py

Add support for RelStorage 3.0.

---

Products/ZenReports/ReportMail.py

- Fixed query parsing in ReportMail.py
- Added --debug and --ignore-ssl-errors into ReportMail.py

ZEN-32718 Fixes and enhancements for ReportMail.py

---

Products/ZenUI3/browser/resources/js/zenoss/Tooltips.js
Products/ZenUI3/browser/resources/js/zenoss/componentTemplate.js
Products/ZenUI3/browser/resources/js/zenoss/devdetail.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/threshold.js
Products/ZenUI3/browser/resources/js/zenoss/template.js
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

ZEN-32784 (backport for ZEN-30758)

---

Products/ZenReports/ReportMail.py

We need to have the possibility to save file into a specific directory. This commit removes the deleting of the saved file

ZEN-32812: We shouldn't delete generated report

---

Products/ZenRRD/runner.py
Products/ZenRRD/zencommand.py
Products/ZenUtils/Executor.py
Products/ZenUtils/tests/test_executor.py

When a command's execution time exceeds the timeout value, the connection to the device will be closed.  The connection is closed when the collection cycle has completed.
Fixes ZEN-32385.

zencommand handles command timeouts.

---

Products/ZenRRD/zencommand.py

Pass the right number of arguments.

---

Products/ZenRRD/zencommand.py

Don't assume eventKey field exists.

---

Products/ZenRRD/zencommand.py

Add Clear events, when necessary, for a datasource during result processing, not during result storage.  Also, datasource timeout events have the component field set to the name of the datasource.
Fixes ZEN-32925.

Refactor zencommand's event management.

---

Products/Jobber/task/dmd.py

Ensure ZenRelations/ZenProperty code is installed.

---

Products/Jobber/config.py
Products/Jobber/manager.py
Products/Jobber/model.py
Products/Jobber/tests/test_manager.py
Products/Jobber/tests/test_model.py

Support legacy query fields by JobManager.

---

Products/Jobber/jobs/misc.py
Products/Jobber/task/dmd.py

Use default user if given user fails.

---

Products/Jobber/jobs/misc.py
Products/Jobber/jobs/subprocess.py
Products/Jobber/log.py
Products/Jobber/tests/test_algorithms.py
Products/Jobber/tests/test_log.py
Products/Jobber/utils/algorithms.py
Products/Jobber/utils/log.py
Products/ZenUI3/browser/resources/js/zenoss/joblist.js

Whitespace is also now preserved.
Fixes ZEN-33060.

Send job log messages to correct log files.

---

Products/Jobber/manager.py
Products/Jobber/model.py
Products/Jobber/storage.py
Products/Jobber/task/event.py
Products/Jobber/tests/test_model.py
Products/Jobber/tests/test_redisrecord.py
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddDeviceView.js
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AutoDiscoveryView.js
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/JobLog.js
Products/Zuul/routers/jobs.py

Add support for chained jobs.

---

Products/Jobber/task/dmd.py

Specify the number generator func to backoff.

---

Products/Jobber/jobs/facade.py

Detect joblog parameter correctly.

---

Products/Zuul/facades/metricfacade.py

Fix "Unknown log msg type received from central query" error

---

Products/Jobber/storage.py
Products/Jobber/tests/test_storage.py

Expire jobs based on status.

---

Products/Jobber/config.py
Products/Jobber/log.py
Products/Jobber/scheduler.py
Products/Jobber/signals.zcml

Make zenjobs scheduler logging better.

---

Products/Jobber/config.py
Products/Jobber/log.py

Handle zenjobs-job-expires as a global config.

---

Products/Jobber/log.py
Products/Jobber/model.py
Products/Jobber/task/abortable.py

Handle deleted jobs.

---

Products/Zing/datamaps.py
Products/Zing/model_updates.py

Add logging around delete facts.

---

Products/Zing/datamaps.py
Products/Zing/model_updates.py

Remove unnecessary Zing fact delete logging.

---

Products/Zing/datamaps.py

Manually migrated from this commit 
https://github.com/zenoss/zenoss-prodbin/commit/ebe90aef9d61f99f9b163fdf943629bf227604a5

ZEN-33112: zing fact generation inefficient and component groups broken - patch

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

(cherry picked from commit 6c1964ae10aab499ae78c058cf57d9371bde30dc)

ZEN-33009: fix object comparison in ADM

---

Products/Jobber/model.py
Products/Jobber/tests/test_model.py
Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddDeviceController.js

Fix flare message while adding multiple vSphere devices

---

Products/Jobber/manager.py

Fix error when we add multiply vSphere devices

---

Products/ZenHub/server/config.py
Products/ZenHub/server/main.py

Add sanity checks for zenhub-server.yaml file.

---

Products/ZenModel/RRDDataSource.py

Add 'context' key for TALES evaluation.

---

Products/ZenModel/tests/testIpNetwork.py

add unit test for the fix https://github.com/zenoss/zenoss-prodbin/pull/3985/files

ZEN-33165 add unit test

---

Products/Jobber/tests/test_model.py
Products/ZenRelations/tests/testEvents.py

Fix unit test failures in Products.ZenRelations

---

Products/ZenHub/services/ModelerService.py

Give ApplyDataMap a copy to work on.

---

Products/ZenModel/actions.py
Products/ZenModel/configure.zcml
Products/Zuul/infos/actions.py
Products/Zuul/infos/configure.zcml
Products/Zuul/interfaces/actions.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3963

ZEN-33277 Add support of sending SNMP v3 traps via notification

---

Products/DataCollector/plugins/zenoss/snmp/SnmpV3EngineIdMap.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3953/files

ZEN-32940 SnmpV3EngineID Modeler Plugin Can't Handle No ID Returned

---

Products/ZenModel/OSProcess.py
Products/ZenUI3/browser/resources/js/zenoss/process.js
Products/Zuul/infos/component/osprocess.py
Products/Zuul/infos/process.py
Products/Zuul/interfaces/component.py
Products/Zuul/interfaces/process.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3945

ZEN-33268 Process memory-threshold patch should be applied to prodbin

---

Products/ZenModel/RRDDataSource.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3997

ZEN-33275 Add 'context' key for TALES evaluation.

---

Products/Jobber/config.py
Products/Jobber/jobs/__init__.py
Products/Jobber/jobs/purge_logs.py
Products/Jobber/log.py
Products/Jobber/scheduler.py
Products/Jobber/signals.zcml
Products/Jobber/tests/test_model.py
Products/ZenRelations/tests/testEvents.py

Adds a task that deletes job logs which is executed periodically by the 'beat' command.
Fixes ZEN-33325.

Adds a custom scheduler for the Celery's 'beat' command.

---

bin/metrics/solrstats.py

Extract Solr data correctly.

---

Products/Zing/fact.py

Exclude password properties from Zing.

---

Products/ZenModel/Device.py

define variable before its use.

---

Products/ZenUtils/Executor.py

Two changes that address tracebacks observed in zencommand's log file.

Fix zencommand tracebacks

---

Products/ZenRRD/zencommand.py

Datasource commmands finishing with non-zero exit code is not an error.
Fixes ZEN-33464.

Restore zencommand error code handling.

---

Products/DataCollector/ApplyDataMap/__init__.py
Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py

ApplyDataMaps.applyDataMaps no longer modifies its arguments.

---

Products/ZenModel/Device.py
Products/ZenModel/RRDDataSource.py
Products/ZenModel/tests/testDevice.py
Products/ZenModel/tests/testRRDDataSource.py

Added unit tests.
Fixes ZEN-33467.

Refactor datasource testing to use similar code.

---

Products/ZenRelations/ImportRM.py
Products/ZenRelations/RelationshipManager.py
Products/ZenRelations/tests/test_ImportRM.py
Products/ZenRelations/tests/test_RelationshipManager.py

Preserve prodstate in xml imports and device class moves.

---

Products/ZenUtils/snmp.py

Copy the list so it's not modified.

---

Products/ZenModel/DataRoot.py

fix for zen-32234
removing traceback from console error report

Rremoving traceback from console error report

---

Products/Jobber/meta.zcml
Products/Jobber/metaconfigure.py
Products/Jobber/task/dmd.py
Products/Zing/configure.zcml
Products/Zing/send_organizers.py

Add job to send organizer facts to zing.

---

Products/Zing/configure.zcml
Products/Zing/send_component_groups.py

Add job to send component group facts to Zing.

---

Products/ZenPackAdapter/cloudpublisher.py
Products/ZenPackAdapter/db.py
Products/ZenPackAdapter/monkey.py
Products/ZenPackAdapter/services.py
Products/ZenPackAdapter/update_zenpacks.py
Products/ZenPackAdapter/zenwrapt.py
Products/ZenPackAdapter/zminihub.py
Products/ZenPackAdapter/zobject.py

Fix for Zing-13679
https://jira.zenoss.com/browse/ZING-13679

Updating ZPA to use zobject

---

Products/ZenModel/DataRoot.py

Call format_exception_only to ignore traceback.

---

Products/Zing/zing_connector.py

Remove reference to non-existent attribute

---

Products/ZenUI3/browser/resources/js/zenoss/manufacturers/ManufacturersConsole.js
Products/Zuul/routers/manufacturers.py
Products/Zuul/utils.py

- Sanitize URL field
- Allow only HTTP schemes
- Add validation to the frontend

ZEN-33656 Fix XSS vulnerability in Edit Manufacturer dialog

---

Products/ZenUI3/browser/resources/js/zenoss/manufacturers/ManufacturersConsole.js
Products/Zuul/routers/manufacturers.py
Products/Zuul/utils.py

- Sanitize URL field
- Allow only HTTP schemes
- Add validation to the frontend

ZEN-33758 (Forward port) Fix XSS vulnerability in Edit Manufacturer dialog

---

Products/ZenModel/UserSettings.py
Products/Zuul/facades/userfacade.py
Products/Zuul/infos/user.py
Products/Zuul/routers/users.py

Updating usersync to include adding/removing ZenUser role and listing Member's groups as well as Group's members
updates needed for: ZING 17150, 17359, 17360
https://jira.zenoss.com/browse/ZING-15272

Updating Zuul Router Users

---

Products/ZenModel/UserSettings.py
Products/Zuul/facades/userfacade.py
Products/Zuul/infos/user.py
Products/Zuul/routers/users.py

fix for zen-33810
zuul user router IInfo object now correctly returns the data
Also adds a check that groups != None, before a for-loop

corrects the Zuul userrouter output

---

Products/ZenCollector/cyberark.py
Products/ZenCollector/tests/test_cyberark.py
Products/ZenCollector/zencyberark.py

Log CyberArk tracebacks only when DEBUG is enabled.

---

Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js

Updated regex mask for [ZEN-28389](https://jira.zenoss.com/browse/ZEN-28389)

Updated js regex mask.

---

Products/DataCollector/SshClient.py

Fixes ZEN-33995.
To fix the issue for the sendEvent of SshClient, the sending of events
was implemented using IEeventService.

Fix sendEvent function for SshClient

---

bin/healthchecks/redis_answering

Restore redis_answering healthcheck script.

---

Products/ZenUtils/Auth0/Auth0.py

Check Auth0 session before using it.

---

Products/Jobber/config.py
Products/Jobber/storage.py
Products/Jobber/tests/utils.py
Products/ZenCallHome/CallHomeStatus.py
Products/ZenUtils/RedisUtils.py
Products/ZenUtils/requestlogging/ZenCheckZopesAssignments.py
Products/ZenUtils/requestlogging/ZopeRequestLogger.py
Products/Zuul/utils.py

Unify synchronous use of redis client.

---

Products/Zuul/routers/triggers.py

E-mail Notifications Displays Plain Text Password

---

Products/ZenModel/migrate/addSnmpLastCollectionIndex.py
Products/Zuul/catalog/indexable.py

Fixes ZEN-34085.
To resolve the issue, the last modeled time was added for indexing into
Solr.

Add indexing of last modeled time to Solr

---

Products/ZenUI3/browser/resources/js/zenoss/ContextCardButtonPanel.js
Products/ZenUI3/browser/resources/js/zenoss/SubselectionPanel.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Fix for component tree. 
Ticket [ZEN-34079](https://jira.zenoss.com/browse/ZEN-34079)
Moved changes from this PR: https://github.com/zenoss/zenoss-prodbin/pull/3195
Tested manually.

ZEN-34079:Hidden component tree(backport)

---

Products/ZenUI3/browser/eventconsole/columns.py
Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js

Fixed Date/Time filtering on the State Change column
Defect: [ZEN:34076](https://jira.zenoss.com/browse/ZEN-34076)
Moved changes from PR https://github.com/zenoss/zenoss-prodbin/pull/3317
Tested manually

ZEN:34067 Date/Time filtering is broken on the State Change column

---

bin/healthchecks/redis_answering

ZEN-34006: Return redis_answering 

---

Products/ZenModel/ZenPackLoader.py
Products/ZenReports/ReportLoader.py
Products/ZenReports/tests/test_report_loader.py

Fixed missing element in CPU utilization report
Defect: [ZEN-34072](https://jira.zenoss.com/browse/ZEN-34072)
Moved changes from PR https://github.com/zenoss/zenoss-prodbin/pull/3545

ZEN:34072 Missing element in CPU utilization report

---

bin/quiesce-rabbitmq.sh

Restore the quiesce-rabbitmq.sh script.

---

Products/Zuul/routers/triggers.py

Added warning message if notification is not updated
[Defect: ZEN-34203](https://jira.zenoss.com/browse/ZEN-34203) 
Tested manually.

Added message if notification is not updated

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Fix infrastructure page commands fail

---

Products/ZenModel/Device.py

Fixes ZEN-32938.
Back-port for ZEN-32926 from support/6.x branch

Exhaustively find a suitable sourcetype

---

Products/ZenModel/Device.py
Products/ZenModel/RRDDataSource.py
Products/ZenModel/tests/testDevice.py
Products/ZenModel/tests/testRRDDataSource.py

Fixes ZEN-34070.
Back-port for ZEN-33467 from support/6.x branch

Fix 'UnboundLocalError' error for Meraki dsplugins

---

Products/DataCollector/zendisc.py

Fixes ZEN-30834.
Back-port for ZEN-30835 from support/6.x.

zendisc SNMP Discovery is not parallelized

---

Products/ZenCollector/cyberark.py

Handle chained certificate authorities for cyberark.

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Fix the confirmation dialog for device deletion

---

Products/Jobber/log.py
Products/Jobber/tests/test_log.py

Ensure builder service loads the correct logging configuration.

---

Products/ZenCollector/config/task.py
Products/ZenCollector/daemon.py
Products/ZenCollector/services/config.py
Products/ZenCollector/services/push.py
Products/ZenHub/PBDaemon.py
Products/ZenHub/services/ConfigCache.py
Products/ZenHub/services/DiscoverService.py
Products/ZenHub/services/EventService.py
Products/ZenHub/services/ModelerService.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenHub/services/ThresholdMixin.py

Restored some CollectorDaemon APIs that ZenPacks depended on.

---

Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/utils/pollers.py
Products/ZenCollector/configcache/utils/services.py
Products/ZenHub/hub.zcml
Products/ZenHub/invalidationoid.py

Restored DeviceOidTransform class to support vSphere ZenPack.
ZEN-34658

Correctly locates configuration services in ZenPack egg installs.

---

Products/ZenCollector/configcache/cli.py

Implemented configcache's 'show' and 'expire' commands.

---

Products/ZenCollector/configcache/cli.py

Handle showing a config that doesn't exist.

---

Products/ZenCollector/daemon.py
Products/ZenCollector/services/ConfigCache.py

Moved ConfigCache service to ZenCollector.services package.  Removed redundant getOptionsFilter implementation.
ZEN-34652

Fix call to dispatching strategy class.

---

Products/ZenCollector/configcache/app/base.py
Products/ZenCollector/configcache/app/init.py
Products/ZenCollector/configcache/cli.py
Products/ZenCollector/configcache/expire.zcml
Products/ZenCollector/configcache/list.zcml
Products/ZenCollector/configcache/show.zcml
Products/ZenCollector/configcache/store.zcml

Allow runtime initialization without Zope.

---

Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/utils/__init__.py
Products/ZenCollector/configcache/utils/propertymap.py

Use defaults for missing config cache z-properties.

---

Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/utils/__init__.py
Products/ZenCollector/configcache/utils/propertymap.py

Use defaults for missing ConfigCache z-properties.

---

bin/healthchecks/MetricShipper/store_answering
bin/healthchecks/metrics_answering
bin/healthchecks/query_answering

Pass correct options to curl for HEAD requests.

---

bin/nmap
etc/sudoers.d/zenoss_nmap
etc/sudoers.d/zenoss_ping

Add nmap wrapper script and update zenoss nmap sudoers config.

---

Products/ZenStatus/nmap/util.py

Actually use /opt/zenoss/bin/nmap

---

Products/ZenCollector/configcache/manager.py

fix: fix timestamp format in manager.py

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/localserver/__init__.py
Products/ZenHub/localserver/errors.py
Products/ZenHub/localserver/options.py
Products/ZenHub/localserver/resource.py
Products/ZenHub/localserver/server.py
Products/ZenHub/localserver/zhstatus.py
Products/ZenHub/tests/test_PBDaemon.py
Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py
bin/dumpstats
bin/healthchecks/zenhub_answering

Replace zenhub answering file with HTTP endpoint.

---

Products/ZenCollector/config/task.py
Products/ZenCollector/daemon.py
Products/ZenCollector/frameworkfactory.py
Products/ZenCollector/scheduler/__init__.py
Products/ZenCollector/scheduler/scheduler.py
Products/ZenCollector/scheduler/statistics.py
Products/ZenCollector/scheduler/task.py
Products/ZenCollector/tests/testFactory.py
Products/ZenHub/PBDaemon.py

fix: remove collection tasks for removed device

---

Products/ZenCollector/configcache/modelchange/oids.py

Sometimes a (ZenRelations) relationship is empty so check whether it exists before trying to use it.
ZEN-34714

fix: check relationships before using them.

---

Products/ZenCollector/configcache/modelchange.zcml
Products/ZenCollector/configcache/modelchange/oids.py

Added an IInvalidationOid implementation to configcache to handle threshold changes.
ZEN-34715

fix: add invalidation transform to handle threshold changes

---

Products/ZenCollector/configcache/cli.py

The show command now displays nearly all data in a device configuration and its output adjusts to the width of the terminal.
Also, wildcard matching is now used so the commands can be abbreviated to reduce the amount of required typing.  The wildcard feature has been extended to list and expire commands.
ZEN-34721

The show command displays more device config content.

---

Products/ZenCollector/configcache/cache/model.py
Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/cache/table/__init__.py
Products/ZenCollector/configcache/cache/table/config.py
Products/ZenCollector/configcache/cache/table/metadata.py
Products/ZenCollector/configcache/cache/table/uid.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/tests/test_storage.py

fix: retry config builds that have expired

---

Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/utils/pollers.py

fix: force garbage collection

---

Products/ZenCollector/configcache/manager.py

When looking for old device configs to rebuild, make sure the minimum TTL setting is applied.
ZEN-34731

fix: ensure minimumTTL has precedence over TTL.

---

Products/ZenCollector/configcache/propertymap.py
Products/ZenCollector/configcache/tests/test_propertymap.py

fix: DevicePropertyMap now returns default when given None.

---

Products/ZenCollector/zencyberark.py

Also renamed the '--debug' option to '--verbose'.
ZEN-34750

fix: configure logging for stdout in zencyberark

---

Products/ZenUtils/configlog.py

fix: addLogsFromConfigFile no longer clears out loggers

---

Products/ZenRelations/checkrel.py
Products/ZenUtils/CheckRelations.py

Also added argument checking to checkrel.py
ZEN-34580

fix: add absolute import support to CheckRelations.py

---

Products/ZenCollector/configcache/invalidator.py

Fix _changed_device_class to receive the correct number of arguments.

---

Products/Jobber/config.py
Products/Jobber/jobs/job.py
Products/Jobber/jobs/purge_logs.py
Products/Jobber/log.py
Products/Jobber/model.py
Products/Jobber/scheduler.py
Products/Jobber/signals.zcml
Products/Jobber/storage.py
Products/Jobber/task/base.py
Products/Jobber/task/dmd.py
Products/Jobber/worker.py
Products/Jobber/zenjobs.py

Allow different zenjobs services to have separate config files.
ZEN-34771

add '--config-file' option to zenjobs.

---

Products/Jobber/config.py
Products/Jobber/zenjobs.py

fix: ensure Celery app has a useable default config.

---

Products/ZenCollector/configcache/invalidator.py

Always send build jobs to pick up potentially missed configs to support devices, like vSphere, that defer their modeling until a later time.
ZEN-34729

fix: send build jobs for updated devices to pick up new configs

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_dispatcher.py

When config's status is changed to Expired or Pending while the config is building, save the built config without changing its status.
ZEN-34754

fix: keep status while saving config when status is not Building.

---

Products/Jobber/scheduler.py
Products/Jobber/storage.py

Fixed zenjobs scheduler error while starting up

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_task.py

fix: clear cache statuses when no config is built.

---

Products/ZenCollector/configcache/modelchange/filters.py
Products/ZenRelations/ToOneRelationship.py

Add error handling to help identify issue.

---

Products/Jobber/model.py
Products/Jobber/scheduler.py
Products/Jobber/signals.zcml

Fix: Scheduled jobs were deleted without execution

---

Products/ZenCollector/configcache/dispatcher.py
Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_dispatcher.py
Products/ZenCollector/configcache/utils/__init__.py
Products/ZenCollector/configcache/utils/zprops.py

Small changes to hopefully reduce memory usage.

---

Products/ZenCollector/configcache/api.py
Products/ZenCollector/configcache/handlers.py
Products/ZenCollector/configcache/invalidator.py
Products/Zuul/facades/devicefacade.py

fix: Push Changes UI command forces configs to be built.

---

Products/Jobber/serialization.py
Products/Jobber/task/dmd.py
Products/ZenCollector/configcache/cache/model.py

Handle unicode inputs into the build_device_config task.

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/cli/list.py

Display statuses for configurations that don't have config data.

---

Products/ZenCollector/configcache/modelchange/oids.py

Also handle local and device class thresholds differently.
ZEN-34836

Handle local and device class templates differently.

---

Products/Jobber/jobs/purge_logs.py

Fix: purge_logs is not starting

---

Products/ZenUI3/browser/eventconsole/configure.zcml

ZEN-34864:ZEN-32760 Fix Event Archives pop-up view permissions

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

ZEN-34866:ZEN-33637 Fix the confirmation dialog for device deletion

---

Products/ZenUI3/browser/resources/js/zenoss/form/ComponentGraphPanel.js
Products/Zuul/facades/devicefacade.py
Products/Zuul/infos/metricserver.py
Products/Zuul/routers/device.py

ZEN-34882:ZEN-33814 ComponentGraphs fails to load high component count

---

Products/Jobber/storage.py

Setting the 'count' argument on calls to the redis' `scan_iter` method controls how many queries are made to Redis.  The way Redis is designed, fewer calls with more data returned per call usually results in better performance for all users of Redis.
ZEN-34539

Use redis' 'count' argument to reduce load.

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

ZEN-34883:ZEN-34422 Fix maintenance window edit permissions

---

Products/ZenStatus/ping/CmdPingTask.py

Pass an integer to ping's -w option.

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/cli/expire.py
Products/ZenCollector/configcache/cli/list.py
Products/ZenCollector/configcache/cli/remove.py
Products/ZenCollector/configcache/cli/stats.py
Products/ZenCollector/configcache/handlers.py
Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_storage.py
Products/ZenCollector/configcache/tests/test_task.py

configcache expire command should effect all statuses.

---

Products/ZenModel/migrate/addzNoRelationshipCopy.py
Products/ZenRelations/ToOneRelationship.py
Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/zPropertyCategory.py

(cherry picked from commit cadb4d2c659bf265059fcbcc8b307e70f1c27e2c)

ZEN-26428: make copied template not owned by original zenpack

---

Products/ZenCollector/configcache/handlers.py

Generating keys for all config types is required for new devices.

---

Products/ZenCollector/configcache/handlers.py

Use config cache `get_status` API correctly.

---

Products/ZenModel/ZenPack.py

Fix zenpack migration version comparison

---

Products/Zuul/facades/devicefacade.py

Hide "Available" folder for device view

---

Products/Jobber/monitor/collector.py
Products/Jobber/monitor/command.py
Products/Jobber/monitor/events.py
Products/Jobber/monitor/handler.py
Products/Jobber/monitor/inspector.py
Products/Jobber/monitor/logger.py
Products/Jobber/monitor/reporter.py

Ensure the correct logger is created.

---

Products/Jobber/monitor/collector.py
Products/Jobber/monitor/command.py
Products/Jobber/monitor/handler.py
Products/Jobber/monitor/inspector.py
Products/Jobber/monitor/logger.py
Products/Jobber/monitor/reporter.py

Added signal handler for better shutdown behavior.
ZEN-34970

Reworked logging configuration.

---

Products/ZenUI3/browser/modelapi/configure.zcml
Products/ZenUI3/browser/modelapi/modelapi.py

Add model API for zenjobs-monitor service

---

Products/Zuul/routers/zep.py

Fixed Advanced -> Events tab loading for admin

---

Products/Zuul/routers/zep.py

Correct admin access to event config fields

---

Products/Zuul/routers/zep.py

ZEN-34659:ZEN-34998 fix event conf field permissions

---

Products/ZenEvents/TrapFilter.py
Products/ZenEvents/tests/testTrapFilter.py

ZEN-34994:ZEN-34549 Fix do not drop all v3 traps

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/events/queue/tests/test_base.py
Products/ZenHub/events/queue/tests/test_deduping.py
Products/ZenHub/pinger.py
Products/ZenHub/server/avatar.py
Products/ZenHub/server/events.py
Products/ZenHub/server/executors/event.py
Products/ZenHub/server/executors/tests/test_workers.py
Products/ZenHub/server/executors/workers.py
Products/ZenHub/server/priority.py
Products/ZenHub/server/service.py
Products/ZenHub/server/tests/test_avatar.py
Products/ZenHub/server/tests/test_events.py
Products/ZenHub/server/tests/test_service.py
Products/ZenHub/server/tests/test_worker.py
Products/ZenHub/server/tests/test_workerpool.py
Products/ZenHub/server/utils.py
Products/ZenHub/server/worker.py
Products/ZenHub/server/workerpool.py
Products/ZenHub/tests/testPBDaemon.py
Products/ZenHub/tests/test_PBDaemon.py
Products/ZenHub/tests/test_pinger.py
Products/ZenHub/tests/test_zenhubclient.py
Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubclient.py
Products/ZenHub/zenhubworker.py

* Consolidated the ZenHubClient implementations
* zenhubworker notifies zenhub of shutdown
* zenhub has improved handling of lost zenhubworker connection
ZEN-34856

Added protocol for zenhubworker shutdown.

---

Products/ZenCollector/daemon.py

ZEN-35022:ZEN-34655 Fix collection for zenvsphere, zenperfsnmp

---

Products/DataCollector/plugins/zenoss/snmp/RouteMap.py

ZEN-35021:ZEN-34386 Add route types to RouteMap modeling plugin

---

Products/ZenEvents/TrapFilter.py
Products/ZenEvents/tests/testTrapFilter.py

ZEN-35020:ZEN-32183 allow v3 trap filtering and specific oid for v1

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

ZEN-35018:ZEN-34727 Fix for refresh button

---

Products/DataCollector/zenmodeler.py

ZEN-35035:ZEN-34423 zenmodeler startat and cycletime not work as intended

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/tests/test_PBDaemon.py

ZEN-35014:ZEN-34914 manager field is no longer included in events

---

Products/ZenModel/ZenPacker.py

ZEN-35015:ZEN-34923 Add unicode type check for the object id

---

Products/ZenCollector/cyberark.py

ZEN-34496:ZEN-34249 Handle chained certificate authorities for cyberark

---

Products/ZenCollector/config/task.py
Products/ZenCollector/daemon.py

Run the ConfigurationLoaderTask outside the scheduler.

---

Products/ZenMessaging/ChangeEvents/events.py
Products/ZenMessaging/queuemessaging/adapters.py

ZEN-34855:Fix MessagePostPublishingEvent is incorrectly decorated

---

Products/ZenCollector/configcache/cache/storage/device.py

Use json.loads to parse config data.

---

Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenRelations/ZenPropertyManager.py
Products/ZenUtils/snmp.py
Products/Zuul/interfaces/actions.py

Enable new SNMP cryptographic protocols.

---

Products/ZenCollector/services/ConfigCache.py

Convert generators into lists before sending over the network.

---

Products/ZenRelations/ToManyContRelationship.py

Add error handling when iterating over the content of a relation.

---

Products/ZenCollector/services/ConfigCache.py

Skip device configs that fail to load.

---

Products/ZenCollector/config/__init__.py
Products/ZenCollector/config/task.py
Products/ZenCollector/daemon.py
Products/ZenCollector/interfaces.py
Products/ZenCollector/scheduler/scheduler.py
Products/ZenCollector/scheduler/task.py
Products/ZenCollector/services/ConfigCache.py

The CollectorDaemon is also modified to have an optimized run path when collecting a CLI specified device.
ZEN-34895

Implement an API to retrieve a single device config.

---

Products/ZenCollector/configcache/cache/storage/device.py

Compress device configs when stored in Redis.

---

Products/ZenCollector/configcache/cli/remove.py

Add missing argument to `remove` method.

---

Products/ZenCollector/configcache/cache/model.py
Products/ZenCollector/configcache/cache/storage/device.py
Products/ZenCollector/configcache/cli/list.py
Products/ZenCollector/configcache/tests/test_deviceconfigstore.py

configcache `-u` option now works (again).

---

Products/ZenUtils/CmdBase.py

Don't print missing config file error.

---

Products/ZenCollector/configcache/cli/show.py

Also remove tracebacks when exiting early while writing to pipes.
ZEN-35104

Improve hiding of passwords in 'show' command.

---

Products/ZenEvents/EventServer.py
Products/ZenEvents/zentrap/app.py
Products/ZenEvents/zentrap/filterspec.py
Products/ZenEvents/zentrap/handlers.py
Products/ZenEvents/zentrap/receiver.py
Products/ZenEvents/zentrap/tests/test_filterspec.py
Products/ZenEvents/zentrap/tests/test_handlers.py
Products/ZenEvents/zentrap/trapfilter.py
Products/ZenHub/PBDaemon.py

Also restore missing zentrap heartbeat events.
ZEN-35073

Restore missing eventFilterDroppedCount event.

---

Products/ZenEvents/zentrap/__main__.py
Products/ZenEvents/zentrap/app.py
Products/ZenEvents/zentrap/capture.py
Products/ZenEvents/zentrap/decode.py
Products/ZenEvents/zentrap/filterspec.py
Products/ZenEvents/zentrap/handlers.py
Products/ZenEvents/zentrap/net.py
Products/ZenEvents/zentrap/oidmap.py
Products/ZenEvents/zentrap/processors.py
Products/ZenEvents/zentrap/receiver.py
Products/ZenEvents/zentrap/replay.py
Products/ZenEvents/zentrap/trapfilter.py
Products/ZenEvents/zentrap/users.py

Removed call to snmp_clone_pdu.

---

Products/Jobber/manager.py
Products/Jobber/meta.py
Products/Jobber/storage.py
Products/Jobber/task/base.py

Catch bad zenjobs task name earlier.

---

Products/ZenEvents/zensyslog/processor.py

Add `self` argument to SyslogProcessor method.

---

Products/Zuul/facades/reportfacade.py
Products/Zuul/infos/metricserver.py

Use group name for multigraph report

---

Products/DataCollector/SnmpClient.py
Products/DataCollector/zendisc.py
Products/DataCollector/zenmodeler.py
Products/ZenCollector/services/ConfigCache.py
Products/ZenHub/HubService.py
Products/ZenHub/services/DiscoverService.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenHub/tests/test_HubService.py
Products/ZenHub/zenhubclient.py
Products/ZenModel/Device.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenUtils/Executor.py
Products/ZenUtils/snmp.py

Replaced net-snmp specific code and implicit configuration with explicit, declarative, configurations.
ZEN-35109

Utilize pynetsnmp's improved API.

---

Products/ZenMessaging/queuemessaging/publisher.py

Ensure attribute exists before use.

---

Products/Jobber/tests/test_worker.py
Products/Jobber/worker.py

Raise SystemExit when unable to get a ZODB connection.

---

Products/DataCollector/SnmpClient.py
Products/DataCollector/zenmodeler.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenRRD/zenperfsnmp.py

Updated logging to improve SNMP troubleshooting.

---

Products/ZenEvents/zentrap/app.py
Products/ZenModel/SiteError.py
Products/ZenRRD/zenprocess.py

Correct the spelling of snmp.

---

Products/ZenRRD/zenprocess.py

Clean up SNMP event handling.

---

Products/ZenEvents/zensyslog/daemon.py

Pass the correct object into the Parsers initializer.

---

Products/DataCollector/SnmpClient.py
Products/ZenCollector/tasks.py
Products/ZenEvents/zentrap/users.py
Products/ZenHub/services/SnmpTrapConfig.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenRRD/zenprocess.py

Also updated code to support latest pynetsnmp changes.
ZEN-35105

Improve zenperfsnmp logging.

---

Products/ZenHub/server/events.py
Products/ZenHub/server/metrics.py

Initialize events so that zenhub metrics can decrement.

---

Products/DataCollector/zendisc.py
Products/ZenUtils/snmp.py

Fix device name discovery during Discover network

---

Products/ZenHub/PBDaemon.py

PBDaemon should always setup the event client.

---

Products/ZenUtils/snmp.py

Remove INFO log during snmp discovery

---

Products/ZenUtils/patches/zodbpackmonkey.py

Added methods to identify and remove orphaned references in ZODB.object_ref that were causing zenossdbpack to fail to remove oid groups.

Fixes ZEN-35223

---

Products/Zuul/facades/reportfacade.py
Products/Zuul/infos/metricserver.py

Use group name for multigraph report.

---

Products/ZenUtils/patches/mysqladaptermonkey.py
Products/ZenUtils/patches/zodbpackmonkey.py

mysqladaptor/zodbpack monkeypatch updates for RelStorage 3.5

---

src/Products/ZenCollector/configcache/tasks/deviceconfig.py

Use the correct attribute for the Celery job ID.

---

bin/runtests

Add support for docker compose based testing.

---

src/Products/ZenEvents/zentrap/receiver.py

Only free cloned PDU on snmp_send failure.

---

src/Products/ZenModel/zendmd.py

Restore the getFacade, setLogLeve, and listFacades functions to zendmd.

---

bin/zenupgrade
src/zenoss/patches/mariadb_answering.diff

Update mariadb_answering file to use mysql client.

---

src/Products/ZenUtils/CmdBase.py

Option names in an app's config file names are now mapped to the correct application config option.
ZEN-35303

Correctly apply config file to app options.

---

src/Products/ZenHub/zenhubclient.py

Ensure stale broker references are removed.
