zenoss/zenoss-prodbin

Products/ZenHub/PBDaemon.py

https://jira.zenoss.com/browse/ZEN-15892
ISSUE - This line is causing the jobs to be marked as failures. It looks like the health check is reporting a failure before the connection to zenhub is made
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenHub/PBDaemon.py#L997:
```
2014-12-26 16:29:12,770 ERROR zen.ZenDisc: ZenHub health check: ZenHub may be down. 
```
DEMO - ( notice lack of "ZenHub health check" error):
```
Log file: /opt/zenoss/log/jobs/4c59cd28-49b4-4d4d-ab82-8f6dda7e5dc0.log
2015-01-05 15:51:37,943 INFO zen.Job: Job 4c59cd28-49b4-4d4d-ab82-8f6dda7e5dc0 (Products.Jobber.jobs.SubprocessJob) received
2015-01-05 15:51:37,981 INFO zen.Job: Starting job 4c59cd28-49b4-4d4d-ab82-8f6dda7e5dc0 (Products.Jobber.jobs.SubprocessJob)
2015-01-05 15:51:37,982 INFO zen.Job: …
```

downgrade log.error to log.debug of zenhub health check warning for zenjobs success

---

Products/ZenUI3/docs/licenses.html

This is necessary to run Zenoss w/devimg, and should be replaced before
shipping the actual product

Add a dummy license

---

Products/ZenEvents/SyslogProcessing.py

Fixes https://jira.zenoss.com/browse/ZEN-15393,
Port of https://jira.zenoss.com/browse/ZEN-15936,
Originally reviewed by  Jason Peacock.

ZEN-15393: updated regexp for Cisco ACS syslog messages

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddDeviceController.js
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddDeviceView.js

Zenoss.remote.JobsRouter.deleteJobs doesn't return the response.

fixes ZEN-16496: Cannot delete device from add device option.

---

Products/ZenHub/__init__.py
Products/ZenHub/zenhub.py

https://jira.zenoss.com/browse/ZEN-16757
5.1.0 and 5.0.1 are missing Products/ZenHub/zenhub.py fix from 4.1.1 (https://jira.zenoss.com/browse/ZEN-6388) and 4.2.5:
https://dev.zenoss.com/tracint/browser/branches/core/zenoss-4.1.1-patches/patches/changeset_76100.diff?rev=76535
DEMO:
```
******** REMOTE ZENCOMMAND:
2015-02-20 17:41:32,441 INFO zen.zencommand: Attempting to connect to zenhub
2015-02-20 17:41:34,470 ERROR zen.zencommand: No event service: None
******** ZENHUB:
2015-02-20 16:48:40,435 DEBUG zen.ZenHub: set socket('0.0.0.0', 8789)  CONNECT_TIMEOUT:60  TCP_KEEPINTVL:15
2015-02-20 17:21:40,660 DEBUG zen.hub: removing listener for localhost:EventService
2015-02-20 17:21:40,660 DEBUG zen.hub: removing listener for localhost:CommandPerformanceConfig
```

fixes ZEN-16757: zenhub should use socket options for keep alive on PB connections

---

Products/ZenModel/migrate/migrateLocalhostPerf.py

This migrate script will migrate a non-CC-backed hub + collector toe be
CC-backed.  To be used during the 4x -> 5x migration

Migrate script for converting monitors

---

Products/ZenUtils/tests/testTopoPrioritize.py
Products/ZenUtils/zenpack.py

If impact was installed on the old image, ensure that we restore it first so that the pre-commit hook will be installed and active during subsequent ZenPack installs
Fixes https://jira.zenoss.com/browse/ZEN-17016

Ensure Impact is first ZenPack restored

---

Products/ZenHub/services/CommandPerformanceConfig.py
Products/ZenRRD/parsers/ps.py
Products/ZenRRD/zencommand.py

https://jira.zenoss.com/browse/ZEN-17304
revert #735 from https://jira.zenoss.com/browse/ZEN-16639
DEMO - :
```
[zenoss@7fc542bb3757 zenoss]$ patch --backup -p1 -R < /tmp/735.diff  
patching file Products/ZenHub/services/CommandPerformanceConfig.py
patching file Products/ZenRRD/parsers/ps.py
patching file Products/ZenRRD/zencommand.py
[zenoss@7fc542bb3757 zenoss]$ zencommand run -d 10.87.208.186                                       
2015-04-01 19:56:10,607 INFO zen.zencommand: Connecting to localhost:8789
2015-04-01 19:56:10,622 INFO zen.zencommand: Connected to ZenHub
2015-04-01 19:56:12,973 INFO zen.zencommand: 1 devices processed (118 datapoints)
2015-04-01 19:56:12,973 INFO zen.collector.scheduler: Tasks: 2 Successful_Runs: 1 Failed_Runs: 0 Missed_Runs: 0 Queued_Tasks: 0 …
```

fixes ZEN-17304: revert pull/735 from ZEN-16639

---

Products/ZenModel/migrate/setDMDVersion.py

https://jira.zenoss.com/browse/ZEN-17652
TODO: when cherry-picking this into support/5.0.x branch, make sure to set Version to to next release (5, 0, 3)
DEMO - after running the upgrade on a 5.0.1 system, dmd.version should show 5.0.70:
```
[root@resmgr-501 ~]# serviced script run /root/5.0.x/upgrade-resmgr.txt --service Zenoss.resmgr
...
I0430 17:55:31.193890 00913 runner.go:160] executing step 12: SVC_RUN Zenoss.resmgr/Zope upgrade
I0430 17:55:31.775394 00913 eval.go:259] running: serviced service run 348wjyzaxee7klbcqjt8okfqr upgrade
...
I0430 17:56:24.192131 02067 shell.go:225] Committing container
I0430 17:57:00.631921 00913 runner.go:152] Executing exit functions
Script done, file is /var/log/serviced/script-2015-04-30-175127-root.log
[root@resmgr-501 ~]# serviced service attach …
```

fixes ZEN-17652: set dmd.version for maintenance branch upgrades

---

Products/ZenUtils/ZenPackCmd.py

If something like a ```SystemExit``` gets raised in here, there's no indication that there was an issue and you just get a non-0 exit or the program.

Make failed zenpack install exit properly

---

Products/ZenUtils/ZenPackCmd.py

Prior to this fix, uninstalling a linked zenpack would not remove the
entry from easy-install.pth, or the egg link.

ZEN-17714: Uninstall linked ZP

---

Products/ZenModel/migrate/ChangeConInfoEngine.py

https://jira.zenoss.com/browse/ZEN-17756
UPGRADE from 5.0.0:
```
INFO:zen.migrate:Database going to version Zenoss 5.0.70
INFO:zen.migrate:Installing addPrefixToTriggerRule (5.0.3)
INFO:zen.migrate:Installing setDMDVersion (5.0.3)
INFO:zen.migrate:Installing ChangeConInfoEngine (5.0.70)
```
ISSUE:
```
[zenoss@5e1cab152109 ~]$ echo "print 'dmd.version=%s' % dmd.version;" | zendmd --script /dev/stdin
dmd.version=Zenoss 5.0.70
```

fix Migrate.Version

---

Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py

Changes:
- Updated flags 
- Renamed interfaces names exactly as for ifconfig
Retested again, Screenshot https://www.dropbox.com/s/imov2b062jzuvrd/Screenshot%202015-05-22%2000.33.52.png?dl=0

ZEN-16855: Linux_ifconfig Command Plugin fails on CentOS 7

---

Products/ZenUtils/patches/pasmonkey.py

ZEN-18828: Cherry-pick fix from ZEN-18656 (PR https://github.com/zenoss/zenoss-prodbin/pull/957) into support/5.0.x.

referenced the wrong method

---

Products/ZenUtils/zenpack.py

ZEN-18858: Use egg name parser to figure out how to fix broken zenpacks
Conflicts:
Products/ZenUtils/zenpack.py
https://github.com/zenoss/zenoss-prodbin/pull/969
DEMO:
```bash
$ serviced service run zope zenpack restore
I0723 13:32:29.831465 08928 server.go:341] Connected to the control center at port 172.17.42.1:4979
I0723 13:32:30.324930 08928 server.go:435] Acquiring image from the dfs...
I0723 13:32:30.326152 08928 server.go:437] Acquired!  Starting shell
I0723 13:32:30.327276 08928 shell.go:215] started command in container &{/usr/bin/docker [/usr/bin/docker run -v /home/smousa/src/europa/src/golang/bin:/serviced -v /home/smousa/src/europa/src/core:/mnt/pwd -v /home/smousa/src/europa/src/golang/src/github.com/control-center/serviced/isvcs/resources:/usr/local/serviced/resources -u …
```

ZEN-18858: Merge pull request #969 from zenoss/feature/ZEN-18858

---

Products/ZenUtils/__init__.py
Products/ZenUtils/patches/pasmonkey.py
Products/ZenUtils/pbkdf2.py

https://jira.zenoss.com/browse/ZEN-15413
Time measurements of `PBKDF2-SHA256` hashing function on the XX-Large Mem (8 CPU / 61GB / 100GB / High Network) AWS box:
```
In [1]: from Products.ZenUtils import pbkdf2
In [2]: s = pbkdf2.PBKDF2DigestScheme()
In [5]: salt = s._generate_salt(24)
In [14]: %timeit -n 50 s._encrypt('password', salt, iterations=100000, hash_len=24)
50 loops, best of 3: 214 ms per loop
In [16]: %timeit -n 50 s._encrypt('password', salt, iterations=200000, hash_len=24)
50 loops, best of 3: 444 ms per loop
In [17]: %timeit -n 50 s._encrypt('password', salt, iterations=300000, hash_len=24)
50 loops, best of 3: 668 ms per loop
In [18]: %timeit -n 50 s._encrypt('password', salt, iterations=400000, hash_len=24)
50 loops, best of 3: 887 ms per loop
```

ZEN-15413: Weak Password Hashing Algorithm

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

When the component deep-link is to a component on a device in a device
class that contains a space character, the UID will contain a
pre-escaped %20. This breaks the deep-linking unless we unescape it
first.
Fixes ZEN-18889.

Fix space-containing component deep-linking.

---

Products/DataCollector/zendisc.py
Products/ZenStatus/nmap/NmapPingTask.py
Products/ZenStatus/nmap/util.py

The major change was converting the code from the older twisted "driver" framework to the new "inline callbacks" framework.  Also made changes so that both zenmodeler and zendisc both used the same nmap based ping code.  The remaining changes were for improving some of the error handling, addressing issues identified by flake8 (a pyflakes + pep8 tool), and updates to use Python idioms.

ZEN-18971 zendisc now uses nmap for ping

---

Products/ZenModel/DataRoot.py

Patch catches zExceptions.Unauthorized and does not use the
zenoss_feedback_error_message template because unauthorized users
cannot access /zport/dmd resources. Instead, the generic error
template is used.

ZEN-16579 Physical paths exposed when sent malformed requests

---

Products/ZenModel/Device.py
Products/ZenModel/IpInterface.py
Products/ZenModel/LinkManager.py
Products/ZenModel/migrate/addNetworksPerDeviceCache.py

New data structure add to dmd.ZenLinkManager that stores the networks a device belongs to. Havin this information ready improves the overall performance of getChildLinks.
The data structure chosen is the following:
```
OOBTree
Key:    Device.id
Value:  OOBtree
Key:    Network
Value:  number of ip addresses that belong to that network
```

ZEN-14139: Improve getChildLinks performance

---

Products/ZenHub/PBDaemon.py

Prevent something like this from happening
```
2015-09-09 13:55:30,374 WARNING zen.pbclientfactory: Perspective ping timed out after 2 seconds
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
File "/opt/zenoss/lib/python2.7/site-packages/twisted/internet/tcp.py", line 299, in connectionLost
protocol.connectionLost(reason)
File "/opt/zenoss/lib/python2.7/site-packages/twisted/spread/pb.py", line 630, in connectionLost
d.errback(failure.Failure(PBConnectionLost(reason)))
File "/opt/zenoss/lib/python2.7/site-packages/twisted/internet/defer.py", line 423, in errback
self._startRunCallbacks(fail)
File "/opt/zenoss/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
self._runCallbacks()
--- <exception caught here> ---
File …
```

Be safer with error handling

---

Products/ZenUtils/controlplane/client.py

If an HTTP Request already has a cookie inserted, HTTPCookieProcessor
apparently does not update it. So in our retry loop that handles the 401
error, rebuild the Request each time.

Fixes ZEN-19507: Unauthorized flares

---

Products/ZenModel/migrate/fixZopeHealthCheck.py

Fixes ZEN-19335
The original fix for ZEN-19335 was based on the first fix for CC-1187. The healthcheck went through a couple of iterations. The fix in this PR matches the last (and hopefully final) iteration of the healthcheck.

Use the same script as applied to ZEN-19663

---

bin/zenrun
bin/zenrun.d/zenpack-manager.sh
bin/zenrun.d/zenpack.sh

A quick -- to mean "this ends the flag arguments" should do the trick.
Quoting $1 for safety.
Fixes ZEN-19369

Keeps declare in zenrun from misinterpreting flags

---

Products/Zuul/tree.py

Exception thrown should now only bear tail of traversed path
Fixes ZEN-18467

Remove vestigial logic from catalog getBrain

---

Products/Zuul/facades/metricfacade.py

The caller of ```_server_request``` is responsible for handling any exceptions, including logging.

ZEN-19815: Quiet down errors that should really just be debug

---

Products/ZenUtils/metricwriter.py
Products/ZenUtils/tests/test_metricwriter.py

DerivativeTracker.derivative() was ignoring datapoint rrdmin/rrdmax if
they were strings instead of int or float. This was especially
problematic since as far as I can see they're always strings because
RRDDataPoint._properties defines them that way.
Fixes ZEN-18991.

DerivativeTracker: Fix handling of string min/max.

---

Products/DataCollector/ApplyDataMap.py
Products/ZenHub/invalidationfilter.py
Products/ZenHub/services/ModelerService.py

This change incorporates the essence of the modeling optimization
currently being monkeypatched in by the vSphere ZenPack.
The optimization is first to wrap the application of all datamaps in a
single transaction instead of one transaction per datamap. This can
potentially reduce the number of invalidations generated by modeling a
large device.
The second part of the optimization is to wrap all datamap application
in a pausedAndOptimizedIndexing context manager to reduce roundtrips to
CatalogService. This can greatly reduce the time spent inside
ApplyDataMap when modeling a large device.
The final piece of this change is adding ProductClass to the list of
classes that are ignored by invalidation processing. This is mostly
unrelated to the optimization other than I saw a large number …

Incorporate vSphere modeling optimization.

---

bin/healthchecks/collectorredis/metrics
bin/healthchecks/redis/metrics

Backgrounded use of redis-mon in healthchecks so it still ships
its metrics data, but also added the use of redis-cli ping to make
sure a response from redis is what's being tested for.
Closes ZEN-20103

Update redis and collectorredis healthchecks

---

Products/ZenModel/migrate/enableCommitonUpgrade.py

Adds a migration to set CommitOnSuccess to True by default for
Zope's "upgrade" command.
Fixes ZEN-20119

ZEN-20119 Zope upgrade CommitOnSuccess=True

---

Products/DataCollector/PythonClient.py
Products/DataCollector/tests/testPythonClient.py

The results of SNMP modeler plugins (SnmpPlugin) are already processed
in the order the plugins are configured, but Python modeler plugins
(PythonPlugin) don't work this way. Their results are ordered according
to which plugin returns its data first.
Fixes ZEN-20364.

Honor zCollectorPlugins order for Python plugins.

---

Products/ZenModel/ZenPack.py
Products/ZenModel/tests/testZenPack.py
Products/ZenRelations/ZenPropertyManager.py

This corrects a problem where the type for a ZenPack's zProperty as
defined in its ZenPack.packZProperties property would be erased if the
same zProperty was also defined in ZenPack.packZProperties_data without
setting the type. This could end up being a common occurrence once
packZProperties_data becomes more widely known.
This fix prevents the erasure and makes packZProperties win any
disagreements in an attempt to provide the best backwards compatibility.
This problem can also easily be worked around in the ZenPack by adding a
type into the packZProperties_data for each zProperty in that dict.
Fixes ZEN-20359.

Fix packZProperties/packZProperties_data clashing.

---

Products/ZenUtils/controlplane/client.py

In an HTTP Request already has a cookie inserted, HTTPCookieProcessor
apparently does not update it. So in our retry loop that handles the 401
error, rebuild the Request each time.
Cherry-Picked from commit: 6219c53f451c74dc5a4784d3ecc28822db34f712
(Original title was: "Fixes ZEN-19507: Unauthorized flares")

ZEN-20516: Fix Advanced/Control Center screen shows error of Unauthorized

---

Products/Zuul/catalog/events.py

catalog.unindex_object_from_paths() doesn't work with CatalogService.
This was resulting in devices remaining indexed under DeviceGroup and
System paths even after those organizers were deleted. The result of
this was devices still being shown under the "Groups" and "Systems" root
organizers even though they no longer belonged to any groups or systems.
See comments of ZEN-20628 for a script that reproduces the problem and
verifies this solution.
Fixes ZEN-20628.

Fix onOrganizerBeforeDelete with CatalogService.

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddDeviceController.js

When adding a multiple devices SNMP credentials should be optional to match the behavior of the add a single device form.

Please review branch feature/ZEN-18954

---

Products/ZenUI3/browser/resources/js/zenoss/Reports.js

When a node is deleted in the reports tree an ExtDirect call is made to asyncGetTree() with all of the parameters of the deleted node.  The asyncGetTree method does not know what to do with these and an error appears.  Fix is to remove extra data from the call and just update the tree.

Please review branch feature/ZEN-20236

---

Products/Zuul/infos/metricserver.py

A single graph with multiple devices was showing null for the title.  It now uses the graph id.

Use the graph id as the title of a multi-graph with multiple devices

---

Products/DataCollector/plugins/DataMaps.py

Objects of the MultiArgs type cant't be used in tests, because of missed
__eq__() method implementation. Added the __eq__() method to fix it.
Fix suggested by @ssbunyk

ZEN-19774: Add __eq__() method to MultiArgs class

---

Products/ZenUI3/browser/eventconsole/columns.py

port from 4.2.5: https://github.com/zenoss/4.2.5-RPS/pull/639/files

ZEN-19017: [Event Console] Group and Systems Columns aren't Sortable

---

Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/tests/TestSchema.py
Products/ZenRelations/tests/testZenPropertyManager.py

Added some validation in custom attribute creation code.
Now the proper algoritm to create a custom property with `select` type is:
1. (Optional) Create first custom property with `Lines` type with each
selection separated with a carriage return.
2. Create second custom property with "Selection" type. You must set
existing
property or the custom property from (1) as the `Value`.
In this case the second cProp has a working drop down filled with the contents
from the 1st cProp.
Ported From: 85dea502ba13777282ddd113bbfeac1fd70ad4dc in 4.2.5-RPS

ZEN-20810: Select-type cProp results in site error on creation

---

Products/ZenUI3/browser/resources/js/zenoss/ExtOverrides.js

Fixed issue with using the shift key to select multiple records in a grid.

Please review branch feature/ZEN-18834

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddDeviceController.js

When adding a multiple devices SNMP credentials should be optional to match the behavior of the add a single device form.

Backport of merge #1150 

---

Products/ZenUtils/CmdBase.py

Reverts zenoss/zenoss-prodbin#1209
This change is too much of a "brute force" approach.  Different aspects of the system need INFO level logging for verification by users (as in, we don't know anything is happening unless we see logging).

Revert "Changed default log level to Warn"

---

Products/Zuul/infos/metricserver.py

When graphing multiple devices on a single graph the title was null

Use the graph id as the title of a multi-graph 

---

Products/ZenModel/migrate/zminionViaSupervisord.py

Modify zminion's startup command to use supervisord to divert output to rotated logfile.
Add a LogConfigs entry to forward this logfile to logstash.
Requires https://github.com/control-center/service-migration/pull/27 as it modifies a service's LogConfigs.

ZEN-20646 Run zminion via supervisord

---

Products/ZenModel/migrate/removeEmptyGraphdata.py

Modifies MonitoringProfile of zenmodeler services to remove
a number of graphs which were empty anyway.
Closes ZEN-20962

ZEN-20962 Remove empty graphs from zenmodeler

---

Products/ZenModel/Device.py

Method propertyItems() can return security data (e.g ssh password), so
we should forbidd acees to this method from UI to aviod of security
issues.
Co-Authored-By: Roman Bakaleyko <rbakaleyko@zenoss.com>

ZEN-20099: Make propertyItems() accessible only from python code

---

Products/ZenModel/Device.py

Method propertyItems() can return security data (e.g ssh password), so
we should forbidd acees to this method from UI to aviod of security
issues.
Co-Authored-By: Roman Bakaleyko <rbakaleyko@zenoss.com>
Cherry-Picked-From: a837c2cf6f9a5b10ac84c32b518178c9ad4f55b9

ZEN-21026: Make propertyItems() accessible only from python code

---

Products/ZenModel/migrate/addZenMailHealthCheck.py

In `zenmail` container:
```
[root@13159066a9a9 /]# echo 'QUIT' | nc -w 20 -C 127.0.0.1 50025                  
220 13159066a9a9 NO UCE NO UBE NO RELAY PROBES
221 See you later
[root@13159066a9a9 /]# echo 'QUIT' | nc -w 20 -C 127.0.0.1 50025 | grep '^220 '   
220 13159066a9a9 NO UCE NO UBE NO RELAY PROBES
[root@13159066a9a9 /]# echo 'QUIT' | nc -w 20 -C 127.0.0.1 50025 | grep -q '^220 '
[root@13159066a9a9 /]# echo $?
0
[root@13159066a9a9 /]# echo 'QUIT' | nc -w 20 -C 127.0.0.1 50025 | grep -q '^225 '
[root@13159066a9a9 /]# echo $?                                                    
1
[root@13159066a9a9 /]# echo 'QUIT' | nc -w 20 -C 127.0.0.1 50026 | grep -q '^220 '
Ncat: Connection refused.
[root@13159066a9a9 /]# echo $?
1
[root@13159066a9a9 /]# 
```
For reply code 220 please see …

ZEN-20640: zenmail failing on 5.x

---

Products/ZenModel/DataRoot.py
Products/ZenModel/SiteError.py
Products/ZenModel/ZenossInfo.py

getZenossRevision() method makes `svn info` call, which always fails, so
we can safely remove this method to clean code.
Also removed wildcard and unused imports. See PEP8 [0] for motivation
[0] - https://www.python.org/dev/peps/pep-0008/#imports

ZEN-11138: Remove getZenossRevision() and it's usage

---

bin/zenrun

Support commands provided by existing service definitions (e.g., Impact).
* Run commands which are on the path
* Return non-zero if the NOCOMMIT env variable is set to true
Fixes [ZEN-21081](https://jira.zenoss.com/browse/ZEN-21081)

Backwards compatibility for existing run commands

---

Products/ZenUtils/zenpack.py

This second fix covers installing an actual egg, which the initial fix
did not.

ZEN-20904: Prevent installing WebScale and Autotune

---

Products/ZenUtils/zenpack.py

This second fix covers installing an actual egg, which the initial fix
did not.
(cherry picked from commit 223c951c31df34dd6c880636caee8c7f95035ef9)

ZEN-18830: Prevent installing WebScale and Autotune

---

Products/ZenModel/DataRoot.py
Products/ZenModel/SiteError.py
Products/ZenModel/ZenossInfo.py

getZenossRevision() method makes `svn info` call, which always fails, so
we can safely remove this method to clean code.
Also removed wildcard and unused imports. See PEP8 [0] for motivation
Cherry-Picked From: 9cbc789bf3824269ce5467ec0b504295c4d6660c
[0] - https://www.python.org/dev/peps/pep-0008/#imports

ZEN-21093: Remove getZenossRevision() and it's usage

---

Products/ZenModel/Device.py

Method propertyItems() can return security data (e.g ssh password), so
we should forbidd acees to this method from UI to aviod of security
issues.
Co-Authored-By: Roman Bakaleyko <rbakaleyko@zenoss.com>
Cherry-Picked-From: a837c2cf6f9a5b10ac84c32b518178c9ad4f55b9

ZEN-21104: Make propertyItems() accessible only from python code

---

Products/ZenModel/migrate/README.md

Includes a short readme about creating and unittesting
new service migrations with the service-migration SDK.

Adds a README.md for service migrations

---

Products/ZenUtils/zenpack.py

Uses os.path to find the name of a Zenpack from a path argument.
Closes ZEN-21233

ZEN-21233 Link installing zenpacks fails

---

Products/ZenModel/migrate/README.md

The readme was already present in develop;
it had failed to make it to 5.1.x until now.

Added README for service migrations

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js
Products/Zuul/routers/zep.py

fixes https://jira.zenoss.com/browse/ZEN-21338
When the event query code is hit from the export button in the ui, the arguments were passed in as json which was not properly handled by the code that looks for "!!" and adds it to exclusion filter before performing the query.
The fix was to make sure that the `params` value passed into `findExclusionParams()` was a dict, and also to make sure the exclusion filter work was done before `_buildFilter()` was called on the `params` object.

fix ZEN-21338 saving event listed filtered with 'git status' as csv

---

bin/zenrun.d/upgrade.sh

zeneventserver-create-db schemas aren't relevant to the zodb table.
Addresses error messages during upgrade as mentiond in CC-1669

CC-1669 Removed zodb as target of upgrade.sh

---

Products/ZenModel/DataRoot.py
Products/ZenModel/SiteError.py
Products/ZenModel/ZenossInfo.py

getZenossRevision() method makes `svn info` call, which always fails, so
we can safely remove this method to clean code.
Also removed wildcard and unused imports. See PEP8 [0] for motivation
Cherry-Picked From: 9cbc789bf3824269ce5467ec0b504295c4d6660c
[0] - https://www.python.org/dev/peps/pep-0008/#imports

ZEN-21092: Remove getZenossRevision() and it's usage

---

Products/ZenModel/migrate/addZenMailHealthCheck.py
Products/ZenModel/migrate/makeMemcachedUpdates.py
Products/ZenModel/migrate/switchLoggingLevel.py
Products/ZenModel/migrate/updateOpenTSDBConfigs.py
Products/ZenModel/migrate/updateZeneventserverHealthCheck.py
Products/ZenModel/migrate/updateZookeeperConfigs.py
Products/ZenModel/migrate/updateZopeThreadsCount.py

Changed a number of instances of filter(...)[0] to accomodate
for the cases where a filter would result in no elements.
ZEN-20863 mentions one such case; because of the similarity this
patch includes changes to six other migration scripts.

ZEN-20863 More defensive migration scripts

---

Products/ZenUtils/zenpack.py

Exit with error on ZenPack install when --link is used but
no directory is provided --OR-- when egg file is provided and
--link option is not specified.

ZEN-21233 link installing zenpack fails for certain path descriptions

---

Products/ZenUtils/zenpack.py

Adjusted logic to allow --link and valid directory input.

ZEN-21233 installing zenpack via --link fails for certain paths

---

Products/ZenUtils/zenpack.py

Adjusted zenpack installation package detection logic to catch failed install situations
and fail gracefully.

ZEN-21297 zenpack install with --link fails for certain valid paths

---

Products/ZenUI3/browser/resources/js/zenoss/triggers.js
Products/Zuul/facades/triggersfacade.py

https://jira.zenoss.com/browse/ZEN-20715
These decorators in `triggersfacade.py` are not needed as methods check permissions in the code and take to account local permissions specified in the triggers/notifications itself.

ZEN-20715: Users other than Admin Cannot Update Triggers / Notifications

---

Products/ZenModel/Device.py

Cherry-pick of https://github.com/zenoss/zenoss-prodbin/commit/c63faff1e72668233ae8d59fc5801551d360299c

fixes ZEN-19385: Added an exclusion for /Ping device class.

---

Products/ZenModel/DataRoot.py

`socket` module used in getDefaultEmailFrom() function but don't imported.

ZEN-21544: Fix missed import in DataRoot module

---

Products/ZenModel/migrate/AddEndpointsToZenjobs.py
Products/ZenModel/migrate/addCentralQueryGraphConfigs.py
Products/ZenModel/migrate/addMemcachedService.py
Products/ZenModel/migrate/addQuiltInstallCommand.py
Products/ZenModel/migrate/addZenMailHealthCheck.py
Products/ZenModel/migrate/collectorDaemonsImportZproxy.py
Products/ZenModel/migrate/convertRunsToCommands.py
Products/ZenModel/migrate/duallogchange.py
Products/ZenModel/migrate/enableCommitonUpgrade.py
Products/ZenModel/migrate/fixZopeHealthCheck.py
Products/ZenModel/migrate/makeMemcachedUpdates.py
Products/ZenModel/migrate/removeEmptyGraphdata.py
Products/ZenModel/migrate/switchLoggingLevel.py
Products/ZenModel/migrate/templatizeCollectorEndpoints.py
Products/ZenModel/migrate/updateHBaseForNetcat.py
Products/ZenModel/migrate/updateOpenTSDBConfigs.py
Products/ZenModel/migrate/updateZeneventserverHealthCheck.py
Products/ZenModel/migrate/updateZentrapConfigs.py
Products/ZenModel/migrate/updateZookeeperConfigs.py
Products/ZenModel/migrate/updateZopeThreadsCount.py
Products/ZenModel/migrate/useBeakerInZope.py
Products/ZenModel/migrate/zenmodelerWorkers.py
Products/ZenModel/migrate/zminionViaSupervisord.py

At minimum, each cutover function logs that it's starting, and how many services are about to be affected.

ZEN-21569 Add log.info to migrations

---

bin/zenrun.d/upgrade.sh

Zope does not import the ZEP mariadb, so the schema updates performed
here are not persisted.

ZEN-21534: Moving ZEP DB upgrade out of Zope

---

bin/zenrun.d/upgrade.sh

Zope does not import the ZEP mariadb, so the schema updates performed
here are not persisted.

ZEN-21590: Moving ZEP DB upgrade out of Zope

---

Products/ZenModel/migrate/Migrate.py

Added a second log handler to capture zen.migrate contents
so the recent log.info lines will be visibile during the
course of `zenrun upgrade.sh doUpgrade`.

ZEN-21569 Verbose logging during service migration

---

Products/ZenUtils/controlplane/__init__.py

Changed controlplane to use the correct host IP.  Previously, it was using the IP of the agent's host, instead of the master.  It now attempts to read it from a new environment variable before falling back to global.conf.
The new environment variable is added here:  https://github.com/control-center/serviced/pull/2500

Fixes ZEN-21972 - Connection refused flare msg in Advanced->Control Center tab

---

Products/ZenModel/ZenPackLoader.py
Products/ZenRelations/ImportRM.py

This commit makes multiple related changes.
* Fix a bug that resulted in a commit-per-object for ZenPack upgrades
self.objectnumber in ImportRM would stay at 0. 0 modulo any chunk_size
evalutates to true. So a commit would happen for every object. There
was also a less significant case for ZenPack installations that did
add objects. In these cases self.objectnumber could remain modulu 0 to
chunk_size even if no further objects were being updated. To address
this, I added uncommittedObjects to track that number separately from
objectnumber.
* Wrap all XML object loading in pausedAndOptimizedIndexing
The main delay in loading objects is round trips to CatalogService
when commits happen. pausedAndOptimizedIndexing batches all of these
calls together to reduce round trips.
* Increase object …

Improve speed of loading objects from XML

---

Products/Zuul/facades/templatefacade.py

Fixed attribute-not-found error throwing an exception "Attribute not found dpName" by
first checking that the point being deleted is in fact a data point rather than a
ThresholdGraphPoint object.

ZEN-21978 Unable to remove data source

---

Products/Zuul/facades/templatefacade.py

Cherry-pick of ZEN-21978.
Fixed attribute-not-found error throwing an exception "Attribute not found dpName" by
first checking that the point being deleted is in fact a data point rather than a
ThresholdGraphPoint object.

ZEN-22036 Unable to remove data source

---

Products/ZenModel/data/devices.xml

Cast here.speed to a long to prevent a syntax error message while
monitoring this interface.

ZEN-22001 Syntax error in ethernetCsmacd_64 threshold

---

Products/Zuul/infos/metricserver.py

Multigraph reports when displaying identically-named components (think eth0 on several devices)
show only the data from the first component rather than multiple lines from multiple devices.
The fix is to uniquely identify the MetricServerGraphPoint by including device context value
into the line's id.

ZEN-22068 Multigraph reports show same data

---

Products/Zuul/infos/metricserver.py

Clone of ZEN-22068
Multigraph reports when displaying identically-named components (think eth0 on several devices)
show only the data from the first component rather than multiple lines from multiple devices.
The fix is to uniquely identify the MetricServerGraphPoint by including device context value
into the line's id.

ZEN-22079 Multigraph reports show same data

---

Products/ZenModel/NotificationSubscriptionWindow.py

Port of #1191 to support/5.1.x
Notification Subscription Window was failing during begin() and end()
due to a TypeError related to additional kwargs.

ZEN-22121 Notification schedule not sending event

---

Products/ZenModel/DataRoot.py
Products/ZenModel/Device.py
Products/ZenModel/IpNetwork.py
Products/ZenModel/Organizer.py
Products/ZenModel/ZenModelBase.py
Products/ZenModel/skins/zenmodel/Dashboard.pt
Products/ZenUtils/Utils.py

https://jira.zenoss.com/browse/ZEN-15410
Zope doesn't publish methods with no docstring set. Added the decorator to remove docstrings.

ZEN-15410: Cross Site Scripting from Exposed Helper Methods

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

Permissions were handled appropriately on the back-end, but the UI was not updating the enabled/disabled status of buttons when the context changes.  I added a callback method to update these when the user switches to a different selection in the tree.

Fixes ZEN-21945 "User cannot create maintenance window despite ZenManager privs to the organizer"

---

Products/ZenModel/ZenPackLoader.py
Products/Zuul/facades/triggersfacade.py

Zenpack developers can setup an actions.json which will create notifications and triggers upon zenpack installation. In order to link notifications to triggers, a UUID can be created and used in the actions.json. This PR deals with 2 issues around the UUIDs:
1) catches and warns of errors zep may throw in case of an invalid UUID
2) deals with case sensitivity discrepancy between a UUID string and the binary uuid value that gets stored in zep. If a UUID is passed into zep with uppercase characters, when it is later retrieved, the characters are all lowercased. Since zope stores the UUID as a string, this may cause lookups using string comparisons to fail.

ZEN-22237 - make actions.json more forgiving with uuids

---

Products/Zuul/infos/device.py

This reverts commit ff514e434d9db97e4c90a61cace72b0ba2d4de0d.

Revert "For devices modeled with SNMP use SNMP status to determine their status"

---

Products/ZenModel/data/devices.xml
Products/ZenModel/migrate/addzCommandUserCommandTimeout.py
Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/zPropertyCategory.py
Products/ZenUI3/browser/command.py

https://jira.zenoss.com/browse/ZEN-12936
Introduced new zProperty `zCommandUserCommandTimeout` to set timeout only for user commands.
Port from 4.2.5: https://github.com/zenoss/4.2.5-RPS/pull/724

ZEN-12936: User Commands button timeout broken

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/menus.xml
Products/ZenModel/migrate/addzCommandUserCommandTimeout.py
Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/zPropertyCategory.py
Products/ZenUI3/browser/command.py

https://jira.zenoss.com/browse/ZEN-22132
Port of the https://github.com/zenoss/zenoss-prodbin/pull/1555 to 5.1.x
ZODB dump had incorrect DB version (5.1.70) so I fixed this and reapplied all migrations with version 5.0.70 and above.

ZEN-22132: User Commands button timeout broken

---

Products/Zuul/infos/metricserver.py

clone of ZEN-22411.
The fix for ZEN-22079 changed the way ids could be prefixed to make them unique. This broke multigraph reports which used RPNs, as the rpn update code expects the _context.id (only) to be prepended to the _object.id. This change adds a _prefix field and saves the prefix, whether it's dev.id + _context.id or just _context.id. The _prefix field is then used to update the RPN, rather than assuming the metric will have _context.id (only) prepended. I have verified this on my dev system using test cases pertinent to both ZEN-22068 and ZEN-22411.

ZEN-22422: add tracking for metric prefixes, so RPN update works properly.

---

Products/ZenUtils/extdirect/zope/router.py

We were performing a strict comparison of the content type with the string "application/json", but valid content types can also contain charset definitions, e.g., "application/json; charset=utf-8", so this check was failing.

more robust content type checking

---

Products/ZenModel/ZVersion.py

Per Ian, we are deliberately abandoning the *.70 version scheme for the develop branch.
Fixes [ZEN-22760](https://jira.zenoss.com/browse/ZEN-22760)
See also https://github.com/zenoss/platform-build/pull/671

Bump Zenoss version to 5.2.0

---

Products/ZenModel/BatchDeviceDumper.py

Zenbatchdump fails on any 5.x deployment where there are collectors

---

Products/ZenUtils/zenpack.py

Changes the version check during restore so Zenpacks
new since the dmd version and no older than what's in ZVersion
are installed new.

ZEN-22820 Some Zenpacks missing in UCSPM 2.0.1 upgrade

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js

Graphs will now always fill columns. User setting of width is removed. User can still set height.

ZEN-22368 Set chart width to fill column

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddSmtpView.js

Removes need to override method for each branded skin.

ZEN-23111 remove "Zenoss" reference from Quickstart Wizard

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddSmtpView.js

Removes need to override method for each branded skin.

ZEN-23150 remove "Zenoss" reference from Quickstart Wizard

---

Products/ZenUtils/patches/zodbpackmonkey.py
Products/ZenUtils/zenhackdbpack.py
bin/zenossdbpack

- Add option to build internat tables using workers (-tw N_WORKERS)
- Add option to run traverse_graph method using less memory (downside: takes longer to run) (-m)
- Log to file
- Add tool and set of steps to be able to pack systems with huge databases that have never been packed

ZEN-22875: Improve zenossdbpack performance:

---

Products/ZenUtils/patches/zodbpackmonkey.py
Products/ZenUtils/zenhackdbpack.py
bin/zenossdbpack

- Add option to build internat tables using workers (-tw N_WORKERS)
- Add option to run traverse_graph method using less memory (downside: takes longer to run) (-m)
- Log to file
- Add tool and set of steps to be able to pack systems with huge databases that have never been packed
This is cherry-pick from https://github.com/zenoss/zenoss-prodbin/pull/1643

ZEN-23084: Improve zenossdbpack performance:

---

Products/ZenUI3/browser/pages.py

Port of #1691 
Fixes ZEN-23402

Don't include port when setting the cookie's domain

---

Products/ZenUI3/browser/resources/js/zenoss/Action.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

If role based permissions granted access to a button, the
button was always enabled.  This change allows other states
(like no devices being selected) to disable controls even
if the role has access to the function.  This check-in also
fixes a permission error for the action and commands dropdown
menus so they get disabled properly when permissions change.

Fix permission checks so that they fall through correctly

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/zenhub.py

Cherry-pick from https://github.com/zenoss/zenoss-prodbin/pull/1660

ZEN-22960: We should add an ID to identify the instance when using multiple hub instances

---

bin/zenpass

We no longer use zopectl, so we need to send control-c to the
runzope command to restart it.  We also give a help message
if they give arguments (like --help) to prevent passthrough to
the zpasswd.py Zope command.
https://jira.zenoss.com/browse/ZEN-23468

Update zenpass to work correctly.

---

.gitignore
javascript.mk
legacy/zensocket/README
legacy/zensocket/zensocket.c
makefile
zensocket.mk

Build zensocket as part of creating the prodbin artifact.
Note that the zensocket executable in /opt/zenoss/bin needs to be SETUID root, but this should be handled in the product-assembly repo somewhere. In the 5.0.x/5.1.x world, these settings where handled by `services/repos/zenoss5x/install-functions.sh` in the platform-build repo.

Import zensocket into prodbin

---

Products/ZenModel/BatchDeviceLoader.py

https://jira.zenoss.com/browse/ZEN-24030
Fixed spelling error in the 'Unknown Device' error.

ZEN-24030: fixed typo in error message

---

Products/Zuul/infos/metricserver.py

Multi graph reports not showing graph group name in title of the
graph, and is displaying graph definition name instead.
Check if the graph definition belongs to group and if yes, set
that group in title.

ZEN-23895: add group name to title in multi graph reports

---

Products/ZenUtils/MySqlZodbFactory.py
Products/ZenUtils/memcacheClientWrapper.py
Products/ZenUtils/tests/testMemcacheClientWrapper.py

Add zodb-cache-max-object-size config value which controls the server_max_value_length parameter of the initializer of the Client class in the memcache library.  This allows setting the max object size in memcached to a non-default value.
See also https://github.com/zenoss/ZenPacks.zenoss.EnterpriseCollector/pull/27, https://github.com/zenoss/zenoss-service/pull/301
Fixes [ZEN-24145](https://jira.zenoss.com/browse/ZEN-24145)

Add config value for memcache max object size 

---

Products/DataCollector/zendisc.py

ZenUtils.GlobalConfig.configToFlag() replaces underscores with en-dashes, which causes the prod_state confg to not be read from the config file. To fix, I added an alias option to the optparser config for zendisc so that the prod_state can be parsed from the config file.

ZEN-10184: add prod-state flag so it'll be picked in conf

---

Products/ZenUI3/security/authorization.py
Products/Zuul/security.py

This is to fix ZEN-24297: graphs timing out after 20 minutes.
Fix is twofold:
* remove abort call in authorization.py. This lets session information get saved when we update it
* in security.py - each time we check the token, refresh the exipration information. This will keep the token current, so the timeouts don't happen.
This fix also addresses a customer issue (zendesk ticket number 118031)

cherry-pick ZEN-24297 fix to maintenance branch for ZEN-24298

---

Products/ZenHub/zenhub.py

use request.getHeader instead of request.received_headers, which no longer exists
ZEN-24430

Fixes ZEN-24430 zensendevent fails with "500 Internal Server Error"

---

Products/ZenModel/migrate/updateZodbConfigFiles.py

Prior to this fix, the migration would fail on service trees which did not include the Zauth service.  (e.g., core, resmgr.lite, etc.)

Handle case where Zauth service is not present

---

Products/ZenUtils/controlplane/client.py

In some cases serviced returns a 104 error when we have not authenticated
and are trying to POST.  Sadly, urllib does not give us a nice error code
that we can check against.  All we can do is compare the error string to
a known string.
Fixes [ZEN-24363](https://jira.zenoss.com/browse/ZEN-24363)

Handle HTTP status 104 response from serviced

---

Products/DataCollector/SshClient.py

This fix was not sufficiently tested and contains syntax errors when
ssh keys are used.
Reverts the fix for ZEN-20463.

Revert pull/1823

---

Products/ZenUtils/zenpack.py

Reverts zenoss/zenoss-prodbin#1858
Due to the issues presented in ZEN-24751, these changes are being reverted until a definitive solution to ZEN-24751 can be found.

Revert "ZEN-24274 Fix install of community/custom ZenPacks during upgrades"

---

Products/ZenUtils/zenpack.py

Reverts zenoss/zenoss-prodbin#1872
Turns out these changes are needed to fix [ZEN-24654](https://jira.zenoss.com/browse/ZEN-24654), so putting the changes back in.

Revert "Revert "ZEN-24274 Fix install of community/custom ZenPacks during upgrades""

---

Products/ZenUtils/tests/testFindEggs.py
Products/ZenUtils/zenpack.py

When looking for the egg (or zip) of a ZenPack, the version string must convert its first dash into an underscore to match version string used in the naming of the egg (or zip) file.  This change moves that transform into the method that performs the search rather relying the caller to transform it.
This should finish fixing ZEN-24265.
The version transform issue was discovered while trying to determine the cause of [ZEN-24751](https://jira.zenoss.com/browse/ZEN-24751).  After ensuring that the version string was transformed correctly, the issue disappeared.

Always transform ZenPack version for egg file

---

Products/ZenEvents/SyslogProcessing.py
Products/ZenEvents/tests/testSyslogProcessing.py

SyslogProcessor have generated event that had cutted messages.
The issue took place because SyslogProcessor set original syslog message as event `summary`, that allows only 256 characters and after this CheckInputPipe class get event `message` from it`s `summary`.
This fix set event `message` directly from the original message.

ZEN-25261 Event message from zensyslog is cut off at 256 characters

---

Products/Zuul/routers/zep.py

`self._filterParser.findExclusionParams` has a naughty side-affect - it removes some keys from `params`
In develop it is fixed by #1353 
[Jira](https://jira.zenoss.com/browse/ZEN-24522)

ZEN-24522: Handle NOT operator in event console

---

Products/ZenEvents/Schedule.py

Fixes ZEN-24669 by setting status as "New" on Maintenance Start/Stop events so that maintenance window star events show up in the RM event console UI.

Fixes ZEN-24669 by setting status as "New" on Maintentenance Start/Stop events

---

Products/ZenUtils/ZenPackCmd.py

Reattempts the 'python setup.py develop' step of creating a new
ZenPack to counteract a problem with some filesystems, especially
across multi-host deployments.

ZEN-25294 Resource Temporarily Unavailable during zenpack install

---

Products/ZenUI3/browser/resources/js/zenoss/daemons/controller/DetailsController.js

In CC1.2 we simply proxy Kibana, making the keep-alive unnecessary.

Remove elasticsearch keepalive task

---

Products/ZenModel/actions.py

There was no timezone in in event time which may be confusing for
a user.
Fetch all time string in email body and add timezone to the end of
it.

ZEN-24535: add a timezone to event time in email

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml
Products/ZenModel/migrate/AddZepEndpointToZeneventd.py
Products/ZenModel/migrate/addKibanaRouteInZproxyConf.py
Products/ZenModel/migrate/addSnmpV3UserCommand.py
Products/ZenModel/migrate/addTagToImages.py
Products/ZenModel/migrate/addzCommandUserCommandTimeout.py
Products/ZenModel/migrate/beakerHttpOnly.py
Products/ZenModel/migrate/changeMemcachedStartup.py
Products/ZenModel/migrate/defaultBeakerToSecure.py
Products/ZenModel/migrate/disableZproxyAccessLog.py
Products/ZenModel/migrate/fixMariadbHealthCheck.py
Products/ZenModel/migrate/fixZauthHealthCheck.py
Products/ZenModel/migrate/moveProductionStateToBTree.py
Products/ZenModel/migrate/removeEmptyGraphs.py
Products/ZenModel/migrate/retryZopeHealthCheck.py
Products/ZenModel/migrate/templatizeCollectorEndpoints.py
Products/ZenModel/migrate/updateOpenTsdbCreateTables.py

Renumbering all migrations at least as young as 5.1.1 because
some releases and appliances had db versions ahead of the migrations
shipped.
Switching to a single-number scheme to reduce confusion and to break
the relation between releases of Zenoss and migrations of ZenModel--
they need not stay in lockstep.
The new scheme is based on 100 to make sure releases as early as 5.1.1
will run all of the necessary migrations, as the db version could be as
far forward as 5.1.70 in some systems.
We also re-generated the exported database files by deploying a clean Zenoss.core with the above changes and running zenwipe and then exportXml.sh

ZEN-25871 Change ZenModel migration numbering scheme

---

Products/ZenUI3/browser/eventconsole/export.py

- Reverted changes that unsuccessfully tried to fix this ticket (https://github.com/zenoss/zenoss-prodbin/pull/1790). 
- The issue is that, when exporting to cvs, each event detail gets its own column. Events with lots of details (like trap events) generate cvs with so many columns that the file was impossible to be read. To address this, all the event details that are returned in the "details" key by zep are put in one column.
- Also, now columns are arranged differently. First, the columns displayed in the event console, then all the remaining fields in alphabetic order and last but not least the details.
Example in the ticket: https://jira.zenoss.com/browse/ZEN-23871

ZEN-23871: event export to csv information overload

---

Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py

apply fixes for ZEN-25498 on Metis, which makes re-identifying a device recoverable, to RM 5.1.9

FIX ZEN-25952: porting fixes from PR1919 on develop to 5.1.9

---

Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js

Convert local date string to UTC date string before making a query request `/evconsole_router`.

Fix ZEN-23418: fix date range filtering by converting date filter params to UTC

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

[Jira](https://github.com/zenoss/zenoss-prodbin/compare/ZEN-25506)
We must display user's local time in date pickers, not UTC.

ZEN-25506 Use user local time in date pickers

---

Products/ZenEvents/EventClassInst.py
Products/ZenEvents/tests/testEventClassInst.py
Products/ZenRelations/ZenPropertyManager.py

Changed _updateProperty method in ZenPropertyManager
to compare sequences across results of sameKey
instead of all of Events.getInstances.

ZEN-23195 Fixed duplicate event detection

---

Products/Zuul/facades/devicefacade.py

This pr fixes https://jira.zenoss.com/browse/ZEN-20022 by putting ****** for the props value in the response object if the proptype is password.

ZEN-20022 Passwords visible as plaintext in Overridden Objects panel

---

Products/ZenModel/migrate/moveProductionStateToBTree.py

In order to limit memory consumption we now commit the transaction every 1000 devices.

ZEN-26000 migration moveProductionStateToBTree not scalable

---

bin/healthchecks/MetricShipper/store_answering

Reverts zenoss/zenoss-prodbin#1948, which used a more efficient health check -- that doesn't exist in 5.1.x.

Fix ZEN-26021: Restore the old shipper health check

---

makefile

Needed for Metis release process - ZEN-26069
Will be used in the Jenkins job [zenoss-prodbin-merge-support-52x](http://jenkins.zendev.org/view/zenoss-prodbin/job/zenoss-prodbin-merge-support-52x) to run a command like:
```
BRANCH=support-5.2.x make clean build
```
Which will produce an artifact with a name like `prodbin-5.2.0-support-5.2.x.tar.gz`

Allow the BRANCH make variable to be overriden from the command line

---

Products/Zuul/routers/device.py

[ZEN-25501](https://jira.zenoss.com/browse/ZEN-25501)

Escape name in DeviceRouter.getDeviceUuidsByName

---

Products/ZenModel/migrate/moveProductionStateToBTree.py

Better error handling in production state migration.  This handles a case that really only should occur if you are doing something you shouldn't.

ZEN-26126: Migration MoveProductionStateToBTree fails if zenpack code is missing

---

Products/Zuul/routers/device.py

ZEN-26128: Escape name in DeviceRouter.getDeviceUuidsByName

---

Products/Zuul/facades/__init__.py

https://jira.zenoss.com/browse/ZEN-25927
The commits in this PR change the behavior of moving a folder to only explicitly reindex the devices in the organizer/folder that is being moved at the old location.

ZEN-25927: Moving a Top Level Location Indexes All Devices in /Locations

---

Products/ZenUI3/browser/resources/js/zenoss/EvConsole.js

ZEN-26108 When you configure displayed columns in event console 'Create Incident' button disappears
is a PORT ticket for:
ZEN-23181 When you configure displayed columns in event console "Create Incident" button disappears

ZEN-26108 When you configure displayed columns in event console 'Create Incident' button disappears

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/editUserSettings.pt
Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/javascript.zcml

[Jira](https://jira.zenoss.com/browse/ZEN-25826)
In this PR I've added a new setting (on an user level) - user can now specify a date format which will be displayed on graphs.
Also, I've changed order of loading scripts on page - I need to have `ZenossData` JS snippet before `visualization.js` for zenoss/query#264

ZEN-25826 Add date format to user settings

---

Products/ZenWidgets/skins/zenui/locationGeoMap.pt
Products/ZenWidgets/skins/zenui/simpleLocationGeoMap.pt

Fixes browser SensorNotRequired warning by removing unneccesary Sensor querystring parameter.

ZEN-26572 Google Map API warning msg

---

Products/DataCollector/plugins/zenoss/snmp/InterfaceMap.py

This is port from https://github.com/zenoss/zenoss-prodbin/pull/2015
[JIRA](https://jira.zenoss.com/browse/ZEN-26580)

ZEN-26580: add netmask 64 to the ipv6 value from snmp

---

Products/ZenModel/migrate/AddHMasterRegionServerGraphConfigs.py
Products/ZenModel/migrate/FixDatapointsFormat.py
Products/ZenModel/migrate/addHBaseMetricsConfig.py
Products/ZenModel/migrate/addSnmpV3UserCommand.py
Products/ZenModel/migrate/addTagToImages.py
Products/ZenModel/migrate/addzCommandUserCommandTimeout.py
Products/ZenModel/migrate/beakerHttpOnly.py
Products/ZenModel/migrate/changeMemcachedStartup.py
Products/ZenModel/migrate/checkHBaseTablesExist.py
Products/ZenModel/migrate/disableZproxyAccessLog.py
Products/ZenModel/migrate/enableNginxPagespeed.py
Products/ZenModel/migrate/fixDefaultmappingSequences.py
Products/ZenModel/migrate/fixMariadbHealthCheck.py
Products/ZenModel/migrate/fixZauthHealthCheck.py
Products/ZenModel/migrate/moveProductionStateToBTree.py
Products/ZenModel/migrate/removeEmptyGraphs.py
Products/ZenModel/migrate/removeRegionServerPrereqs.py
Products/ZenModel/migrate/retryZopeHealthCheck.py
Products/ZenModel/migrate/setMariaDbConfigDefaults.py
Products/ZenModel/migrate/updateHBaseLogPath.py
Products/ZenModel/migrate/updateMariaDbPoolAllocations.py
Products/ZenModel/migrate/updateMemcachedMaxObjectSize.py
Products/ZenModel/migrate/updateMetricsHealthchecks.py
Products/ZenModel/migrate/updateOpenTSDBConfigRandomUIDEnable.py
Products/ZenModel/migrate/updateOpenTsdbCreateTables.py
Products/ZenModel/migrate/updateZepLogbackConfig.py
Products/ZenModel/migrate/updateZodbConfigFiles.py
Products/ZenModel/migrate/updateZopeAnsweringHealthChecks.py
Products/ZenModel/migrate/updateZproxyPagespeedUpstreams.py

This one:
https://github.com/zenoss/zenoss-prodbin/blob/support/5.1.x/Products/ZenModel/migrate/removeEmptyGraphs.py
has switched 5.1.x dmd.version to 107, because of that a lot of 107 migrations from 5.2.x are not run during 5.1.x -> 5.2.1 upgrade and because of this we have an issue described in ZEN-26635.

ZEN-26635: Tracebacks on upgrade from 5.1.10 to 5.2.1

---

Products/ZenRelations/ImportRM.py

When installing zenpack, it ignors what OIDs are already
in the system and just create duplicates in its MIBs modules.
When zenpack install  OIDs using object.xml check whether OID
is presented in the system, and if yes skip creating new OID.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-17882)

ZEN-17882: check for existing OIDs when installing zenpack

---

Products/Zuul/facades/devicefacade.py

Also ZEN-22396. Get component graph legends to show same name regardless of "All on Same Graph" checkbox state.

ZEN-26498 Component graph legends

---

Products/ZenUI3/browser/resources/js/zenoss/Renderers.js
Products/ZenUI3/browser/resources/js/zenoss/Types.js

The 'Links' for the device are broken.
Add hyperlink handling when we get hyperlink tag
of guest device from some main one.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-26628)

ZEN-26628: add hyperlink tag handling

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Open graph in the new tab the zoom in/out/arrow buttons do not work.
If we cannot get drange from graphPanel take it from graph params.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-26758)

ZEN-26758: set drange variable when graph is opened in the new tab

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

The legend can be quite large due to the volume of data
points and data point names being long so there is no way
to scroll down to graph.
Add autoScroll to config of the expandGraph window.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-26760)

ZEN-26760: add autoScroll option to expandGraph window

---

Products/ZenHub/zenhub.py
Products/ZenHub/zenhubworker.py

This adds hook for ZenHub to wait some amount of time before `kill -SIGUSR2` a new hubworker process. Zenhubworker instances are configured to ignore SIGUSR2 until its initialization is complete.

Fix/ZEN-26671 - zenhub stats kill zenhubworker processes

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceOverviewPanel.js

[Jira](https://jira.zenoss.com/browse/ZEN-26620)
Additional fix for https://github.com/zenoss/zenoss-prodbin/pull/2042
Fix provides html encoder for `snmpCommunity` field.

ZEN-26620 XSS on the device's details page

---

Products/Zuul/facades/devicefacade.py

https://jira.zenoss.com/browse/ZEN-26519
These changes fix ZEN-26519 by checking the graph definition for each component instead of assuming they all have the same graph definition.  If a component does not have a graph definition, the behavior remains the same.

Allow components to have unique graph definitions

---

Products/ZenModel/zenmib.py

When we install new MIB file zenmib will just remove the old one
and install new one, despite fact that previous MIB file was newer
or there was some nodes or notification added manually, this will
cause a crash of eventClassMappings.
If that MIB file is in the system, take that object and just update
it.

ZEN-17882: update MIB module instead of remove.

---

Products/ZenModel/MinMaxThreshold.py

Before:
2017-02-27 18:48:23,287 ERROR zen.MinMaxCheck: User-supplied Python expression (here.BAD) for minimum value caused error: ['laLoadInt5_laLoadInt5']
After:
2017-02-27 20:35:52,306 ERROR zen.MinMaxCheck: User-supplied Python expression (here.BAD) for minimum value caused error: ['usedBlocks_usedBlocks'] of FileSystem testFS in Device 10.87.128.92

Add dev and comp ids in log msg when data source expression is invalid

---

Products/ZenHub/services/CommandPerformanceConfig.py
Products/ZenModel/MetricMixin.py
Products/ZenModel/RRDDataSource.py

To measure the performance improvement, the following code was run in the 5.2 environment ZEN-26606 was reported (with Impact) and an aws 5.3 system:
```
devices = [ "10.88.111.101", "10.88.111.102", "10.88.111.112", "10.88.111.113", "10.88.111.114", "10.88.111.115", "10.88.111.116", "10.88.111.130", "10.88.111.131", "10.88.111.132", "10.88.111.133", "10.88.111.134", "10.88.111.135", "10.88.111.136", "10.88.111.137", "10.88.111.138", "10.88.111.145", "10.88.111.150", "10.88.111.16", "10.88.111.17", "10.88.111.18", "10.88.111.180", "10.88.111.181", "10.88.111.184", "10.88.111.185", "10.88.111.187", "10.88.111.24", "10.88.111.49", "10.88.111.60", "10.88.111.61", "10.88.111.70", "10.88.111.71", "10.88.111.75", "10.88.111.77", "10.88.111.78" ]
from …
```

ZEN-26606: do not call device() on components more than needed

---

Products/DataCollector/zenmodeler.py

The following changes are to provide more accurate timing info for modeling runs (port of #2130)
- add flag to check whether any devices were processed during
`ZenModeler` collector loop
- raise level of log message denoting start of collector loop for
proper modeling run timings

Fix ZEN-26944: log start of model run at info level, log if no collection happened

---

Products/DataCollector/zenmodeler.py

I did the following to provide more accurate timing info for modeling runs
- add flag to check whether any devices were processed during
`ZenModeler` collector loop
- raise level of log message denoting start of collector loop for
proper modeling run timings

Fix ZEN-26637: raise log level message for start of model run, log if no collection happened

---

Products/ZenHub/zenhub.py
Products/ZenHub/zenhubworker.py
Products/ZenUtils/debugtools.py
Products/ZenUtils/tests/testContinuousProfiler.py

* add the zenhubworker PID to zenhub stats output
- zenhubworker will report its PID when reportingForWork
- zenhub will output the PID for each worker along with its stats
- zenhub will warn when a worker's status doesn't match its stats
- This is change is intended to provide more info when debugging
zenhub activity
* added class+tests for continuous profiling
* add zenhub config option to run with profiler on
* add cmd config option for profiling zenhubworkers
* fix typo that would've coused incorrect signal handler registration

5.2.x port of feature/ZEN-26752 zenhub enhancements (#2073)

---

Products/Zuul/facades/devicefacade.py

Identify metrics in all-in-same-graph graph by the same name when in individual charts.

ZEN-26741 All on Same Graph Legends

---

Products/ZenModel/Device.py

Devices whose production state had been set above their
threshold were not generating events, and devices with their
threshold above their production state continued to generate
events.
Setting _p_changed is enough for that change to take hold and be
propagated to start and stop those events from being generated
as expected.

ZEN-26530 Event generation ignoring production state changes

---

Products/ZenEvents/tests/test_zentrap.py
Products/ZenEvents/zentrap.py

Fixes ZEN-24658
SNMP Trap values of "BASE64:..." for values we failed to decode
were causing confusion for users who believed the original trap
was sent in base64.
* new value reads "Failed to decode: converted to BASE64:"<base64 encoded value>"
* adds unit tests for zentrap

Adds explicit description of snmp decode failure

---

Products/ZenModel/Device.py

If device wasn't modeled we could set its ip to other
devices and than have several devices with the same ip.
We were searching for the duplicate ip first in Network
and then from IP object we were taking a device object,
but if device wasn't modeled ip from Network wasn't assigned
to it. Now try to find device by its ip from Devices.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-23718)

ZEN-23718: check if device with the same ip exist

---

Products/ZenWidgets/browser/Portlets.py
Products/Zuul/facades/__init__.py
Products/Zuul/tests/test_devicefacade.py

In the unit tests for this set of fixes:
* `collector` is used as a non-indexed field
* `name` is used as an index field

ZEN-26894 fix production state sort error

---

Products/ZenEvents/tests/test_zentrap.py

Fixes ZEN-27062
* After testing and review, we decided not to change the implementation.
* Adds test suite for zentrap.TrapTask._convert_value() method
* Adds unittests that validate existing functionality.

Adds unittests for ZenEvents/zentrap

---

Products/ZenEvents/tests/testTransforms.py

A race condition was causing event transform tests to fail intermittently.
This commit separates one test into three to resolve this.

BLD-75 Split ZenEvent transform tests

---

Products/ZenUI3/browser/resources/js/zenoss/EvConsole.js
Products/Zuul/routers/zep.py

Users who have no global role, but have adminObjects added to their account are not able to act upon events in the global EvConsole, because they lack a global context on which to check permissions. These changes address this:
* in the UI by checking the combined permissions on the currently selected events in the EventPanel Grid, which re-nables the event action toolbar;
* on the server-side, for each event on which an action is requested, we check user permissions for that event's target device.

Fix ZEN-26417: port of #2118 to support/5.2.x

---

bin/quiesce-mariadb.sh

https://jira.zenoss.com/browse/ZEN-23656
The script was renamed but the main function wasn't changed; result is that zodb/zep haven't been properly paused for backups since Nov 2014.

Fix filename in quiesce-mariadb.sh to match file rename

---

Products/ZenHub/tests/testWorklist.py
Products/ZenHub/zenhub.py
Products/ZenModel/DataRoot.py
Products/ZenUtils/zenpack.py

https://jira.zenoss.com/browse/ZEN-27160
Port of https://github.com/zenoss/zenoss-prodbin/pull/2236
Added dmd.startPauseADM() and dmd.stopPauseADM() to prevent zenhub from assigning applyDataMaps jobs to workers. The pause has a configurable timeout that defaults to 1 hour.

ZEN-27160: Pause zenhub applyDataMap jobs during zenpack install/upgrade/remove

---

Products/ZenModel/migrate/updateZeneventserverHealthCheck.py

Migration script wasn't runned when we were upgrading
from 5.1.10 since db version in 5.1.10 was higher than
migration.
Bump the version to last.

ZEN-27229: bump the version on the migration script

---

Products/ZenModel/migrate/updateZeneventserverHealthCheck.py

This is port from #2282 
[JIRA](https://jira.zenoss.com/browse/ZEN-27380)

ZEN-27380: bump the version on the migration script

---

Products/ZenModel/DmdBuilder.py
Products/ZenModel/IpNetwork.py
Products/ZenTestCase/BaseTestCase.py
Products/Zuul/catalog/model_catalog_tool.py
Products/Zuul/facades/__init__.py
Products/Zuul/facades/processfacade.py
Products/Zuul/tests/base.py
Products/Zuul/tests/test_devicefacade.py
Products/Zuul/tests/test_mibfacade.py
Products/Zuul/tests/test_processfacade.py
Products/Zuul/tests/test_servicefacade.py

This PR allows catalog searches against unindexed fields and fixes some issues with search revealed by the Zuul integration tests.  It also makes changes to the test framework to enable tests that use the ModelCatalog.

Improve search, fix some of the Zuul tests

---

Products/ZenUtils/ZenPackCmd.py

port from https://github.com/zenoss/zenoss-prodbin/pull/2290
[Jira](https://jira.zenoss.com/browse/ZEN-27341)

ZEN-27341 ZenPack dependencies not always installed in correct order

---

Products/Zuul/catalog/model_catalog.py
Products/Zuul/catalog/model_catalog_tool.py

The commit_dirty param controls the ability to commit a transaction for objects that have been modified, but whose transactions have not been explicitly committed yet.

Add commit_dirty param to searches.

---

Products/Zuul/catalog/indexable.py

'uid' is a special case in our schema that is always untokenized, so we need to mark it as such for queries against it to work.

Use untokenized field type for uid

---

Products/ZenUtils/elastic/client.py

Number of log files for zope was different
from number of log files that should be
created. In addition, support bundle wasn't
working at all, since we moved to newer
version of ES.
Changed query to elastic, now using scroll api,
file name format now include instance id
instead of host name.
[JIRA](https://jira.zenoss.com/browse/ZEN-27520)

ZEN-27520: changed api query to elstic

---

Products/ZenEvents/zeneventd.py
Products/ZenUtils/MetricReporter.py
Products/ZenUtils/ZCmdBase.py

Removed two extra log.info lines from MetricReporter
Moved MetricReporter instance from ZCmdBase to zeventd

ZEN-27437 Remove extra log.infos from MetricReporter

---

bin/metrics/zenossStatsView.py

Fixes an attribute error causing every zproxy metrics publish attempt to fail.

ZEN-27333: Fix for self.interval exception

---

Products/ZenModel/actions.py

[Jira](https://jira.zenoss.com/browse/ZEN-27621)

ZEN-27621 Incorrect time sent in syslog notification

---

bin/metrics/zenossStatsView.py

Semicolons were not being properly stripped from
the results of reading the zope upstreams file.

ZEN-27333 Fixed parsing bug in zenossStatsView

---

Products/ZenModel/actions.py

port from #2340
[Jira](https://jira.zenoss.com/browse/ZEN-27358)

ZEN-27358 Incorrect time sent in syslog notification

---

Products/ZenEvents/tests/testTransforms.py

Stopping the metricreporter should be enough to prevent
attempts to connect to the metric store.

ZEN-27663 Silences metricreporter during unit tests.

---

Products/Zuul/catalog/indexable.py

Part of the fix for ZEN-27659
We switch fields that are logically a single token or that will mostly only be searched for exact matches to be untokenized.

Switch some fields to untokenized

---

Products/ZenEvents/zenactiond.py
Products/ZenUtils/MetricReporter.py

MetricReporter now has a simple AsyncMetricReporter subclass that
makes use of twisted.reactor to wrap the write() method.
Zenactiond now uses Metrology timers to collect metrics on notifications and signals processed.

ZEN-27608 Instrument zenactiond to collect metrics

---

Products/ZenModel/migrate/UpdateRedisBindAddress.py

The migration changes redis config to explicitly listen on 0.0.0.0 since newer versions of redis only listen on 127.0.0.1 by default.

Bump migration number since it was being skipped in Thebe upgrade.

---

Products/ZenModel/ManagedEntity.py

Certain tests don't like it if there is an entry under _properties that is actually a python property on the object (as opposed to an attribute).  'productionState' didn't exist in the _properties list back when we were storing them in a BTree, so it doesn't appear to be necessary.

Remove productionState from ManagedEntity._properties

---

Products/Zuul/facades/metricfacade.py

To prevent any accidental renaming, central query are updated so as to rename either a prefix or a whole name. This change is to utilize the updated feature in central query,

Make separate requests for renaming metrics and tagv

---

Products/ZenModel/MibModule.py
Products/ZenModel/MibOrganizer.py
Products/ZenModel/zenmib.py
Products/ZenRelations/ImportRM.py
Products/ZenUI3/browser/resources/js/zenoss/MIBs.js
Products/Zuul/facades/mibfacade.py
Products/Zuul/infos/mib.py
Products/Zuul/routers/mibs.py

These changes should be improve MIB management.  The main change is to allow ZenPacks, the `zenmib` utility, and users at the web UI to replace existing OIDs.  Prior Zenoss releases have either allowed multiple instances of the same OID to exist or prevented duplicate OIDs by raising an exception.
Should address many of the concerns expressed in ZEN-27323.

Prevent duplicate OIDs

---

Products/ZenModel/MibModule.py
Products/ZenModel/MibOrganizer.py
Products/ZenModel/zenmib.py
Products/ZenRelations/ImportRM.py
Products/ZenUI3/browser/resources/js/zenoss/MIBs.js
Products/Zuul/facades/mibfacade.py
Products/Zuul/infos/mib.py
Products/Zuul/routers/mibs.py

These changes should be improve MIB management. The main change is to allow ZenPacks, the `zenmib` utility, and users at the web UI to replace existing OIDs. Prior Zenoss releases have either allowed multiple instances of the same OID to exist or prevented duplicate OIDs by raising an exception.
Should address many of the concerns expressed in ZEN-27612.

Prevent duplicate OIDS.

---

Products/Zuul/catalog/model_catalog_init.py

1. Added new options to soft reindexer that lets you scope reindexing by root and type and perform soft reindexing of specific fields only
2. Fixed a race condition where the soft reindexer would never terminate by making it so that workers hold the semaphore while they are idle (waiting on the parent queue) vs. the opposite.
3. Fixed a race condition where the soft reindexer would terminate prematurely by using a sentinel value to indicate the end of the data (for soft re-indexing only)
4. Fixed an issue where some workers may get killed during their final index batch due to a short timeout on the join() call.
5. Made the time calculation more accurate.

fix model index init issues

---

Products/ZenModel/ZDeviceLoader.py

When we were adding CC host first as /Server/SSH/Linux or
/Server/Linux device class and then using the VIP to
the /Control Center device class The CC device will not
appear even though the job completes successfully.
A device can't be added since the VIP was already assigned
to device when it was first added and modeled as
/Server/SSH/Linux or /Server/Linux. An error wasn't raised
since exception was catched. Now give an error log and raise
an exception for job to be failed.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-27932)

ZEN-27932: change debug to error log and raise an exception

---

Products/ZenRelations/ZenPropertyManager.py

When editing multiline credentials, the credentials are now masked
in the audit log.

Hide Password Field in Audit Log Messages

---

Products/Zuul/facades/__init__.py

On Infrastructure page if you enter IPv6 address in ip address
column filter it won't match any device. IPv6 filtering is
not working.
Using new index idx_ipAddressAsText  for searching in model
catalog which was added with solr implementation.
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/Zuul/catalog/indexable.py#L105

ZEN-27921: using new index in modelcatalog for ip search

---

Products/ZenEvents/tests/test_zentrap.py
Products/ZenEvents/zentrap.py

Fixes ZEN-27714
* Add test case for `int` and `long` types
* Add decoder that returns the unaltered value for numerics

Add decoder for numerical values

---

bin/quiesce-rabbitmq.sh

https://jira.zenoss.com/browse/ZEN-28014
For systems upgraded from <= 5.0.9, the rabbit node name will be different compared to new systems.  In earlier systems, this was "rabbit@localhost".  In newer systems this is "rabbit@rbt0" (which also matches the hostname).  Upgraded systems still have the old rabbit node name.  In either case, the node name is defined in the rabbit conf file (this config file/location hasn't changed).  Read the node name from /etc/rabbitmq/rabbitmq-env.conf file directly in the quiesce script to avoid giving the wrong node name.

Use the rabbit-env.conf to get the rabbit node name

---

Products/Zuul/routers/properties.py

The password would be visible in plain text in audit log messages.
It would appear in the zProperty field where the entire JSON object
was displayed.  This change just puts the key (which is the
property name you get by looping through the JSON object) into
that field.

Fix Password Appearing in Audit Messages

---

Products/ZenModel/IpInterface.py

Modifies the change made here:  https://github.com/zenoss/zenoss-prodbin/commit/6d2edce8b248ee9452da094a0d3f489a12a468cd
Admin status of '0' is "Unknown".  We will still monitor until the admin status is known to be "Down", "Testing" or anything that isn't "Up".  This also fixes some zenpack unit tests that were failing due to this change.

Dont monitor if admin status is > 1

---

Products/ZenCollector/interfaces.py
Products/ZenCollector/scheduler.py
Products/ZenCollector/tasks.py

Add suppress_late property to IScheduledTask and set False in BaseTask, then check it in calls to late() in the scheduler.

Allow tasks to opt out of being counted in missedRuns

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

The context menu option for refreshing a tree was not working.  It
should now be fixed.  Also, making changes to the tree (e.g. Adding
a new process organizer) did not properly refresh the tree. This is
also fixed.

Fix Tree Refresh

---

Products/ZenModel/migrate/addOpenTSDBLogbackConfig.py

The highest value for `Migrate.Version` on the `support/5.2.x` branch is 115. Therefore, for this migration to take effect when upgrading from 5.2.6 to 5.3.0, we need to specify the next highest value; e.g. 116

Bump Migrate.Version for 1 higher than highest version for 5.2.x

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Fixes truncated lower legend names -- most often seen when the "show all on one graph" checkbox is checked.

ZEN-24402 Graph legends truncated

---

Products/ZenModel/WinService.py
Products/Zuul/infos/component/winservice.py

Fixes ZEN-28263
Disabled windows services need to be able to be monitored to ensure
that they are in a STOPPED state.

Allow Disabled WinService to be monitored via gui

---

Products/ZenModel/migrate/tests/common.py

More fixes for CC-3673 - this time, additions to the unit-test harness used to test service migrations to all for verifications of calls to `addLogFilters`

CC-3673: Update unit-test harness to validate addLogFilter

---

Products/Zuul/routers/device.py

The add device form tries to fetch 'credential related' properties from the back end as the user is typing in the device class name. The stale data dialog reported in the ticket is the result of an ObjectNotFoundException happening in the facade layer.

Handle case where only part of the device class has been typed in, so no properties are (yet) found.

---

Products/Zuul/facades/devicefacade.py

No components are loaded at all if there is an object with a
broken component search.
Load all the components and scrip the broken one and log a
message that there is a broken component.
this is port from https://github.com/zenoss/zenoss-prodbin/pull/2619
[JIRA](https://jira.zenoss.com/browse/ZEN-21889)

ZEN-21889: catch the exception if there is a broken component search

---

.gitignore
Products/ZenModel/ZMigrateVersion.py.in
Products/ZenModel/ZVersion.py.in
Products/ZenModel/migrate/README.md
makefile
replace-zmigrateversion.sh
zenoss-version.mk

Cherry-pick changes from https://github.com/zenoss/zenoss-prodbin/pull/2605 to improve handling of SCHEMA versions between releases.  
For more details, see https://github.com/zenoss/zenoss-prodbin/pull/2605 and the changes to `Products/ZenModel/migrate/README.md` in this PR.

Feature/fix migration versions.53x

---

Products/ZenModel/IpInterface.py
Products/ZenReports/tests/testInterfacePlugin.py

ports from https://github.com/zenoss/zenoss-prodbin/pull/2559 and https://github.com/zenoss/zenoss-prodbin/pull/2567
[Jira](https://jira.zenoss.com/browse/ZEN-28105)

ZEN-28105 Do not monitor interface if admin status is down

---

Products/ZenModel/migrate/addSolrService.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.1.5-addSolrService.json
Products/ZenUI3/browser/resources/js/zenoss/manufacturers/ManufacturersConsole.js
bin/remove_CatalogServiceZenPack.sh

https://jira.zenoss.com/browse/ZEN-28341
`find /opt/zenoss/.ZenPacks/ -name ZenPacks.zenoss.CatalogService*` caused the issue in ZEN-28341, as a system could have multiple versions of CatalogService ZenPack, but during investigation, I discovered a few more problems with the migration and fixed those up.

Cleanup catalogservice removal

---

Products/ZenUI3/browser/resources/js/zenoss/form/ComponentGraphPanel.js

Yellow flare issued after checking "all on same graph" checkbox on components graph panel when device contains no components.   Now checks for valid component ID before trying to update graph.

ZEN-22112 All on same graph check issues flare

---

Products/Zuul/facades/devicefacade.py
Products/Zuul/routers/device.py

This now will stop attempts to add the same RMMonitor twice, but still lets most device classes use manageIp the way they used to.

Don't allow attempts to add the same RMMonitor device twice.

---

Products/ZenModel/MibModule.py
Products/ZenRelations/ImportRM.py
Products/Zuul/routers/mibs.py

Also improved error handling when resolving MIB catalog brains into ZODB objects.
Fixes ZEN-28477.

Don't delete MIB OIDs on ZenPack install.

---

Products/ZenUtils/Redactor.py
Products/ZenUtils/extdirect/router.py
Products/ZenUtils/tests/test_redactor.py

fixes ZEN-28293.
Added redactor routine, which traverses class and replaces values of any dictionary entry whose key matches the passed-in value. Invoked this on object being logged from router.py.
```
(zenoss) [zenoss@7376edd42c15 ~]$ runtests -t unit -n TestRedactor Products.ZenUtils
==============================
Packages to be tested:
Products.ZenUtils
==============================
Parsing /opt/zenoss/etc/zope.conf
Running tests at level 1
Running zope.testrunner.layer.UnitTests tests:
Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
Running:
.........
Ran 9 tests with 0 failures and 0 errors in 0.001 seconds.
Tearing down left over layers:
Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
(zenoss) [zenoss@7376edd42c15 ~]$ 
```

ZEN-28293: add code to redact method, invoke from router

---

makefile

The tip of support/5.3.x should be versioned as 5.3.2 now that we're in the process of releasing a hotfix for ZEN-28477 as 5.3.1

Bump version to 5.3.2

---

Products/ZenModel/migrate/addSolrService.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.1.5_badSolrEP.json

resolves issue that caused ZEN-27842 to be re-opened.
See also https://jira.zenoss.com/browse/IMP-243

Remove zodb_zencatalogservice endpoint imports

---

Products/ZenModel/migrate/data/nginx_error-6.0.0.conf

This simple change just adds two comment lines to further clarify the log filter test cases per a request. https://jira.zenoss.com/browse/CC-3874

Added in comments to show examples of the last two grok patterns

---

Products/Zuul/facades/devicefacade.py

[Jira](https://jira.zenoss.com/browse/ZEN-28551)
Add checker to prevent TypeError in case link from grid of some component redirects user to different device instead of some component

ZEN-28551 Correct error handling in case target component was not found

---

bin/metrics/rabbitstats.py

Allow more rabbitqueues to collect data in opentsdb.

Remove the 'zenoss' queuename filter

---

Products/ZenUI3/browser/resources/js/zenoss/EvConsole.js

Create an inactivity timer to reload the console to avoid unbounded memory usage.
Not a "surgical" memory leak fix, but after looking at heap dumps and allocation profiles, it's unclear where the leakage is coming from. There are detached DOM nodes present, but hard to say where those are getting referenced. Observing and calling destroy() on the grid and reloading hourly kept memory usage level over a weekend.

Create an inactivity timer to reload the console to avoid unbounded

---

Products/ZenUtils/ZenDaemon.py

This is a change to fix the memory leak / holding of twisted when the logger for twisted is never initialized.  https://jira.zenoss.com/browse/ZEN-28629

Added in code to set the logging for twisted to none

---

Products/ZenUI3/browser/resources/js/zenoss/date.js
Products/ZenUI3/browser/resources/js/zenoss/form/CustomPropertyPanel.js
Products/ZenUI3/browser/resources/js/zenoss/tests/date_spec.js
Products/ZenUI3/browser/resources/js/zenoss/tests/renderers_spec.js
Products/Zuul/routers/properties.py
Products/Zuul/routers/zep.py

Fixes ZEN-27345.
Also adds the Zenoss.form.field.DateTime and Zenoss.date.Moment
classes for handling datetimes and timezones.

Custom Date properties can edit times again.

---

Products/ZenUtils/zencatalog.py

Terminate property of ReindexProcess, and the arg name to model_catalog_init.run() was renamed to terminator.
See https://github.com/zenoss/zenoss-prodbin/pull/2735

model_catalog_init arg name change

---

Products/ZenUI3/browser/resources/js/zenoss/EvConsole.js

Add inactivity timer to reload the console and avoid unbounded memory usage.

Add inactivity timer to reload the console and avoid memory growth.

---

Products/ZenUtils/patches/pasmonkey.py

https://jira.zenoss.com/browse/ZEN-28610
port https://github.com/zenoss/zenoss-prodbin/pull/2720

ZEN-28610 Removing audit logs from '/authorization/login' path

---

Products/Zuul/catalog/model_catalog_tool.py

If you search on with the help of regex it was not working
and if there was an escape character it was causing
a ModelCatalogError flare message.
Make regex compatible with re.compile function.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-28699)
related PR https://github.com/zenoss/modelindex/pull/72

ZEN-28699: regex work again without any escaping

---

Products/Zuul/facades/devicefacade.py

When you reorder templates in a 'Bind Templates' window
an order of selected wasn't shown after you reopen a window.
Sort templates according to zDeviceTemplates property.
[DEMO&JIRA](https://jira.zenoss.com/browse/ZEN-7184)

ZEN-7184: sort templates in a right order

---

Products/Zuul/facades/devicefacade.py

When you reorder templates in a 'Bind Templates' window
an order of selected wasn't shown after you reopen a window.
Sort templates according to zDeviceTemplates property.
this is cherry-picking from https://github.com/zenoss/zenoss-prodbin/pull/2776
[JIRA](https://jira.zenoss.com/browse/ZEN-28765)

ZEN-28765: sort templates in a right order

---

Products/ZenModel/RRDDataPointAlias.py
Products/ZenModel/tests/testRRDDataPointAlias.py
Products/ZenUI3/browser/resources/js/zenoss/form/alias.js

These changes have the application enforce the restrictions that have been followed by convention.
The most common violation of the restriction, leading and trailing whitespace in ID of the alias, is handled automatically.  If the alias ID is valid after trimming whitespace from the ends, then the alias is saved using the trimmed value.
Fixes ZEN-28817 and ANA-304.

Add alias ID naming restrictions.

---

Products/ZenEvents/MailProcessor.py

The current logic fails on 'From: "FoglightNMS.au@oup.com" <FoglightNMS.au@oup.com>'

ZEN-28693: Revise hostname parsing logic from email addresses

---

Products/ZenModel/RRDDataPointAlias.py
Products/ZenModel/tests/testRRDDataPointAlias.py

For the moment, invalid alias names are logged rather than raising an exception. This will allow existing ZenPacks to successfully install.
Fixes ZEN-28830.

Log invalid alias names.

---

Products/ZenModel/RRDDataPointAlias.py
Products/ZenModel/tests/testRRDDataPointAlias.py
Products/ZenUI3/browser/resources/js/zenoss/form/alias.js

This change checks that a datapoint alias ID contains no spaces and does not exceed 30 characters in length.  This should reduce the number of 'invalid alias' log messages when a ZenPack is installed.
The previous requirements were too strict and did not reflect the range of alias IDs that Analytics can support.
Fixes ZEN-28817.

Verify minimum requirements for alias IDs.

---

Products/ZenModel/Device.py

https://jira.zenoss.com/browse/ZEN-28849
For upgraded devices that have never had a production state set on them, give them a default production state attribute.

Set a default production state for devices

---

Products/ZenMessaging/ChangeEvents/subscribers.py
Products/ZenModel/ManagedEntity.py
Products/Zuul/catalog/events.py

The impact event listener can check this flag and know it should do a lighter weight productionState change rather than a full graph update for each device in the maintenance window.

Indicate whether a change event was triggered from a maintenance window.

---

Products/Zuul/catalog/tests/testModelCatalog.py

As part of the fix for ZEN-28850, modelindex now strips out characters that can't be utf-8 encoded.  This updates a test to account for that.
See https://github.com/zenoss/modelindex/pull/75

Fix test to match modelindex's new behavior

---

Products/ZenEvents/zenactiond.py

No maintenance window default value is currently set which causes zenactiond to try to update all devices in a maintenance window in a single transaction. For customers with large numbers of devices in main windows, the transaction often fails with timeouts or conflict errors.
This was not an issue when we moved production state to btree storage in late 2016, which is why batching was disabled, but in Thebe, production state moved back to the solr index, so we need to go back to batching by default.

Set a default batch size for maintenance windows.

---

Products/Zuul/facades/devicefacade.py

On 'Overridden Objects' page when you select password
type property from a drop-down list its value will
be shown as a plain text.
Mask the password type properties with asterisk.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-28797)

ZEN-28797: mask password type properties.

---

Products/ZenMessaging/queuemessaging/publisher.py

https://jira.zenoss.com/browse/ZEN-28918
If the arguments used to create the queue are different from the arguments zenoss-protocols is trying to create it as, the create will fail and we can't connect to the queue.  If the queue exists, use the queue as-is without trying to create it.

Check if the queue exists before creating it

---

Products/ZenModel/ComponentGroup.py
Products/ZenModel/Device.py
Products/ZenModel/MaintenanceWindow.py
Products/ZenModel/ManagedEntity.py
Products/ZenModel/tests/testDeviceClass.py

MW wasn't working for Component Group.
Some of the objects n the component group may not
have production state attribute, skip them.
When creating device config for cllector daemon
filter components by their production state in the
same way as devices are.

ZEN-28116: filter components by their production state for config

---

bin/upgrade_reindex.sh

https://jira.zenoss.com/browse/ZEN-29061
Called from the upgrade with the top-level service name as the argument.  Checks if the major version is prior to the addition of Solr to conditionally force a catalog reindex.

Add a script to optionally force reindex during upgrades

---

bin/upgrade_reindex.sh

https://jira.zenoss.com/browse/ZEN-29075
ZVersion.py has the to-version, not the from-version.  The current_version.txt upgrade step places /var/zenoss/upgrade_from_version.txt into the DFS, so we can use this to find out what version we're upgrading from.

Use /var/zenoss/upgrade_from_version.txt

---

Products/ZenRelations/ZenPropertyManager.py

The fix for ZEN-28507 required adding a new standard zProperty:
zCommandCollectionInterval. However, the commit that added it (72aa56d)
left it out of the standard zProperty list. This prevents it from being
available for unit tests.
Refs ZPS-2559.

Add zCommandCollectionInterval by default

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Ensure numeric addition of chart component heights -- thus preventing numeric string concatination of values. 1 + 2 + 500 = 503 not "12500"

ZEN-28787 Chart is excessively tall

---

Products/ZenModel/BasicDataSource.py

zminionCommand variable was used but not assigned
SNMP setup.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-29276)

ZEN-29276: set zminionCommand in SNMP setup

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

Since there was no 'startdatetime' in grid data model
None was sent to zope.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-29027)

ZEN-29027: change key-value pair according to a new data model

---

Products/ZenCollector/scheduler.py

If the Missed Run happen we put stats of the
corresponding task into the event message.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-25765)

ZEN-25765: add stats of the task to event message

---

Products/Zuul/facades/devicefacade.py

in order to display all monitoring templates bound to a device

Fix getTemplates() in device facade

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddDeviceController.js

https://jira.zenoss.com/browse/ZEN-29026
We need to search for exact value:
```
>>> typeGrid.getStore().findRecord('value', deviceClass).get('shortdescription')
"/Server/Linux/Dell"
>>> typeGrid.getStore().findRecord('value', deviceClass, 0, false, true, true).get('shortdescription') 
"Linux Server (SNMP)"
```

ZEN-29026 Use exactMatch during finding records in store

---

Products/Zuul/facades/propertiesfacade.py

in order to display more user friendly flare message.

ZEN-29110: Catch ValueError while casting int-type zProperty

---

Products/ZenUI3/browser/resources/js/zenoss/process.js

If you move  a sequence located at the top to the very bottom
it moves back to its starting location after moving it.
This was happening since data was buffered and then restored
to the original list.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-29178)

ZEN-29178: set buffer attribute of store to false

---

Products/ZenUtils/MySqlZodbFactory.py
Products/ZenUtils/PostgresqlZodbFactory.py

https://jira.zenoss.com/browse/ZEN-27806
The new version of relstorage ignores the poll-interval option and generates a warning.  Remove this as one of the parameters when connecting.

Remove the poll-interval option when connecting to relstorage

---

Products/ZenUtils/ZenPackCmd.py

https://jira.zenoss.com/browse/ZEN-29333
Upgrade of ZPs will fail if custom ZP installed on pre-upgrade system requires higher version of some dependency than to-upgrade package contains.
https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L776

ZEN-29333 Allow to update distribution if other version already exists

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/css/zenoss.css

Crayola colors be gone! More professional color scheme for "show definition" modals and the like. This has bugged me far too long and needs to be changed.

Better syntax highlight colors

---

bin/healthchecks/memcached_session_answering

https://jira.zenoss.com/browse/ZEN-29001
Adds a new healthcheck that gets used by services importing memcached_session on port 11212.

Add new healthcheck for imported memcached_session service

---

Products/ZenUtils/ZenPackCmd.py

port https://github.com/zenoss/zenoss-prodbin/pull/2929
https://jira.zenoss.com/browse/ZEN-29337

ZEN-29337 Allow to update distribution if other version already exists

---

Products/ZenUI3/browser/resources/js/zenoss/SubselectionPanel.js
Products/ZenUI3/browser/resources/js/zenoss/devdetail.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

[Jira](https://jira.zenoss.com/browse/ZEN-29462)

ZEN-29341 Device Tree refresh moves focus away from device class panel

---

Products/ZenModel/skins/zenmodel/editGraphDefinition.pt

Remove unused/unsupported Logarithmic scale option from graph report options.
port from https://github.com/zenoss/zenoss-prodbin/pull/2894

ZEN-29241 Remove Log Scale Option

---

Products/ZenModel/skins/zenmodel/editGraphPoint.pt

Removes unused limit input field from datapoint customization panel.
port https://github.com/zenoss/zenoss-prodbin/pull/2904

ZEN-29237 Multigraph Datapoint Limit

---

bin/remove_CatalogServiceZenPack.sh

During the upgrade if a traceback occurs at a certain time
the Catalog Service fails to remove, but the upgrade proceeds.
When CatalogService fails to remove while upgrade process,
fail the whole process and give a message to a user to
manually remove CatalogService zenpack before the upgrade.

ZEN-29451: fail the upgrade when CatalogService zenpack was not removed

---

Products/ZenUtils/zenpack.py

ZEN-29494: RM upgrade fails on dependencies for zenpacks that don't start ZenPacks.zenoss

---

Products/ZenEvents/tests/test_zentrap.py
Products/ZenEvents/zentrap.py

When a series of trap variables are detected, a 'sequence' event detail is added to show the order of the sequence.  E.g., given the following SNMP trap varbinds:
```
someVar.0  Data0
someVar.1  Data1
```
the following details are added to the event:
```
someVar.0  Data0
someVar.1  Data1
someVar.sequence  0,1
```
Fixes ZEN-29016.

Improve SNMP varbind capture.

---

Products/Zuul/catalog/events.py

ZEN-29511 Windows ZP error during the upgrade from 5.2.6 to 6.1.1 backport https://github.com/zenoss/zenoss-prodbin/pull/2973

ZEN-29511 Windows ZP error during the upgrade from 5.2.6 to 6.1.1

---

Products/ZenUtils/zenpack.py

After upgrade, some of the dev zenpacks was left in a broken state.
The problem was in version naming of the zenpack egg and version
naming from ZODB. At the time of upgrade, those two versions were
formatted differently and Zenpack was not able to restore, so it was
skipped and left in a broken state.
[JIRA](https://jira.zenoss.com/browse/ZEN-29362)

ZEN-29362: formatting version from egg and ZODB before restore

---

Products/ZenUtils/zenpack.py

this is port from https://github.com/zenoss/zenoss-prodbin/pull/2978
[JIRA](https://jira.zenoss.com/browse/ZEN-29466)

ZEN-29466: formatting version from egg and ZODB before restore

---

bin/fix_MultiRealmIPZenPack.sh

```
...
...
INFO:zen.ZenPackCmd:Successfully restored zenpacks!
/opt/zenoss/Products/ZenUtils/MySqlZodbFactory.py:172: UserWarning: poll_interval is ignored
storage = relstorage.storage.RelStorage(adapter, **relstoreParams)
INFO:zen.migrate:Installing AddLagAndZEPEventClasses (200.1.1)
2018-02-16 12:52:58 INFO zen.migrate: Installing AddLagAndZEPEventClasses (200.1.1)
INFO:zen.migrate:Installing AddMemcachedForSessions (200.1.1)
2018-02-16 12:52:58 INFO zen.migrate: Installing AddMemcachedForSessions (200.1.1)
INFO:zen.migrate:Found 1 services named 'memcached'.
2018-02-16 12:52:58 INFO zen.migrate: Found 1 services named 'memcached'.
2018-02-16 12:52:58 INFO zen.migrate: Loading Reports
INFO:zen.migrate:Loading Reports
2018-02-16 12:53:00 INFO zen.migrate: Committing changes
2018-02-16 …
```

ZEN-29562: Cannot upgrade MultiRealmIP Zenpack from 2.2.2 to 2.2.3

---

bin/fix_MultiRealmIPZenPack.sh

port: https://github.com/zenoss/zenoss-prodbin/pull/2997

ZEN-29548: Cannot upgrade MultiRealmIP Zenpack from 2.2.2 to 2.2.3

---

Products/ZenHub/metricpublisher/publisher.py

https://jira.zenoss.com/browse/ZEN-29575
port https://github.com/zenoss/zenoss-prodbin/pull/3050

ZEN-29575 Set max size for metrics to default value

---

Products/ZenUtils/Exceptions.py
Products/ZenUtils/tests/testExceptions.py

ZEN-26277: zenmodeler: TypeError: __init__() takes exactly 4 arguments (3 given)
ZEN-29059: Modelling can fail with cryptic traceback

ZEN-26277: Error decoding twisted.python.failure exceptions

---

Products/ZenUtils/Exceptions.py
Products/ZenUtils/tests/testExceptions.py

Fixes ZEN-29810, ZEN-26277, ZEN-29059
* RED: add test for twisted.spread.pb.RemoteError
* REFACTOR: test using actual Twisted Failure object
* GREEN: add handler for twisted.spread.pb.RemoteError
* REFACTOR: cleanup unittests
* REFACTOR: Remove special decoding of type strings
* if resolveException fails, wrap the failure object in a
ZenResolveExceptionError and return that.
* A twisted python failure should never have its type attribute set as a
string, it will cause an error if you try to construct one that way.

ZEN-29810: Error decoding twisted.python.failure exceptions (#3064)

---

Products/ZenCallHome/ZenossAppData.py

The problem is when a vSphere endpoint is decommissioned there's no action to crawl the linked guest relationships and unlink them which causes this to append these to the list of linked guests. To get around this just becomes a quick lookup against the parent device of the link (which is the vSphere endpoint) and consider its production state, preventing previously linked guests who's vSphere endpoint have been set to decommissioned (or lower, in the case of custom prod states) from being counted in the MR calculation

Fixes ZEN-29607

---

Products/Zuul/utils.py

https://jira.zenoss.com/browse/ZEN-29785
If a context begins with the virtual root, strip it off in resolve_context().
The less invasive way to fix events would be to apply this to all uids near https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/Zuul/routers/zep.py#L550

Strip out the virtual root in resolve_context

---

Products/ZenUtils/CSEUtils.py

Don't include the port in the callback url to Auth0 unless the port is something other than 443 (dev environments).

Fix the callback url to not include :443 when using the std port

---

Products/ZenUI3/browser/templates/base-new.pt

https://jira.zenoss.com/browse/ZEN-30079
Clicking the Zenoss Logo redirects to /, which is Zenoss cloud for a CSE.  The "Zenoss Cloud" link is now redundant and should be removed.

Clicking the Zenoss Logo redirects to the base

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

The component group details offers to display a list of devices.
Use regex to exclude device menu option from component group
details.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30092?focusedCommentId=129288&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-129288)

ZEN-30092: exclude device list from component group details

---

Products/ZenUtils/Auth0/Auth0.py

https://jira.zenoss.com/browse/ZEN-30235
If the session jwt expiration has expired, clear the session data to prevent a CZ->ZC loop.

Clear the auth0 session when the jwt has expired

---

Products/ZenUI3/browser/resources/js/zenoss/form/LinkField.js

This line causes the issue:
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenUI3/browser/resources/js/zenoss/Renderers.js#L291
url comes here as:
```
<a href="/zport/dmd/Devices/vSphere/devices/qa-vcenter1.zenoss.loc/vms/VirtualMachine_vm-65">Virtual Machine 'testrail' on qa-vcenter1.zenoss.loc</a>
```
When line 291 is executed url becomes:
```
/cz1/<a href="/zport/dmd/Devices/vSphere/devices/qa-vcenter1.zenoss.loc/vms/VirtualMachine_vm-65">Virtual Machine 'testrail' on qa-vcenter1.zenoss.loc</a>
```
To fix the issue we need to pass into line 281 `link` and `name`:
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenUI3/browser/resources/js/zenoss/form/LinkField.js#L40
https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenUI3/browser/resources/js/ …

ZEN-30108: When clicking the link from a Server to it's VM

---

Products/ZenUI3/browser/resources/css/zen-cse.css

The problem was that the [swfobject.js](https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenUI3/browser/resources/js/swfobject/2.2/swfobject.js) library [has functionality](https://github.com/swfobject/swfobject/blob/9e0104326a8913918f2170f15a69d60624c4bf68/swfobject/src/swfobject.js#L193) that creates empty Flash Player in order to detect its version for non-Internet Explorer browsers.

ZEN-30304: Hide the flickering Adobe Flash box when loading pages

---

Products/Jobber/facade.py
Products/ZenModel/DeviceClass.py
Products/Zuul/facades/devicefacade.py

Add the `is_dev_moved variable` in the `_moveDevice` method of `DeviceClass`.
Set the `is_dev_moved` as True at the end of the method because if there are no exceptions above this line of code the device changes its class. So we return the success result regardless of the device was exported or only moved to another class.
Rename `exports` variable to the `moved_dev_amount` on the `devicefacade.py`
Fix undefined log variable in the `facade.py`
Add the appropriate result structure of the `_moveDevices` method of `DeviceFacade`.

ZEN-29542: global name 'log' is not defined

---

Products/ZenUI3/browser/resources/css/zen-cse.css

In original PR - zenoss/zenoss-prodbin#3185 for light theme was used a color that made the `text` and `path` almost invisible.

ZEN-30098: Fix usage of colors

---

bin/metrics/mysqlmetrics.sh
bin/metrics/storagestats.py

Fixes ZEN-30198 by executing model and events databases sql via the ZenDB class, which automatically fetches creds from global.conf.

ZEN-30198 - RM Monitor Fails if Database Credentials are Changed

---

Products/ZenModel/tests/test_zenmib.py
Products/ZenModel/zenmib.py
Products/ZenUtils/mib/module.py
Products/ZenUtils/mib/smidump.py

Three changes in three separate commits:
1. Actually commit the changes unless `--nocommit` is specified
2. Add the directory of the specified MIB file as a MIB file search path
3. Log results of adding/updating MIBs in ZODB.
Fixes ZEN-30019.

Finish fixing zemib.

---

Products/ZenModel/tests/test_zenmib.py
Products/ZenModel/zenmib.py
Products/ZenUtils/mib/module.py
Products/ZenUtils/mib/smidump.py

Three changes in three separate commits:
1. Actually commit the changes unless `--nocommit` is specified
2. Add the directory of the specified MIB file as a MIB file search path
3. Log results of adding/updating MIBs in ZODB.
Fixes ZEN-30170.

ZEN-30170 Finish fixing zemib.

---

Products/ZenHub/interceptors.py
Products/ZenHub/tests/test_interceptors.py
Products/ZenHub/zenhub.py

Fixes: ZEN-30227
- skip the extra steps of pickling sendEvent(s) messages and forwarding them to the zenhub workers, they just get unpickled and forwarded to the rawEvents queue.
- additional fine-tuning to speed up the remoteMessageRecieved method
- break WorkerInterceptor into testable components
- convert remoteMessageRecieved to an inlineCallback
- improve performance
- Create Unittests for WorkerInterceptor

ZEN-30227: ZenHub: Send Events directly to the rawEvents queue

---

Products/ZenUI3/browser/resources/css/zen-cse.css

Set orange color to edited codeminor header for light theme.
Remove transparent background from codeminor lines and gutter to hide overlapping text on scroll.

ZEN-30135 - style changes for codeminor field for light/dark themes

---

Products/ZenUI3/browser/resources/js/zenoss/dialog/LockForm.js

1. After deselection of `Lock from updates` deselect `Lock from deletion`
2. Make `Send an event when an action is blocked` disabled by default since it can be selected only if `Lock from updates` or `Lock from deletion` is selected

ZEN-30074: Fix the working principle of the checkboxes in Locking

---

Products/Zuul/routers/device.py

Do not log the trace when handling exception but log the
exception message and log a traceback only in debug mode.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-29469?focusedCommentId=132013&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-132013)

ZEN-29469: move ip to new realm on device collector change

---

Products/ZenossStartup/configure.zcml
Products/ZenossStartup/meta.zcml
Products/ZenossStartup/metaglobal.py
makefile

This is to enable injection of zcml meta:provides feature strings directly from variables defined in global.conf file..

Adding zcml features

---

Products/ZenModel/migrate/addAuth0.py
Products/ZenModel/migrate/addDeviceIpAddrRelation.py
Products/ZenModel/migrate/addIndexesForDevice.py
Products/ZenModel/migrate/addLagAndZEPEventClasses.py
Products/ZenModel/migrate/addMemcachedForSessions.py
Products/ZenModel/migrate/addOpentsdbHbaseConnectionHealthCheck.py
Products/ZenModel/migrate/addZenossPublicEndpoint.py
Products/ZenModel/migrate/addZproxyNginxImpactConfig.py
Products/ZenModel/migrate/addzCommandCollectionInterval.py
Products/ZenModel/migrate/deleteRateOptionsForServices.py
Products/ZenModel/migrate/fixRabbitmqHealthCheck.py
Products/ZenModel/migrate/limitRabbitMQInstances.py
Products/ZenModel/migrate/rate_cutoff.py
Products/ZenModel/migrate/updateRateOptionsForMetricShipper.py

This PR is the result of running `make replace-zmigrateversion` per the instructions in  Products/ZenModel/migrate/README.md.
The intent is to immediately follow-up this PR by releasing `develop` to `master` as the 7.0.1 release

Update SCHEMA versions for zenmigrate prior to release

---

Products/ZenModel/skins/zenmodel/templates.pt

We had a such problem since when we were trying to delete a user command the [submit_form](https://github.com/zenoss/zenoss-prodbin/blob/cb746c707e5e59bf510d656339011cb55ba2efda/Products/ZenWidgets/skins/zenui/javascript/zenoss-utils.js#L1050) method that has in his body reference to `Zenoss.render.link` was called. Because of the fact, that iframe did not have Zenoss variable an error appeared.

ZEN-30552: If a page is rendered inside iframe then use Zenoss variable from parent

---

Products/ZenModel/Device.py
Products/ZenModel/PerformanceConf.py
Products/ZenUI3/browser/command.py
Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/resources/js/zenoss/CommandWindow.js
Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

This PR replaces the 'Model Device' button in the device overview UI with a menu with 2 option buttons. 
1. - Model the current device as before.
2. - Model the current device with debug logging enabled.
The command window widget has been enhanced to add a 'Copy to clipboard' button to allow end users to paste the output of the modeling run into the save location of their choice. This new button appears in all places where 'command windows' are used.
Tested locally in Chrome/FF.

ZEN-29895: add debug option to 'Model Device' UI with 'download'

---

Products/ZenCollector/daemon.py
Products/ZenHub/PBDaemon.py

Reduces noise in daemon logs when doing a 'zenpython/zencommand run' while testing. Fixes ZEN-30701.

ZEN-30701: Disable internal metrics for non-cycle (manual run) daemon operations

---

Products/ZenUI3/browser/resources/css/zen-cse.css

The default `stroke` for axes in `Ext.chart.theme.Base` is `#444`, so we have to apply overriding only in this case to let other `path`s have custom colors.
[Jira & Demo](https://jira.zenoss.com/browse/ZEN-30498?focusedCommentId=136504&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-136504)

ZEN-30498: Prevent overriding of custom graphs colors

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js

Prevent error that appears when we try to update `Ext.state.Manager` when there is no reason to do it since from url we got filters params for events, not a state.
[Jira & Demo](https://jira.zenoss.com/browse/ZEN-30779?focusedCommentId=136576&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-136576)

ZEN-30779: Prevent hanging of events console

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

encode only title, we need html from default_uid_renderer.

ZEN-30809 - Link for Resource is broken in event details

---

Products/ZenUI3/browser/resources/js/zenoss/CommandWindow.js
Products/ZenUI3/browser/resources/js/zenoss/ExtOverrides.js

The approach with `setTimeout` is the workaround that fixes the issue on Chrome.

ZEN-30823: Fix issue with copying large modeling output

---

Products/ZenUtils/patches/mysqladaptermonkey.py

Since we moved to a new version of the realstorage 2.x and the
structure of realstorage library was changed, monkeypatching was
failing on because of the bad path to the package and some tables
in zodb were empty.
Use the correct path to package.
[JIRA](https://jira.zenoss.com/browse/ZEN-30848)

ZEN-30848: fix the path for objects that need to be patched

---

Products/ZenEvents/MailProcessor.py
Products/ZenEvents/tests/testMailProcessor.py

Change From address parsing in MailProcessor

ZEN-29654 Reopened- zenmail fails to parse hostname from an email address (the patch for this broke zenmail)

---

Products/Zuul/facades/processfacade.py

When we have the remote collector getProcessList should be
run on that collector, but it is not.
Logical operator that is used to set the modeler collector
is not right. We should use remote modeling in the case
when the collector is not equal to localhost and do not care
about the path to zenmodelerPath.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30469?focusedCommentId=138141&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-138141)

ZEN-30469: The test regex window is not fetching process list

---

Products/ZenUI3/browser/javascript.py
Products/Zuul/routers/messaging.py

There is nginx filtering rules that are adding /cz# prefix
to all the html that is passed to UI and this is breaking
things that do not require /cz# prefix.
To fetch the browser state we are now making an api call.
[JIRA&DEMO
](https://jira.zenoss.com/browse/ZEN-30880?focusedCommentId=138066&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-138066)

ZEN-30880: make a request to server to get Browser state

---

Products/Zuul/infos/report.py

The addition of cz prefix on the backend side caused some side effects in [`getNodePathById` method](https://github.com/zenoss/zenoss-prodbin/blob/24072cf22f2f09635dd70e9d5392baa24c68ad04/Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js#L577) of `HierarchyTreePanel` component. The node path that function began to return is not a valid node path so after reloading application is not able to select a node that was selected before reloading.
By [PR #3152](https://github.com/zenoss/zenoss-prodbin/pull/3152) was added [JS code that ensures](https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenUI3/browser/resources/js/zenoss/Reports.js#L278) that `uid` that will be used on the report page is with cz prefix and this fixes the problem.

ZEN-30907: Fix node selecting after reload in the tree

---

Products/Jobber/facade.py
Products/ZenModel/DeviceClass.py
Products/Zuul/facades/devicefacade.py

Backport PR for https://github.com/zenoss/zenoss-prodbin/pull/3228
Add the `is_dev_moved variable` in the `_moveDevice` method of `DeviceClass`.
Set the `is_dev_moved` as True at the end of the method because if there are no exceptions above this line of code the device change its class. So we return the success result regardless of the device was exported or only moved to another class.
Rename `exports` variable to the `moved_dev_amount` on the `devicefacade.py`
Fix undefined log variable in the `facade.py`
Add the appropriate result structure of the `_moveDevices` method of `DeviceFacade`.

ZEN-29433: global name 'log' is not defined

---

Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js

A while ago rules for datasource name was added, that rule
was disabling a form if we have any special character in the
name except underscores and dashes since datasource name is
part of the metric name in OpenTSDB that was breaking graphs.
According to OpenTSDB documentation, dots are also acceptable in
metric names.
Since datasource name is used as a part for metric name in OpenTSDB I added periods to one of the allowed characters in datasource name according to OpenTSDB docs.
http://opentsdb.net/docs/build/html/user_guide/writing.html
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30743?focusedCommentId=138653&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-138653)

ZEN-30743: allow dot in the datasource and datapoint name

---

Products/Zuul/facades/__init__.py

Fixes ZEN-30966, backport of ZEN-30949: Fixes a condition where a 'priority' filter was not being converted from a list, resulting in an expected object type making it into the solr model index search.

Fixes ZEN-30966

---

Products/ZenMessaging/queuemessaging/publisher.py

Added the Metrology timers to check the execution of commit hooks.

ZEN-30929: Add "Model Change Handler time" measurement to RM ZenPack

---

Products/ZenWidgets/ZenTableState.py

When a user uses page size filter on the table view and sorts
the column that has int value in it will fall with a traceback.
Also, values from the sorted column are used as a page name on
pagination select element, which is not logically right, there
should be only the page numbers 1,2,3 ....
Remove that functionality since it is confusing and not logical.
We are using `_buildTextLabel`  only in this module.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30592?focusedCommentId=140258&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-140258)

ZEN-30592: remove buildTextLabel functionality

---

Products/ZenModel/ZenModelBase.py
Products/ZenUI3/browser/eventconsole/export.py
Products/ZenUtils/Time.py

(cherry picked from commit 264b8f2f149ed3a74132575fa189ad4e4870c544)
backporting fix for ZEN-28212 to CZ

ZEN-30857 Wrong time format on State at time

---

Products/ZenUI3/browser/templates/base-new.pt

The UI for Zenoss Cloud is responsible for creating the local storage object `pendoInfo` and populating it with all of the data that needs to be sent to Pendo.  Note that if that storage object is not found, then RM will not try to load Pendo.
The Zing deploy code has logic that controls whether or not the Zenoss Cloud (zing and CZs) will integrate with Pendo on a project by project basis.

ZEN-31143 - Initial pendo integration

---

Products/ZenModel/Collection.py

When adding a new collection item in multigraph reports collection
specific component path had a cz# prefix, therefore, it was not found
in dmd and not added to collection.
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30626?focusedCommentId=142596&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-142596)

ZEN-30626: remove cz# prefix from component path

---

Products/ZenModel/DataRoot.py
Products/ZenModel/skins/zenmodel/editSettings.pt
Products/ZenRelations/ZenPropertyManager.py

User password for SMTP server is accessible in browser dev tool
by just selecting an input field, the input field value attribute
will show the password as clear text.
Set the value attribute of the input field to masked password under
asterisks. When the form on the UI is submited save the password
only if its new. When SMTP password field is in focus clear it
to prevent updating old password since it can cause wrong password
situation(****  will be saved like ****56)
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-31177?focusedCommentId=142300&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-142300)

ZEN-31177: send to UI asterisks instead of valid password

---

Products/ZenUtils/controlplane/application.py
Products/ZenUtils/controlplane/data.py

Get  RAMCommitment of the CC service for RM zp to model and use it.
Related PR to RM ZP: https://github.com/zenoss/ZenPacks.zenoss.RMMonitor/pull/144
[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30240?focusedCommentId=143046&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-143046)

ZEN-30240: model service RAM Commitment and add it as a threshold

---

jenkins_build.sh

Fixes ZEN-31231.
These changes work with the newer, more generic, zenoss-prodbin build job: http://platform-jenkins.zenoss.eng/job/Components/job/zenoss-prodbin/job/build-zenoss-prodbin/
The changes also ensures that the older, hard-coded, branch specific build jobs continue work unchanged.

Allow product-assembly and zenoss-prodbin to use different branches

---

Products/ZenUI3/browser/stats/stats.py
bin/metrics/zenossStatsView.py

This change adds an undocumented global configuration option 'zope-request-threshold' (defaults to 5 seconds) that allows us to bucket slow requests, and expose the number of slow requests via '/zport/zenossStatsView'.

feature/ZEN-31456: Track Slow Requests

---

Products/ZenHub/dispatchers/tests/test_workers.py
Products/ZenHub/dispatchers/workerpool.py
Products/ZenHub/dispatchers/workers.py
Products/ZenHub/interfaces.py
Products/ZenHub/servicemanager.py
Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py

A PBConnectionLost exception occurs when a zenhubworker quits before zenhub notices its absence.
Handle PBConnectionLost exceptions explicitly and improve log messages regarding worker availability.
Fixes ZEN-31503.

Handle PBConnectionLost exceptions

---

Products/ZenHub/broker.py
Products/ZenHub/servicemanager.py
Products/ZenHub/tests/test_broker.py
Products/ZenHub/tests/test_servicemanager.py
Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py

Versions of zenhub prior to the recent refactor used double serialization (jelly and pickle) to communicate with the zenhubworkers. This had the side effect of bypassing Twisted's check to ensure only registered classes could have their objects unserialized. The refactor removed the use of pickle and so the check for registration was enforced, breaking some ZenPacks. This change removes the registration requirement.
Fixes ZEN-31571.
Note: this change does not effect error handling. All that's changed is to configure Twisted's serialization protocol (named 'jelly') to be much more lenient about what it can (and can't) serialize and unserialize.
Handling serialization errors in Twisted will require additional research. Currently, Twisted performs serialization as nested functionality that …

Allow Twisted to unserialize unregistered classes.

---

Products/ZenHub/servicemanager.py
Products/ZenHub/tests/test_servicemanager.py

AuthXmlRpcService accepts just one cred checker.

---

Products/ZenUI3/browser/modelapi/configure.zcml
Products/ZenUI3/browser/modelapi/modelapi.py

Add model views for Impact to facilitate modeling by RM Monitor. This adds a model view under /zport/dmd/ImpactDaemons that returns Impact (server) and zenimpactstate Control Center information.
The ZCML doesn't load the view if Impact isn't installed.
https://jira.zenoss.com/browse/ZEN-31617

[ZEN-31617] Add Model Views for Impact to facilitate modeling by RM Monitor

---

Products/Zing/datamaps.py
Products/Zing/interfaces.py
Products/Zing/meta.zcml
Products/Zing/tests/test_datamaps.py

Added IObjectMapContextProvider subscriber adapter interface that allows
ZenPacks to provide additional fact dimensions and metadata to Zing.
Implements ZEN-31625.

Add interface for ZenPacks to add Zing entity data

---

Products/Zuul/facades/eventclassesfacade.py

Event Class Mappings cannot be re-sequenced if they contain spaces because the UID returned from the request contains the encoded %20 value.

Fixes ZEN-31081

---

bin/metrics/zenossStatsView.py

This was fixed in 6.x, but never made it into CZ.

ZEN-30783 Zope Self-Monitoring Collection Needs a Timeout

---

Products/ZenHub/dispatchers/tests/test_workerpool.py
Products/ZenHub/dispatchers/tests/test_workers.py
Products/ZenHub/dispatchers/workerpool.py
Products/ZenHub/dispatchers/workers.py

Exceptions raised from remote calls are no longer converted into a single exception type.  Removed testing for whether a zenhubworker reference is 'current'.
Fixes ZEN-31694.

Don't homogenize service call exceptions.

---

Products/ZenUI3/browser/modelapi/configure.zcml
Products/ZenUI3/browser/modelapi/modelapi.py

ZEN-31725 Add Memcached model views
https://zenoss.example/zport/dmd/Memcached
Example output:
```
{"memcacheds": [{"lastModeledState": "running", "RAMCommitment": 3221225472, "instanceCount": 1, "controlplaneServiceId": "f3h13yisx3opawmmsk68a4rsh", "title": "memcached", "id": "memcached"}, {"lastModeledState": "running", "RAMCommitment": 1073741824, "instanceCount": 1, "controlplaneServiceId": "3wat2pb8pb92yltanfjdhg4zr", "title": "memcached-session", "id": "memcached-session"}]}
```

ZEN-31725 Add Memcached model views

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-31734: Validate objectMaps in RelationshipMaps

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py

ZEN-31748: Add handling for duplicate IDs in RelationshipMaps

---

Products/ZenTestCase/testing-noevent.zcml

Something in the ApplyDataMap refactor has resulted in test using it to
require that the ZCML for Products.ZenMessaging.queuemessaging to be
loaded.
Without it we get unit test errors such as the following in ZenPackLib's
unit tests.
Running ZenPacks.zenoss.ZenPackLib.tests.test_layered_unit_tests.SharedLayer2 tests:
Set up ZenPacks.zenoss.ZenPackLib.tests.ZPLTestCaseLayerBase Traceback (most recent call last):
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 380, in run_layer
setup_layer(options, layer, setup_layers)
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 667, in setup_layer
setup_layer(options, base, setup_layers)
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 667, in setup_layer …

add ZenMessaging.queuemessaging for tests

---

Products/ZenUtils/Auth0/Auth0.py

https://jira.zenoss.com/browse/ZEN-31755
In order to better support self-monitoring for ops, add support for a globalkey flag on the jwt that allows the same API Key to be used against any tenant.  This flag is set in the signed Auth0 jwt, and is *only* set for the zaas-ops@zenoss.io/zenoss-com account token.
An example of this code working against two different tenants (with the flag set):
```
$ curl https://qa-long.zenoss.io/cz0/zport/dmd/detailnav_router -H 'content-type: application/json' -H 'accept: */*' --data-binary '[{"action":"DetailNavRouter","method":"getContextMenus","data":[{"uid":"/cz0/zport/dmd/Devices","menuIds":["More","Manage","Edit","Actions","Add","TopLevel"]}],"type":"rpc","tid":8},{"action":"DetailNavRouter","method":"getSecurityPermissions","data":[{"uid":"/cz0/zport …
```

Add support for the globalkey auth0 flag

---

Products/ZenTestCase/testing-noevent.zcml

Something in the ApplyDataMap refactor has resulted in test using it to
require that the ZCML for Products.ZenMessaging.queuemessaging to be
loaded.
Without it we get unit test errors such as the following in ZenPackLib's
unit tests.
Running ZenPacks.zenoss.ZenPackLib.tests.test_layered_unit_tests.SharedLayer2 tests:
Set up ZenPacks.zenoss.ZenPackLib.tests.ZPLTestCaseLayerBase Traceback (most recent call last):
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 380, in run_layer
setup_layer(options, layer, setup_layers)
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 667, in setup_layer
setup_layer(options, base, setup_layers)
File "/opt/zenoss/lib/python2.7/site-packages/zope/testrunner/runner.py", line 667, in setup_layer …

ZEN-31762: add ZenMessaging.queuemessaging for tests

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

Seems like we already encode HTML tags in the `device` field using Ext.htmlEncode method, but we need to always show links and have it clickable so, I just removed that method

Resource in Event Console Detail window is displaying the HTML

---

Products/ZenHub/PBDaemon.py

This change will allow RemoteException objects to be sent to the client without being written to zenhub's log.
Fixes ZEN-31786.

Make RemoteException a subclass of pb.Error.

---

Products/ZenHub/server/configure.zcml
Products/ZenHub/server/metrics.py
Products/ZenHub/server/tests/test_metrics.py

* Restored the legacy zenhub worklists to Metrology gauge types
* Re-added the dropped zenhub eventsSent Metrology meter.
Fixes ZEN-31968.

Reverted legacy metric configuration.

---

Products/ZenModel/IpNetwork.py

Fixes ZEN-32287.
Adapted from https://github.com/zenoss/zenoss-prodbin/pull/3438.

Drop network releationship on deleted devices.

---

Products/ZenHub/server/config.py
Products/ZenHub/server/executors/event.py
Products/ZenHub/server/executors/tests/test_event.py
Products/ZenHub/server/executors/tests/test_workers.py
Products/ZenHub/server/executors/workers.py
Products/ZenHub/server/main.py
Products/ZenHub/server/tests/test_main.py
Products/ZenHub/server/tests/test_priority.py
Products/ZenModel/migrate/tests/common.py
Products/ZenModel/migrate/tests/test_common.py

This PR contains three changes
1. Add a new **CONFIG** priority, set it lower than the existing **OTHER** priority, and assign the `getDeviceConfigs` and `getDeviceConfig` service calls to the **CONFIG** priority.  This will give other service calls to execute without getting having to wait for all the `getDeviceConfigs` calls to complete.  Fixes ZEN-32342.
2. Factory methods have been added to ZenHub service call executors to simplify ZenHub configuration.  With this change, adding new pools and executors will require changing only the `config.py` module.
3. Modified the service migration test to dump all differences between the actual and expected service definitions.  With this change, it is no longer necessary to run the test multiple times to find all the differences.

Give device config calls a lower priority.

---

Products/ZenModel/migrate/editServicesStartUp.py
Products/ZenModel/migrate/tests/zenoss-cse-7.0.3-editServicesStartUp.json

* Add stopwaitsecs to the correct section of the supervisord config file
* Make the migration more resilient to missing data
Fixes ZEN-32453.

Fix editServicesStartUp migration.

---

Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js

autoScroll was added to XformMasterPanel to fix ZEN-31741, but then
appears to have be accidentally reverted when the fix for ZEN-30800 was
cherry-picked to fix ZEN-32012.
This change fixes that accident.

ZEN-32520: Restore autoscrolling for transforms

---

Products/ZenModel/migrate/tests/common.py
Products/ZenModel/migrate/tests/test_common.py

Fixes ZEN-32417 (Improve ZenHub Config Retrieval Performance). The part of changes already was backported in the scope of ZEN-32572. This is backporting of remaining commit.

ZEN-32417. Backported "Show all diffs on service migration test failures"

---

Products/ZenModel/PerformanceConf.py

If your device id has spaces, you can't model from the UI.
The action appears to only use the characters up to the
first space when modeling.
Fixes ZEN-32560

ZEN-32560: (backport) Fix model in UI if device id has spaces

---

Products/ZenHub/server/avatar.py
Products/ZenHub/server/tests/test_avatar.py
Products/ZenHub/server/tests/test_workerpool.py
Products/ZenHub/server/workerpool.py

Also simplify workerpool's logic to rely on just the worker reference's sessionId value.
Fixes ZEN-32601.

Handle DeadReferenceError from zenhubworker.

---

Products/ZenModel/MaintenanceWindow.py
Products/Zuul/facades/devicemanagementfacade.py
Products/Zuul/routers/devicemanagement.py

Add audit logging to the devicemanagement router. Most complaints were around the lack of audit logging for Maintenance Window actions, however we were missing audit logging for User Command and Role assignments as well, this adds logging for all of those actions.

Fixes ZEN-30428

---

bin/metrics/storagestats.py

Related to https://github.com/zenoss/ZenPacks.zenoss.RMMonitor/pull/181

ZEN-31546 Change name of metrics in storagestats.py

---

Products/Zing/datamaps.py
Products/Zing/fact.py
Products/Zing/tests/test_datamaps.py

https://jira.zenoss.com/browse/ZING-8700
In order to properly type devices and device components, we're adding a new metadata field to the ZING entities for devices and device components.  This tag will be used to add additional schemas to the entities in model-id.

Add the zen_schema_tags metadata to the ZING data maps

---

bin/metrics/storagestats.py

Related to https://github.com/zenoss/ZenPacks.zenoss.RMMonitor/pull/183

ZEN-32649 Change name of metrics in storagestats.py

---

Products/ZenEvents/zentrap.py

Debug messages aren't displayed because by default debug mode is disabled and pynetsnmp don't write debug logs. When we use 'zentrap debug', it actually changes log level, but doesn't enable debug mode in net-snmp (C-library). This commits enables debug mode in net-snmp always (but log messages are displayed only when debug level for logging is enabled)

ZEN-32752 Debug messages from pynetsnmp aren't displayed when switch on debug-mode using 'zentrap debug'

---

Products/ZenModel/actions.py

This fixes ZEN-32893 where the timezone for timestamps in emails sent to manually defined email addresses in notifications was being improperly calculated (was not factoring in daylight saving when the container timezone is set to something other than UTC).

Fixes ZEN-32893

---

Products/ZenRRD/runner.py
Products/ZenRRD/zencommand.py
Products/ZenUtils/Executor.py
Products/ZenUtils/tests/test_executor.py

When a command's execution time exceeds the timeout value, the connection to the device will be closed.  The connection is closed when the collection cycle has completed.
Fixes ZEN-32226.

zencommand handles command timeouts.

---

Products/DataCollector/CollectorClient.py

Apparently, relative imports do not work in modules that are not imported using absolute import notation.
Fixes ZEN-32923.

Remove relative import statement.

---

Products/ZenModel/Device.py

Use Method Resolution Order to search the values of the sourcetype class attribute of datasource class hierarchies.  The first, most derived, suitable value is selected.
Fixes ZEN-32926.

Exhaustivly find a suitable sourcetype.

---

Products/ZenRRD/zencommand.py

* Add Clear events, when necessary, for a datasource during result processing, not during result storage.
* Use eventKey to differentiate timeout events between datasources.
* Reorganized the error reporting code
Fixes ZEN-32927.

Refactor zencommand's event management.

---

Products/Jobber/model.py
Products/Jobber/tests/test_model.py
Products/Zuul/__init__.py

* JobRecord now implements the IInfo interface.
* Zuul.marshal no longer assumes IInfo objects have a _object attribute.
- InfoBase provides the _object attribute, not IInfo.
* Added unit tests for JobRecord marshalling.
Fixes ZEN-32987.

Fix JobRecord marshalling errors.

---

Products/Jobber/config.py
Products/Jobber/jobs/job.py
Products/Jobber/log.py
Products/Jobber/model.py
Products/Jobber/monitor.py
Products/Jobber/task/abortable.py
Products/Jobber/task/base.py
Products/Jobber/task/dmd.py
Products/Jobber/task/event.py
Products/Jobber/tests/test_job.py
Products/Jobber/tests/test_manager.py
Products/Jobber/tests/test_model.py
Products/Jobber/utils/datetime.py
Products/ZenModel/migrate/addEventClassInstancesForZenJobs.py
legacy/zenoss-version/setup.py.in

* Jobs are killed when their running time exceeds a configured duration.
* Send a Zenoss event when a job times out, is aborted, or fails.
Fixes ZEN-29200.

Add support for timing out jobs in zenjobs.

---

Products/Jobber/jobs/job.py
Products/Jobber/jobs/subprocess.py
Products/Jobber/tests/test_log.py
Products/Jobber/tests/test_logformattercontext.py
Products/Jobber/tests/utils.py

The log formatter context must be called when used in a `with` statement.
Fixes ZEN-33032.

Fix log formatter context usage.

---

Products/Jobber/jobs/subprocess.py

Raising the SubprocessJobFailed exception is how the SubprocessJob task signals that the job has failed.
Fixes ZEN-33036.

Do not ignore SubprocessJobFailed exceptions.

---

Products/ZenRRD/runner.py
Products/ZenUtils/Utils.py
Products/ZenUtils/tests/test_open_browser_connection.py

* is_browser_connection_open no longer makes assumptions about the incoming request object.
* SshRunner validates the pool key before using it.
Fixes ZEN-33042.

Add more robust error handling.

---

Products/Jobber/jobs/facade.py
Products/Jobber/jobs/subprocess.py
Products/Jobber/storage.py
Products/Jobber/task/base.py
Products/Jobber/task/utils.py
Products/Jobber/tests/test_storage.py
Products/Jobber/tests/test_task_utils.py

Set a job to the FAILURE state if an ERROR log message is found in the job's log file.  Many jobs do not propagate their errors into zenjobs (celery), so zenjobs has to examine their log file to determine the jobs' final state.
Also fixed an issue with the Redis wrapper (storage) when updating a job record with nothing but None valued fields.
Fixes ZEN-33036.

Set job to FAILURE if ERROR in its log file.

---

Products/Zing/fact.py
Products/Zing/model_updates.py
Products/Zing/tx_state.py

This is being done primarily to get locations along with their address
(and geocoded latlong) to the cloud in support of the upcoming maps
tile.

ZEN-33017: send device organizers to cloud

---

Products/Jobber/jobs/facade.py
Products/Jobber/jobs/job.py
Products/Jobber/jobs/misc.py
Products/Jobber/jobs/subprocess.py

Expected exceptions are still an error and fail the job, but do not cause celery to write a traceback to the log.  For expected exceptions, tracebacks are unnecessary as they do not add any useful information.
Fixes ZEN-33054.

Specify a job's expected exceptions to Celery.

---

Products/ZenModel/ZDeviceLoader.py

Prevents zenjobs from writing a traceback to the log.
Fixes ZEN-33053.

Set DeviceExistsError as an expected exception.

---

Products/Jobber/config.py
Products/Jobber/jobs/misc.py
Products/Jobber/serialization.py
Products/Jobber/tests/test_serialization.py
Products/Jobber/zenjobs.py

The custom serializer decodes strings as str instead of unicode.
Fixes ZEN-33035, ZEN-33071, and maybe others.

Zenjobs now uses a custom task serializer.

---

Products/Jobber/manager.py
Products/Jobber/model.py
Products/Jobber/tests/test_model.py

The job_name, job_type, and job_description attributes have been added back to the JobRecord class.
Fixes ZEN-33073.

Restore legacy attributes to JobRecord class.

---

Products/Jobber/manager.py
Products/Jobber/model.py
Products/Jobber/tests/test_manager.py

Locating types of jobs is done using the 'name' field.
Fixes ZEN-33075.

Use the correct search field for job storage.

---

Products/ZenModel/DeviceOrganizer.py

The correct syntax to retrieve a job's ID is `jobid`.
Fixes ZEN-33079.

JobRecord doesn't have a getId method.

---

Products/Jobber/config.py
Products/Jobber/jobs/__init__.py
Products/Jobber/jobs/purge_logs.py
Products/Jobber/log.py
Products/Jobber/model.py
Products/Jobber/scheduler.py
Products/Jobber/tests/test_model.py

Adds a custom scheduler for the Celery's 'beat' command.
Adds a task that deletes job logs which is executed periodically by the 'beat' command.
Fixes ZEN-30586.

Implement 'celery beat' as a service.

---

Products/Jobber/config.py
Products/Jobber/task/dmd.py
Products/Jobber/task/utils.py
Products/Jobber/tests/test_task_utils.py

Use a randomized fibonacci-ish delay before retrying a transaction that failed with a ConflictError or a ReadConflictError.
Fixes ZEN-30746.

Retry with backoff delay on ConflictErrors.

---

Products/Zing/fact.py

If a fact fails to serialize, log the failure as a warning.
ZEN-33043.

Serialize each fact to check for errors.

---

Products/Jobber/manager.py

The original reason to wait for a commit before submitting was too ensure that zenjobs would see jobs saved to ZODB.  Since job data is not stored in ZODB anymore, there's no reason to wait until commit.
Fixes ZEN-33084.

Submit jobs immediately to zenjobs.

---

Products/Jobber/model.py
Products/Jobber/task/abortable.py
Products/ZenUI3/browser/resources/js/zenoss/quickstart/model/Discovery.js
Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AutoDiscoveryView.js
Products/Zuul/routers/jobs.py
Products/Zuul/routers/network.py

Also pass the job's duration so that field is updated on the Add Multiple Devices screen.
Fixes ZEN-33110.

Pass the job ID back to the browser.

---

Products/ZenEvents/tests/test_zentrap.py
Products/ZenEvents/zentrap.py

SNMP notification varbinds that occur only once in a packet are recorded into events as they were in pre 6.2.0 systems.  Varbinds that have multiple occurrences will continue to use the post 6.2.0 behavior.
Fixes ZEN-32255.

ZEN-32255 Updated varbind behavior breaks RFC conventions

---

Products/Jobber/config.py

Multiple services (Zope, etc) need access to the job-expires option so move it to the global.conf file.
Fixes ZEN-33101.

zenjobs' job-expires option should be global.

---

Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py

Fixes ZEN-33116
Add additional database sync when we get remote Service
to restore db connection.

Handle case with lost connection to MySQL

---

Products/ZenModel/Location.py
Products/ZenModel/Organizer.py
Products/ZenModel/migrate/SendOrganizersToZing.py
Products/Zuul/facades/__init__.py
Products/Zuul/facades/devicefacade.py

When initially being created locations would have their name sent to
zing-connector, then set their address. This resulted in their address
never making it to zing. Now we are setting all properties before the
fact goes to zing-connector instead.

ZEN-33017: fix sending of org details to zing

---

Products/Jobber/manager.py
Products/Jobber/model.py
Products/Jobber/task/base.py
Products/Jobber/tests/test_zentask.py

When submitting jobs via JobManager, jobs are not submitted to zenjobs until the current database transaction is committed.  JobManager's other methods for retrieving jobs should return jobs that have been submitted, but not committed yet.
Fixes ZEN-33084.

Added transaction support to JobManager.

---

Products/Jobber/model.py

When a finished job has no start time, log a message that the job was never started.
Fixes ZEN-33124.

Check for unstarted jobs when job ends.

---

Products/Jobber/manager.py
Products/Jobber/tests/test_jobdispatcher.py

JobDispatcher can now handle multiple calls to `add` without losing jobs.
Fixes ZEN-33123.

Support multiple jobs in a transaction.

---

Products/ZenModel/MaintenanceWindow.py

Example of the worst-case scenario log:
```2020-10-08 14:08:37,227 INFO zen.maintenance: Performing periodic maintenance
...skipping...
Traceback (most recent call last):
File "/opt/zenoss/Products/ZenModel/MaintenanceWindow.py", line 659, in retrySingleDevices
processFunc([dev])
File "/opt/zenoss/lib/python2.7/site-packages/ZODB/transact.py", line 44, in g
r = f(*args, **kwargs)
File "/opt/zenoss/Products/ZenModel/MaintenanceWindow.py", line 631, in _setProdState
raise POSKeyError("Debug exception")
POSKeyError: 'Debug exception'
2020-10-21 12:58:59,025 ERROR zen.MaintenanceWindows: The production stage change for <LinuxDevice at qa-ubuntu-12> raised the exception.
Traceback (most recent call last):
File "/opt/zenoss/Products/ZenModel/MaintenanceWindow.py", line 659, in …
```

ZEN-31805: RM 6.3.2 Maintenance Windows fail to change production state for batch of devices if a single device has a conflictError

---

Products/Jobber/model.py
Products/Jobber/tests/test_jobstore_updates.py

A job that is set to RETRY is not ended, but will run again later.
Fixes ZEN-33176.

job_end should verify the job has ended.

---

Products/Jobber/task/base.py
Products/Jobber/task/dmd.py

Don't set a new ID when a job is retried.

---

Products/ZenMessaging/queuemessaging/publisher.py

Send a MessagePostPublishingEvent only if the transaction comitted successfully.
Fixes ZEN-32890.

Only notify with successful transaction.

---

Products/Zing/README.md
Products/Zing/configure.zcml
Products/Zing/tx_state.py
Products/Zing/zing_connector.py

The NullZingClient is an IZingConnectorClient implementation that performs no I/O with the zing-connector service.
Fixes ZEN-33186.

Add NullZingClient component.

---

Products/Zing/datamaps.py

This commit adds check for event.datamap.target in Zing/datamaps.py.
Event can be without target when datamap contains 'remove=True' or
'add=False' directives for a non-existing component. This is a valid
case for ApplyDataMap but Zing/datamaps.py expected that target is
not None

ZEN-33251 Unit tests failure for PythonCollector zenpack

---

Products/ZenUtils/Executor.py

This commit changes the executor logging. Tracebacks are showed only in the
debug mode now
Backport of https://github.com/zenoss/zenoss-prodbin/pull/4002/files

ZEN-33265 Traceback in zenperfsnmp log if device has incorrect credentials

---

Products/ZenRRD/runner.py
Products/ZenRRD/zencommand.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3958/files

ZEN-33272 Tracebacks 'Bad task  executor 'in zencommand log for all linux devices

---

Products/ZenModel/DeviceClass.py

Backport of https://github.com/zenoss/zenoss-prodbin/pull/3988

ZEN-33261 Moving a device to a class with a different zPythonClass will orphan the IpAddress associated with the manageIp

---

Products/ZenHub/tests/test_zenhubworker.py
Products/ZenHub/zenhubworker.py

Add additional database sync when we get remote Service
to restore db connection.
Backport of https://github.com/zenoss/zenoss-prodbin/pull/3949

ZEN-33256 Handle case with lost connection to MySQL

---

Products/ZenModel/MaintenanceWindow.py
Products/ZenModel/tests/testMaintenanceWindow.py

Backported a257165076a8f02bf1a58aaad081032dba461a7c and added unit test

ZEN-33274 Maintenance Windows fail to change production state for batch of devices if a single device has a ConflictError

---

Products/ZenModel/ZVersion.py
makefile

Modify ZVersion.py to read from os.environ instead of Zenoss package.  The value of ZVersion.VERSION should reflect the version number specified in product-assembly, not prodbin.
Fixes ZEN-33350.

Generate ZMigrateVersion.py for prodbin build.

---

javascript.mk
makefile
migration.mk
zenoss-version.mk

* Separate ZMigrateVersion.py build from zenoss-version package.
* Update makefile phony targets depend on real targets.
* Exclude the ZenUITests and migrate tests from the artifact.
* Move sitecustomize.py to its final location in artifact.

Refactor code for building prodbin artifact.

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Now users can't move the device under /Devices, /Groups, /Systems and /Locations.
Users can move devices only to nested organizers
Fixes ZEN-33345

ZEN-33345 Remove possibility to move the device to organizer root

---

legacy/sitecustomize.py
makefile

The sitecustomize.py file is installed by product-assembly as sitecustomize.py is about more than just the contents of prodbin.
Fixes ZEN-33400.

Remove sitecustomize.py from prodbin.

---

Products/ZenHub/services/ModelerService.py

- Fix the problem when we see the following error instead of actual traceback:
`2018-07-11 14:24:15,559 ERROR zen.ZenModeler: exceptions must be old-style classes or derived from BaseException, not str
Traceback (most recent call last):
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 716, in processClient
if driver.next():
File "/opt/zenoss/Products/ZenUtils/Driver.py", line 63, in result
raise ex
TypeError: exceptions must be old-style classes or derived from BaseException, not str`
Because of a wrong order of @translateError decorator, remote exceptions in transact decorator are handled incorrectly. This commit sets the correct order of decorators

ZEN-30634 Traceback Generated When Manually Modelling Devices

---

Products/ZenRRD/zencommand.py

Datasource commmands finishing with non-zero exit code is not an error.
Fixes ZEN-33469.

Restore zencommand error code handling.

---

Products/ZenModel/MaintenanceWindow.py
Products/ZenModel/migrate/addTzToMaintWindows.py
Products/ZenModel/tests/testMaintenanceWindow.py
Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js
Products/ZenUtils/Time.py
Products/Zuul/infos/devicemanagement.py

- Now every MW has its own timezone. MWs are independent of the server timezone
- Use timezoned datetime for time calculations (for proper DST calculations)
- Add timezone field in UI (when editing MW)
- Add unit tests to check DST calculations

ZEN-29799 Maintenance Window Localization Doesn't Handle DST

---

Products/ZenUtils/Time.py

After migration, existing MWs should have the timezone from serviced config

ZEN-33520 'Time Zone' field is blank after upgrade if time zone wasn't default

---

Products/Zuul/facades/metricfacade.py

The renameDevice method in metricfacacade now correctly handles log message types received from Central Query.
ZEN-33548.

Stop incorrect "unknown log msg type" log messages.

---

Products/ZenModel/skins/zenmodel/dialog_addUserToAGroup.pt
Products/ZenModel/skins/zenmodel/dialog_addUserToGroup.pt

This way of adding a previously non-existent user to a group can result
in breaking things in a CZ. Only users with the CZAdmin role, and
therefore the "Manage Users" permission should be allowed to add new
users to a group. Users with the ZenManager role will still be allowed
to add existing users to groups.
Fixes ZING-14314.

Fix adding new user to group without permissions

---

Products/Zing/fact.py

This is to allow organizer entities in cloud to be found when searching
for entities in the organizers.

ZEN-33612: add organizer field to organizer facts

---

Products/ZenModel/DataRoot.py

fix for ZEN-32234
Removing traceback from error_formatted will prevent the call-stack from being printed to the Console

Removing traceback from error_formatted

---

Products/ZenHub/services/ModelerService.py

Because of a wrong order of @translateError decorator, remote exceptions
are handled incorrectly. This commit sets the correct order of decorators
ZEN-33220

Reveal remote exceptions

---

Products/ZenRRD/runner.py
Products/ZenRRD/zencommand.py
Products/ZenUtils/Executor.py

No new timeouts were added.  Instead, existing timeouts were handled differently to ensure that tasks will exit when a timeout occurrs.
Fixes ZEN-33565.

Improve timeout handling on unstable networks.

---

Products/ZenModel/UserSettings.py
Products/Zuul/facades/tests/test_userfacade.py
Products/Zuul/facades/userfacade.py
Products/Zuul/infos/group.py
Products/Zuul/routers/users.py

This adds management methods to edit user, group, and role methods to the Zuul user_router
Includes unit test
https://jira.zenoss.com/browse/ZING-15272

Adding user/group/role methods to the Zuul user router

---

Products/ZenModel/ZenPack.py

Store a ZenPack's module name as an attribute.

---

Products/DataCollector/Plugins.py

Also cache a ZenPack's module name locally rather than repeatedly calling the method.
Fixes ZEN-33761.

Make no attempt to load empty parser names.

---

Products/DataCollector/zenmodeler.py
Products/ZenCollector/cyberark.py
Products/ZenCollector/tests/test_cyberark.py
Products/ZenRRD/zencommand.py
Products/ZenRRD/zenperfsnmp.py

Removes guesswork in identifying the device associated with the given device config.

Change update_config API in CyberArk integration

---

Products/ZenUI3/browser/resources/js/zenoss/Security.js
Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassConsole.js
Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js
Products/ZenUtils/extdirect/router.py

Fixes ZEN-32905.
To fix type errors related to getSecurityPermissions() and
getTransformTree() which were observable for the customer through the
UI, the default value for event class was set. After changes when the
customer opens Events -> Even Classes and chose Transforms in the
drop-down menu before selecting an event class, no errors will occur,
instead of them the transforms for Events will be shown.

Fix UI tracebacks messages for event transforms

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Fixes ZEN-33971.
Graph point legend was represented on the UI side with the cutting of
the first word if the legend is long. The issue appeared because of the
wrong legend rendering on the UI.

Fix UI representation of graph point legend

---

Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py

Fixes ZEN-33839.
To handle the issue with UnicodeDecodeError the decoding procedure was
modified by adding an additional check. The procedure tries to decode
values using zCollectorDecoding if it is defined, otherwise, it tries to
apply the default encoding (usually utf-8). If decoding of the value in
strict mode causes errors, then it will be done in ignore mode,
therefore non-Unicode symbols will be ignored and the corresponding
record will be added to the log.

Process and log the UnicodeDecodeError

---

Products/DataCollector/SshClient.py

Fixes ZEN-31888.
To fix the issue the logic of nested function hasattr_path() within
sendEvent() for SshClient was changed and simplified. Since the
object_root objects, which is an argument for the hasattr_path()
function, has a defined structure that contains the attribute 'factory'
and doesn't contain any other parts of splitting using "." for
"factory.hostname", "conn.factory.hostname",
"factory.datacollector.sendEvent", "factory.sendEvent",
"datacollector.sendEvent", "conn.factory.datacollector.sendEvent", which
are used as a value for the parameter "path". Consequently the logic of
hasattr_path() was changed to inclusion check of "factory" to
path.split(".").

Fix hasattr_path within sendEvent for SshClient

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/triggers.js

Fixes ZEN-33402.
The issue appeared because the "Everyone can view" style for triggers
and notification forms were the same as for other elements (etc.
windows). To fix the problem triggers and notification forms were
extended by adding the new CSS class, which implements a specific
"Everyone can view" style for forms.

Make trigger and notification forms more readable

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/triggers.js

Fixes ZEN-33838.
The issue appeared because the "Everyone can view" style for triggers
and notification forms were the same as for other elements (etc.
windows). To fix the problem triggers and notification forms were
extended by adding the new CSS class, which implements a specific
"Everyone can view" style for forms.

Make notification and trigger forms more readable

---

Products/DataCollector/ApplyDataMap/applydatamap.py
Products/DataCollector/ApplyDataMap/datamaputils.py
Products/DataCollector/ApplyDataMap/incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/test_add_directive.py
Products/DataCollector/ApplyDataMap/tests/test_applydatamap.py
Products/DataCollector/ApplyDataMap/tests/test_datamaputils.py
Products/DataCollector/ApplyDataMap/tests/test_incrementalupdate.py
Products/DataCollector/ApplyDataMap/tests/utils.py
Products/DataCollector/tests/testHRSWRunMap.py
Products/DataCollector/tests/test_incrementalupdate_integration.py
Products/ZenModel/Device.py

* When _add == False, ADM will still update data.
* Regardless of how _add is set, ADM will not update ZODB when changes are not detected.
Fixes ZEN-32767.

Fix issues with ADM's 'add' directive.

---

Products/ZenUI3/browser/resources/js/zenoss/Action.js

Fixes ZEN-33827.
The issue occurred because pieces of code, which were removed during its
fix in ZEN-33307, were accidentally added as a part of the fix for
ZEN-33308. To resolve the issue these pieces of code were deleted and
checkDisabled function was simplified.

Fix actions menu disabling according to permissions

---

Products/ZenUI3/browser/resources/js/silent-auth/silentAuth.js
Products/ZenUI3/browser/templates/base-new.pt

Silent auth will never work with checking of key exists in browser local storage as we never put this info from other places there. 
Also, silent auth will work only if we put the CZ instance host to the  Allowed Web Origins list in https://manage.auth0.com/dashboard/us/zenoss-dev/applications/DEpUm5pU4B5mOXmVtC9CHBmAXImveJlQ/settings.
As soon as silent auth starting work there's no way to get n from zope web application, because of regular (every 30 sec) access token refreshing. https://github.com/zenoss/zenoss-prodbin/blob/c254db8cfa35e4f645e2e7f5f16ad171fade071e/Products/ZenUI3/browser/__init__.py#L46

ZEN-33669: Site error for a page that is opened for a long time

---

Products/Zuul/routers/zep.py

Fixes ZEN-33568.
The issue occurred because the verification of permissions for event
management within the organizers such as Systems, Groups, and Locations,
was performed using the names of general organizers. It didn't take into
account that different kinds of organizers can have the same names and
can have sub organizers. To fix the issue, the verification of event
management permission was changed by adding verification of sub
organizers. In addition, to identify permissions for different
administered objects the usage of the organizer name was changed on the
bread crumb URL path, which makes all identifiers unique.

Fix permission verification for event management

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/administeredDevices.pt

Fixes ZEN-34035, ZEN-34065.
The issue occurred because object names were used for the identification
of administered objects. When two different administered objects, which
are related to different organizers (e. g. Groups and Locations), have
the same name they were unrecognized as different objects. To fix the
removing of administered objects as well as updating roles for
previously added objects, the identification of objects was changed by
using the primary dmd id.

Fix user group permissions management

---

Products/ZenUtils/MySqlZodbFactory.py

```AttributeError: "'module' object has no attribute 'Error'"``` 
appears when auth0 cookies have expired and we fall into `zenoss_error_message` method [here](https://github.com/zenoss/zenoss-prodbin/blob/457b34c8b706e3785af134abe669da3661ad0a25/Products/ZenModel/DataRoot.py#L427)

ZEN-34096: Site error for a page that is opened for a long time

---

Products/ZenRRD/parsers/Auto.py

Fixes ZEN-34100.
Wrong import path cause traceback during processing
command datasource

Replace import path for ZenRRD parsers

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js
Products/Zuul/routers/zep.py

Fixes ZEN-33833.
The issue occurred because the verification of permissions for event
management within the organizers such as Systems, Groups, and Locations,
was performed using the names of general organizers. It didn't take into
account that different kinds of organizers can have the same names and
can have sub organizers. To fix the issue, the verification of event
management permission was changed by adding verification of sub
organizers. In addition, to identify permissions for different
administered objects the usage of the organizer name was changed on the
bread crumb URL path, which makes all identifiers unique.

Fix verification of permission for event management

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/administeredDevices.pt

Fixes ZEN-34036, ZEN-34074.
The issue occurred because object names were used for the identification
of administered objects. When two different administered objects, which
are related to different organizers (e. g. Groups and Locations), have
the same name they were unrecognized as different objects. To fix the
removing of administered objects as well as updating roles for
previously added objects, the identification of objects was changed by
using the primary dmd id.

Fix management of user group permissions

---

Products/Zuul/__init__.py
Products/Zuul/routers/device.py

Fixes ZEN-33828.
To resolve the issue the check for roles granted to the current user
via Administered Objects by both group membership or direct assignment
was added.

Fix management of organizers for group users

---

Products/ZenCallHome/ZenossAppData.py

Implements ZEN-34067.
Total component counts by metatype were added to callhome data.

Add component counts to callhome data

---

Products/ZenUI3/browser/resources/js/zenoss/CommandWindow.js
Products/ZenUI3/browser/resources/js/zenoss/ExtOverrides.js

Fixed "copy to clipboard" for a lot of output. 
Fixes [ZEN-34078](https://jira.zenoss.com/browse/ZEN-34078)
Moved changes from this PR https://github.com/zenoss/zenoss-prodbin/pull/3414
This should fix for support/6.x
Checked manually

ZEN-34078: Copy to Clipboard doesn't work when Model Device (Debug) generates a lot of output (backport)

---

Products/ZenRRD/zencommand.py
Products/ZenUtils/Executor.py

Fixes ZEN-28577.
The TypeError in CancelledError handling in Executor occurred because
the wrong log string formatting in the CancelledError handling section
in Executop.py was made. The issue was resolved by fixing the string
formatting. The issue occurred due to improper processing of errors
twisted.internet.defer.CancelledError and
twisted.internet.error.ConnectionLost, which caused adding events with
an empty summary. To fix the problem, additional except-sections for
these errors were added, which handle these errors and send events with
a clear non-empty summary for twisted.internet.error.ConnectionLost.

Fix the creation events with an empty summary

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceDialogs.js

Fixes ZEN-34172.
To resolve the issue the option to migrate performance data during
device re-identifying was removed by changing of device
re-identification form.

Change the form of the device reidentifying

---

Products/ZenUI3/browser/resources/js/zenoss/triggers.js

Fixes ZEN-34136.
The issue occurred because of the mistake in the backport ZEN-33838,
which was fixed.

Fix trigger form for admin/zenmanager user

---

Products/ZenUI3/browser/resources/js/zenoss/AddToZenPackWindow.js

Fixed an issue that occurs when a user tries to add a new process to ZenPack.
[Defect: ZEN-34077](https://jira.zenoss.com/browse/ZEN-34077)
Tested manually

Fixed TypeError when add process class to zenpack

---

Products/ZenModel/zenmib.py

Fixes ZEN-34191.
The issue occurred because the loadPath, which means upload directory
path, for Meraki ZenPack runMibLoader was set without a leading slash.
The issue was fixed by adding corresponding verification of the MIBs
organizer path and adding the leading slash when it is required.

Fix adding MIBs during Meraki ZP installation

---

Products/ZenCallHome/transport/methods/directpost.py

Callhome reports take ~8 seconds to complete on average with half of that involved with calling SalesForce. We need to increase the timeout so that callhome has enough time to generate a report and callback.

SRE-2609 Increase Timeout For Generating Callhome Report Directly

---

Products/ZenHub/services/PingPerformanceConfig.py

During the ZEN-34454 fix, there was an incorrect transfer of `dp.getTags(iface)` inside the `IpAddressProxy`. 
This class isn't working with a real context `iface` just with the `title` but `dp.getTags` method requires real context.
In the fix, we passed through the new constructor arg of `IpAddressProxy`  the real context for the target method

ZEN-34591: ZEN-34454 potentially causes silent zenping failure

---

Products/ZenModel/MetricMixin.py
Products/Zuul/facades/devicefacade.py

Fix display of templates in DeviceClass details view so that all available templates are displayed, but bound templates are marked and displayed at the top of the list, and replaced templates are also marked.

Fix display of templates in DeviceClass details view

---

Products/ZenUI3/browser/modelapi/configure.zcml
Products/ZenUI3/browser/modelapi/modelapi.py

Implements ZEN-34675.
Added model API browser view for Config Cache components. 
It needs for RMMonitor ZP to be able to model these components.

Add model API for Config Cache components

---

Products/ZenUI3/browser/modelapi/modelapi.py

Implements ZEN-34675.
To avoid JS errors and unnecessary code on the RM Monitor ZP side the configcahe response keys are corrected.

Change configcache modelapi response keys

---

Products/ZenCollector/configcache/tests/test_dispatcher.py
Products/ZenCollector/configcache/utils/dispatcher.py

Signature objects create a task ID by default, so re-using the same signature to send tasks results in the same task ID being used.
ZEN-34687

fix: don't cache celery Signature objects.

---

Products/ZenCollector/configcache/tests/test_propertymap.py
Products/ZenCollector/configcache/utils/propertymap.py

The DevicePropertyMap is initialized with a default value that is returned when no match is found in the map.
ZEN-34653

fix: add default value to DevicePropertyMap

---

Products/ZenCollector/configcache/cache/model.py
Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/tests/test_propertymap.py
Products/ZenCollector/configcache/tests/test_propertymap_makers.py
Products/ZenCollector/configcache/tests/test_storage.py
Products/ZenCollector/configcache/utils/__init__.py
Products/ZenCollector/configcache/utils/constants.py
Products/ZenCollector/configcache/utils/propertymap.py
Products/ZenCollector/configcache/utils/services.py
Products/ZenModel/migrate/addConfigCacheProperties.py
Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/zPropertyCategory.py

This zproperty specifies the number of seconds a configuration must exist before it can be expired.
ZEN-34656

Add zDeviceConfigMinimumTTL property.

---

Products/ZenCollector/configcache/invalidator.py

Devices without a monitor cannot be monitored and so do not need configs.
ZEN-34701

fix: skip devices having an undefined monitor.

---

Products/ZenCollector/daemon.py

Moved creating the DeviceConfigLoader ahead of creating the task stats logger which depends on the DeviceConfigLoader object existing.
ZEN-34705

fix: switch creation order to avoid race.

---

Products/ZenCollector/scheduler/__init__.py

Fixes ZEN-34719.
Added CallableTaskFactory and CallableTask classes to scheduler __init__.py

Fix ImportError for zenvsphere daemon

---

Products/ZenCollector/daemon.py
Products/ZenHub/PBDaemon.py

The PBDaemon class started a task that was accessing an attribute of the DeviceConfigLoader before the DeviceConfigLoader instance was created. This race condition was fixed by moving the creation of the DeviceConfigLoader instance to an earlier point in CollectorDaemon's startup.
ZEN-34705

fix: avoid race condition involving device config loader

---

Products/ZenHub/PBDaemon.py
Products/ZenHub/tests/test_PBDaemon.py

fix: only start the 'local server' when the 'cycle' option is set.

---

Products/ZenCollector/config/task.py
Products/ZenCollector/daemon.py
Products/ZenCollector/services/config.py

The startup process has also been changed to allow the configuration task to complete a first run before device configs are loaded.
ZEN-34681

fix: CollectorDaemon exits for given an unknown device

---

Products/ZenCollector/configcache/cache/model.py
Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/cli.py
Products/ZenCollector/configcache/invalidator.py
Products/ZenCollector/configcache/manager.py
Products/ZenCollector/configcache/propertymap.py
Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_propertymap_makers.py
Products/ZenCollector/configcache/tests/test_storage.py

Set the 'pending' status when dispatching config build jobs for new devices. Clear statuses on cache keys that have no configurations.
ZEN-34739

fix: correctly support building configs for new devices

---

Products/ZenCollector/configcache/invalidator.py

The get_status method returns a generator which must be iterated to retrieve the values.
ZEN-34747

fix: use get_status method correctly.

---

Products/ZenCollector/zencyberark.py

Also renamed the '--debug' option to '--verbose'.
ZEN-34750

fix: configure logging for stdout in zencyberark

---

Products/ZenHub/services/CommandPerformanceConfig.py
Products/ZenRRD/runner.py

Old behavior was to not create a config if SSH credentials were not defined, but this behavior does not work with the configcache system. So, allow zencommand to receive configs without SSH credentials and accept the errors that happen.
ZEN-34758

Allow zencommand to get configs without defined credentials.

---

Products/Jobber/bin.py
Products/Jobber/worker.py

The ZenPacks defining their own jobs must add a jobs.zcml file that identifies these jobs so that zenjobs can find and register them.
ZEN-34751

fix: revert to depending on jobs.zcml to register jobs

---

Products/ZenEvents/Availability.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenModel/ZenMenuItem.py
Products/ZenModel/migrate/Migrate.py
Products/ZenModel/tests/testMigrate.py
Products/ZenUtils/Version.py

Some __cmp__ implementations don't work with 'in' operators and __cmp__ is not supported in Python 3.
ZEN-34657

Replace __cmp__ with __eq__/__lt__/__le__ combos.

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/tests/test_storage.py

json.loads makes a transformation that unjelly doesn't like.
ZEN-34797

Use ast.literal_eval instead of json.loads.

---

Products/ZenCollector/configcache/task.py
Products/ZenCollector/configcache/tests/test_task.py

The DevicePropertyMap is replaced with a direct zproperty lookup, which requires fewer resources to run.
ZEN-34835

fix: replace DevicePropertyMap with a direct lookup.

---

Products/Jobber/bin.py
Products/Jobber/config.py
Products/Jobber/signals.zcml
Products/Jobber/worker.py
Products/Jobber/zenjobs.py

Set the Celery config early during startup because Celery doesn't appear to support being configured multiple times.  Only the initial configuration is used by Celery.
ZEN-34828

fix: configure Celery on initialization

---

Products/ZenCollector/configcache/modelchange/oids.py

Sometimes, an object doesn't have the getParentNode method, so record this unexpected situation into the log.
ZEN-34834

Add error handling around getParentNode.

---

Products/Jobber/model.py
Products/Jobber/tests/test_redisrecord.py

Enabling the Celery's message protocol v2 has changed the structure of the data passed to the save_jobrecord function, so this commit updates the function to handle the changed structure of the inputs.
ZEN-34843

Inputs into save_jobrecord have changed.

---

Products/Jobber/task/base.py
Products/Jobber/task/dmd.py
Products/Jobber/tests/test_dmd.py
Products/ZenCollector/configcache/task.py
Products/ZenModel/Device.py

Add the `dmd_read_only` attribute to tasks using the `DMD` mixin class. When set to True, the transaction is aborted when the task completes. By default, `dmd_read_only` is False.
ZEN-34849

Add `dmd_read_only` flag to `DMD` mixin class.

---

Products/ZenCollector/daemon.py

A device's config may have a `configId` value different from the `id` value, so compare a user specified device ID with the config's `id` value.
ZEN-34850

Compare user input device ID to the device ID.

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/cli/__init__.py
Products/ZenCollector/configcache/cli/_groups.py
Products/ZenCollector/configcache/cli/_json.py
Products/ZenCollector/configcache/cli/_stats.py
Products/ZenCollector/configcache/cli/_tables.py
Products/ZenCollector/configcache/cli/list.py
Products/ZenCollector/configcache/cli/stats.py
Products/ZenCollector/configcache/cli/stats.zcml
Products/ZenCollector/configcache/configcache.py

The 'stats' subcommand will return a report on different statistics regarding the current state of the configuration cache.
The set of statistics include count, average age, median age, minimum age, and maximum age.  These statistics are grouped by service class, collector (monitor), status, and device.
ZEN-34892

Add 'stats' subcommand to configcache command.

---

Products/ZenCollector/configcache/cache/storage.py

A re-entrant function can be called multiple times, so its inputs must also be re-entrant.
ZEN-34921

Don't pass a generator to a re-entrant function.

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Fixes ZEN-34727.
*Hitting refresh button didn't refresh
the infrastructure and event console page device list. The refresh method now includes a store
reload to ensure that the latest data is
fetched and displayed

Added store reload during grid refresh

---

bin/metrics/zenossStatsView.py

Fixes ZEN-34680.
Added last change record for Zope config files.
Now we are comparing the returned last modified value
with a recorded last change value.

 Improve zproxy metrics collection reliability

---

bin/metrics/zenossStatsView.py

Fixes ZEN-34955.
Added last change record for Zope config files.
Now we are comparing the returned last modified value with a recorded last change value.

Improve zproxy metrics collection reliability

---

Products/ZenModel/ZenPacker.py

Fixes ZEN-34923.
When findObject is being executed during the job running the id object passed in the unrestrictedTraverse method could be unicode. It breaks the method and findObject returns an empty list while the object exists which is incorrect.

Add unicode type check for the object id

---

Products/Zuul/facades/devicefacade.py

Fixes ZEN-34960.
Moved -addition and -replacement for bound templates into bound section and place all unbound under "Available" tree node.

Rework device/deviceclass template representation

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Fixes ZEN-34963.
Changed the order to store reload followed by grid refresh to ensure that the grid's refresh operation occurs after the store has been updated with new data from the server

Fix for refresh button

---

Products/ZenCollector/configcache/cache/storage.py
Products/ZenCollector/configcache/handlers.py
Products/ZenCollector/configcache/tests/test_deviceupdatehandler.py

The DeviceUpdateHandler now considers the current status when expiring or retiring a config.
ZEN-34962

Expire or retire configs more carefully.

---

Products/Jobber/monitor/broker.py
Products/Jobber/monitor/collector.py
Products/Jobber/monitor/handler.py
Products/Jobber/monitor/metrics.py
Products/Jobber/monitor/reporter.py

Refactored thread locking for metric updates to ensure all metrics are updated together for each Celery event.
Added more logging to identify missing data or issues related to retrieving metric data.
ZEN-34974

Save the zenjobs metrics to the current service.

---

Products/Jobber/monitor/logger.py

Specified no handlers for zenjobs-monitor's root logger.

---

Products/ZenModel/ZenossInfo.py

Removed Erlang from the zenossVersions page

---

Products/ZenUtils/MetricServiceRequest.py
Products/Zuul/facades/metricfacade.py

Fixes ZEN-35026.
An error 'Response from the server (return code 400): Unrecognized field "format" generated in the event log for GCP device

ZEN-35026:ZEN-34707 Fix error in event log for GCP device

---

Products/ZenUtils/MetricServiceRequest.py

Fixes ZEN-35025.
Warning 'Received response 400 from Central Query' is generated in zenpython log

ZEN-35025:ZEN-34693 Fix error in zenpython log

---

Products/ZenModel/ZenossInfo.py

ZEN-34996:ZEN-34980 Removed Erlang from the zenossVersions page

---

Products/ZenUtils/Auth0/Auth0.py

When the accessToken cookie is missing, invalidate any prior sessionInfo.
This will cause the user to be redirected to czlogin, to obtain new auth credentials.

ZING-35683: Fix issue with users receiving Unauthorized error rather than being sent to log back in

---

Products/ZenCollector/configcache/cli/expire.py
Products/ZenCollector/configcache/cli/list.py
Products/ZenCollector/configcache/cli/remove.py
Products/ZenCollector/configcache/cli/show.py
Products/ZenCollector/configcache/cli/stats.py
Products/ZenCollector/configcache/cli/tests/test_expire.py
Products/ZenCollector/configcache/cli/tests/test_list.py
Products/ZenCollector/configcache/cli/tests/test_remove.py
Products/ZenCollector/configcache/cli/tests/test_show.py

The configcache commands now require the user to specify `*` to get wildcard selection behavior.
ZEN-35054

Remove implicit wildcards from configcache commands.

---

Products/ZenCollector/configcache/tasks/deviceconfig.py
Products/ZenCollector/configcache/tests/test_build_device_config.py

The build_device_config job will now delete the device configuration for any device not found in ZODB.
ZEN-34818

Delete the config when the device ID is not found.

---

Products/ZenUtils/patches/mysqladaptermonkey.py

Fixes ZEN-35111.
*Resolved a TypeError that occurred during the execution of the connmanager.close method in the monkeypatched MySQLdbConnectionManager.

Fix TypeError when running zenossdbpack

---

Products/ZenUtils/patches/zodbpackmonkey.py

Fixes ZEN-35111.
*Resolved a IntegrityError that occurred
during pre_pack procedure.

Fix IntegrityError when running zenossdbpack

---

Products/ZenHub/invalidationmanager.py
Products/ZenHub/invalidations.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenHub/tests/test_invalidationmanager.py
Products/ZenHub/tests/test_invalidations.py
Products/ZenHub/zenhub.py

Removed code that converted ZODB OIDs into an int and stored that int in an IITReeSet object.  IITreeSet objects are limited to 32 bit values and nothing actually used the IITreeSet object's contents, so all code related to the IITreeSet was removed.
ZEN-35118

Remove unnecessary code in zenhub's invalidations.

---

Products/Jobber/tests/test_worker.py
Products/Jobber/worker.py

zenjobs will cause a Celery subprocess worker to exit if the ZODB connection cannot be created.
ZEN-35127

Detect ZODB init failures and exit if not fixable.

---

Products/ZenUtils/MySqlZodbFactory.py
Products/ZenUtils/tests/test_MySqlZodbFactory.py

Retry creating the RelStorage object when an OperationalError exception is raised.  Raise SystemExit if the RelStorage cannot be created.
ZEN-35133

Add error handling when creating RelStorage object.

---

Products/DataCollector/SnmpClient.py
Products/ZenEvents/zentrap/users.py
Products/ZenHub/services/PerformanceConfig.py
Products/ZenHub/services/SnmpTrapConfig.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenRRD/zenprocess.py

SNMP v3 users now always require a passphrase if a protocol is specified.  The Privacy protocol/passphrase is ignored if no Authentication protocol/passphrase is specified.  The Authentication protocol/passphrase is ignored if no security user is specified.
ZEN-35108

Hardened the API regarding SNMP v3 users.

---

Products/ZenCollector/configcache/manager.py

A ConfigStatus only has two elements when converted into a tuple.
ZEN-35085

Fixed converting a ConfigStatus into a tuple.

---

Products/ZenModel/Device.py
Products/ZenModel/IpAddress.py
Products/ZenModel/IpInterface.py
Products/ZenModel/IpNetwork.py
Products/ZenModel/IpRouteEntry.py
Products/ZenModel/tests/testIpAddress.py
Products/Zuul/facades/networkfacade.py

Ensure devices and ipaddress objects clean up their respective relations upon deletion. On subnetwork move, update rels on ipaddresses used by manageIp. Don't remove relations when moving a device. Add a unit test.

ZEN-33550 Improve relationship management of IpAddress objects

---

Products/ZenRelations/ToManyRelationship.py
Products/ZenRelations/ToOneRelationship.py
Products/Zuul/facades/networkfacade.py
Products/Zuul/utils.py

Attempting to remove a remote relation that doesn't exist is likely not an error.
Also added try_unbrain to have a unbrain that doesn't raise an exception if it fails to resolve to a ZODB object.
ZEN-35164

Change ERROR log to DEBUG.

---

Products/ZenUtils/patches/zodbpackmonkey.py

Added methods to identify and remove orphaned references in ZODB.object_ref that were causing zenossdbpack to fail to remove oid groups.

Fixes ZEN-35223

---

Products/Jobber/task/event.py
Products/ZenCollector/configcache/tasks/deviceconfig.py

Record the error and send an event.
ZEN-35030

Don't allow config build errors to propogate to Celery.

---

src/Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js
src/Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

Created two new entries in Zenoss.env.textMasks in zenoss.js:
- allowedNameTextDashDotPipeComma
- allowedNameTextFeedbackDashDotPipeComma
Updated ClassPanels.js to use the above entries for the Event Class Key textfield.

Fixes ZEN-34753

---

src/Products/Jobber/model.py
src/Products/Jobber/task/event.py

Allows job failure events to be sent as expected and also logs which job has a bug in its getJobDescription method.
ZEN-35252

Handle errors when calling 'description_from'.

---

src/Products/ZenHub/PBDaemon.py
src/Products/ZenUtils/MetricReporter.py

Changed the eventQueueLength metric post interval from 2 seconds to the value specified by the 'writeStatistics' configuration option.
ZEN-35254

Use writeStatistics for eventQueueLength metric updates.
