zenoss/zenoss-prodbin

Products/ZenModel/ZenPack.py
Products/ZenUtils/ZenPackCmd.py

Use class variable for service id

---

Products/Zuul/facades/zepfacade.py

Related to https://github.com/zenoss/zenoss-zep/pull/54

ZEN-15429 - Sort UUIDs for better caching

---

Products/ZenUtils/zenpack.py

This is to cover a specific type of issue where a zenpack install tries
to touch database objects while the system has objects supplied by a
broken zenpack.  The solution is to try and fix the broken zenpack
objects, then retry the install of the pervasive touch-everything
zenpack.

ZEN-16380: Retry to restore zenpacks that failed

---

Products/ZenUtils/zenpack.py

Fixes a bug where zenpack --restore's from a x.x.xdev version to a
non-dev x.x.x would fail.

ZEN-16404: ZenPack restores from dev to non-dev version

---

Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/device_export.py
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js
Products/ZenUI3/browser/templates/itinfrastructure.pt

For https://jira.zenoss.com/browse/ZEN-15723

ZEN-15723: Add Export button to device list view on Infrastructure page

---

Products/ZenUtils/Utils.py

Fix wanted for Impact 5.0 - please pick for RM 5.0.1.

Use titleOrId preferentially for displayName

---

Products/ZenUI3/browser/backcompat.py
Products/ZenUI3/browser/views.py

Fix wanted for Impact 5.0 - please pick for RM 5.0.1.

Handle arguments through the Goto redirect and the device devault view

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

Forgotten sorting function somehow. All other port data is there.

ZEN-16710 ZenPack component tree sorting override ability

---

Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/device_export.py
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js
Products/ZenUI3/browser/templates/itinfrastructure.pt

Fixes https://jira.zenoss.com/browse/ZEN-16752,
port of https://jira.zenoss.com/browse/ZEN-16003.

ZEN-16752: Add Export button to device list view on Infrastructure page

---

Products/Zuul/routers/zep.py

port from 4.2.5:
https://github.com/zenoss/4.2.5-RPS/pull/348/files

ZEN-15291: NOT filters not working for the archive console

---

Products/ZenEvents/SyslogProcessing.py

Related PR to develop: https://github.com/zenoss/zenoss-prodbin/pull/704

ZEN-15393: updated regexp for Cisco ACS syslog messages

---

Products/ZenHub/__init__.py
Products/ZenHub/zenhub.py

https://jira.zenoss.com/browse/ZEN-16772
cherry-pick of https://github.com/zenoss/zenoss-prodbin/pull/759

fixes ZEN-16772: zenhub should use socket options for keep alive on PB connections

---

Products/ZenEvents/zeneventdEvents.py

4.2.5 port:
https://github.com/burbel/4.2.5-RPS/commit/926c9fb3577b370dd7f0a39c2f6a78a41d3b57f2

ZEN-15659: Create new zeneventd.conf options

---

Products/ZenEvents/zeneventdEvents.py

5.1.0 port:
https://github.com/zenoss/zenoss-prodbin/pull/767/files

ZEN-16821: Create new zeneventd.conf options

---

Products/ZenEvents/zeneventdEvents.py

Reverts zenoss/zenoss-prodbin#767

Revert "ZEN-15659: Create new zeneventd.conf options"

---

Products/ZenEvents/zeneventdEvents.py

Reverts zenoss/zenoss-prodbin#768

Revert "ZEN-16821: Create new zeneventd.conf options"

---

Products/ZenCollector/services/config.py
Products/ZenHub/services/ModelerService.py

Fixing https://jira.zenoss.com/browse/ZEN-15883

ZEN-15883: Catalog issues stop data collection

---

Products/ZenCollector/services/config.py
Products/ZenHub/services/ModelerService.py

Reverts zenoss/zenoss-prodbin#780

Revert "ZEN-15883: Catalog issues stop data collection"

---

Products/ZenUI3/browser/device_export.py

Updates for https://jira.zenoss.com/browse/ZEN-15723:
reporting only integer value displayed at infrastructure page.

ZEN-15723: reporting events as displayed.

---

Products/ZenUtils/tests/testTopoPrioritize.py
Products/ZenUtils/zenpack.py

Cherry-picked #803
Fixes https://jira.zenoss.com/browse/ZEN-17030

Please review branch feature/ZEN-17030

---

Products/ZenUtils/PortScan.py

Fixes ZEN-17104

---

Products/Zuul/infos/monitor.py
Products/Zuul/routers/device.py
Products/Zuul/routers/monitor.py

+ Allow moving a collector's worth of devices at once to another
collector

Router changes to move devices

---

Products/ZenUI3/browser/resources/js/zenoss/ExtOverrides.js

Due to EXTJSIV-6824, which is fixed in the 4.2 timeframe.  This code
should be removed once we upgrade ExtJS

Fix multi select in tree panels

---

Products/DataCollector/SnmpClient.py

port: https://github.com/zenoss/4.2.5-RPS/pull/461/files

ZEN-17398: SNMP Agent Down Events Not Detected during device modeling.

---

bin/zenrun.d/zenmib.sh

https://jira.zenoss.com/browse/ZEN-16883

change pwd to /mnt/pwd on zenmib script

---

Products/ZenUtils/controlplane/client.py

Related to:
https://github.com/control-center/serviced/pull/1703
https://github.com/control-center/service-migration/pull/18

servicemigration rest endpoint

---

Products/ZenModel/migrate/setDMDVersion.py

Please review branch feature/ZEN-17657

---

Products/ZenUI3/browser/resources/js/zenoss/JobsWidget.js

Please review branch feature/ZEN-17773

---

Products/ZenUI3/browser/eventconsole/view-events.pt
Products/ZenUI3/browser/eventconsole/view-history-events.pt
Products/ZenWidgets/skins/zenui/javascript/geomap.js

ZEN-11620  Navigation through google map dashboard for device event is not working properly

ZEN-11620  Navigation through google map dashboard for device event is not working properly

---

Products/DataCollector/SnmpClient.py

Please review branch feature/ZEN-17403

---

Products/ZenUI3/browser/eventconsole/view-events.pt
Products/ZenUI3/browser/eventconsole/view-history-events.pt
Products/ZenWidgets/skins/zenui/javascript/geomap.js

Please review branch feature/feature/ZEN-15034

---

Products/ZenRRD/parsers/JSON.py

Please review branch feature/ZEN-17755

---

Products/ZenEvents/zentrap.py

Please review branch feature/ZEN-17754

---

Products/ZenModel/UserInterfaceSettings.py
Products/ZenUI3/browser/resources/js/zenoss/JobsWidget.js
Products/ZenUI3/tooltips/data/en/userInterfaceConfig.xml

Please review branch feature/ZEN-17189

---

Products/ZenModel/migrate/ChangeConInfoEngine.py
Products/ZenUtils/patches/mysqladaptermonkey.py
Products/ZenUtils/relstorage/mysql/003.sql

Please review branch feature/ZEN-17756

---

Products/ZenModel/DeviceReport.py
Products/ZenModel/skins/zenmodel/viewDeviceReport.pt
Products/ZenWidgets/ZenTableManager.py

Please review branch feature/ZEN-17782

---

Products/ZenUI3/browser/device_export.py
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Please review branch feature/ZEN-17775

---

Products/ZenModel/ZenPackLoader.py
Products/ZenModel/migrate/addPrefixToTriggerRule.py

Please review branch feature/ZEN-17516

---

Products/ZenRelations/ImportRM.py
Products/ZenUtils/Utils.py

Cherry-picked 6a5c362b7154047feafce167c1eef0c8537d0930
Cherry-picked b2661a91f0058ece9b8e0b1b9ab367c592aafcb0

Please review branch feature/ZEN-17772

---

Products/Zuul/infos/event.py

Please review branch feature/ZEN-17757

---

Products/DataCollector/CommandParsers/Linux_netstat_an.py

Fix [ZEN-17843](https://jira.zenoss.com/browse/ZEN-17843)

Fix parse failure from unhandled format

---

Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py

modified:   Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py

Changed logic (order of call); ZEN-18655

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

cherry-pick commit 304eab36e9a19896e3c66780abb1998e44ccdf7e

Fixes ZEN-17972

---

bin/zenrun.d/zenmib.sh

cherry-pick commit a39ab762776f91b95ba73a4ac2264a33613859f9

Fixes ZEN-17174

---

Products/ZenRRD/zentestcommand.py

Please review branch feature/ZEN-16692

---

Products/ZenUI3/browser/device_export.py

Please review branch feature/ZEN-16752

---

Products/ZenModel/Device.py

cherry-pick commit 2e19dbc611d0a7f51a8b5f18b83682b1dad053bf

Fixes ZEN-18143

---

Products/Zuul/facades/userfacade.py

cherry-pick commit 73c66ab81fb4e2e49cc81925661432252928108b

Fixes ZEN-17964

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Tweak sizing
Remove console log
make popup scale to screen and be unresizable
Remove commented out maxWidth

Add graph panel popup

---

Products/ZenUtils/zenpack.py

Resolve issue with zenpack restore and a brand new dependency in a new
version of an existing zenpack

ZEN-18262: Zenpack restore with a new dep.

---

Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py

Please review branch feature/ZEN-17778

---

Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py
Products/DataCollector/plugins/zenoss/cmd/linux/netstat_an.py
Products/DataCollector/plugins/zenoss/cmd/linux/netstat_rn.py

Cherry-picked pull/887
Cherry-picked pull/890
Cherry-picked pull/891

Please review branch feature/ZEN-16855

---

Products/DataCollector/plugins/zenoss/cmd/linux/ifconfig.py

Please review branch feature/ZEN-18378

---

Products/ZenModel/UserSettings.py

cherry-pick commit 21476bae8f82e1d0d43066c0cdb2112cc4eb2b5a

Fixes ZEN-17964.2

---

Products/ZenModel/ZenPack.py

Export all nested monitoring templates.

---

Products/ZenModel/ThresholdInstance.py

Fix missing events from custom threshold types.

---

Products/ZenModel/ThresholdInstance.py

Fixes ZEN-18555

---

Products/ZenModel/ZenPack.py

Fixes ZEN-18561

---

Products/ZenUI3/browser/backcompat.zcml

https://jira.zenoss.com/browse/ZEN-15389

ZEN-15389: User Enumeration via User Manager

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

https://jira.zenoss.com/browse/ZEN-15114

ZEN-15114: CSS Vulnerability in Event Detail Panel

---

Products/ZenModel/migrate/ChangeConInfoEngine.py
Products/ZenUtils/ZenCheckZenDS.py

https://jira.zenoss.com/browse/ZEN-17275
I had to port some of these changes as well: https://github.com/zenoss/pm-resmgr-4.2.4/commits/master/src/core/Products/ZenUtils/ZenCheckZenDS.py

ZEN-17275 (and ZEN-9267, ZEN-8926, ZEN-9357, ZEN-13994) - Account for non-standard zodb and zodb_session database names

---

Products/ZenUtils/zenpack.py

ZEN-18611: Add retry logic to _verifyZepRunning, so zenpack upgrades will work properly when ZEP startup is slow.

ZEN-18611: add retry logic to ZEP check.

---

Products/ZenUtils/zenpack.py

Please review branch feature/ZEN-18661

---

Products/ZenUtils/requestlogging/ZopeRequestLogger.py

ZEN-18071: Cherry-picking ZEN-15860 fix into support branch.
Feature/zen 15860

ZEN-18071: Merge pull request #668 from zenoss/feature/ZEN-15860

---

bin/zenpack

https://jira.zenoss.com/browse/ZEN-18685
https://github.com/zenoss/platform-build/pull/562/commit

ZEN-18685: do not include site /var/zenoss/ZenPacks during zenpack restore

---

Products/ZenUtils/zenpack.py

https://jira.zenoss.com/browse/ZEN-18858

ZEN-18858: Use egg name parser to figure out how to fix broken zenpacks

---

Products/ZenUtils/patches/pasmonkey.py

Security fix: https://jira.zenoss.com/browse/ZEN-15416

ZEN-15416: Plaintext Password Stored in Session on Server

---

Products/DataCollector/SnmpClient.py

Log all SNMP timeouts during modeling.

---

Products/ZenUtils/patches/pasmonkey.py

https://jira.zenoss.com/browse/ZEN-18967

ZEN-18967: Unable to login to the application after Migration

---

Products/ZenModel/migrate/templatizeCollectorEndpoints.py

Migrate syslog/zentrap endpoints for 5.1

---

Products/ZenUtils/zenpack.py

Original fix developed by jafcrocker--I tested it and am committing it.
I also fixed a misspelled error message.

ZEN-16599: Make 'zenpack --remove' delete svc def

---

Products/ZenUtils/celeryintegration/backend.py

Please review branch feature/ZEN-19203

---

Products/ZenModel/migrate/fixZopeHealthCheck.py

Add a service migration for the zproxy healthcheck of Zope

---

Products/DataCollector/ProcessCommandPlugin.py
Products/DataCollector/plugins/zenoss/snmp/HRSWRunMap.py
Products/ZenRRD/parsers/ps.py
Products/ZenRRD/zenprocess.py

ZEN-17907 Zenoss web UI Cannot handle process with random binary characters

ZEN-17907 Zenoss web UI Cannot handle process with random binary characters

---

Products/ZenModel/zenmib.py

cherry-pick commit 388190e9bbba75c4c19adc7b1ef235f1d74fac9e

Fixes ZEN-19331

---

Products/ZenModel/ZenPack.py

https://jira.zenoss.com/browse/ZEN-19575

Updating the /hub/collector path to reflect the new service definition

---

Products/ZenUI3/browser/eventconsole/columns.py

The select box lists available event classes and allows typing to narrow
the list.

Change event class filter into a select box

---

bin/monitored-datapoints
bin/zendiag.py

zendiag: Add monitored-datapoints script.

---

Products/ZenUtils/controlplane/data.py

This bug is an artifact of https://github.com/control-center/serviced/pull/1966

ZEN-19804: controlplane client handles new service status attribute

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/menus.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml

Looks OK to me - the isProjection properties are the only new things really

Fresh dump of xml + sql

---

Products/ZenCollector/daemon.py
Products/ZenUtils/DaemonStats.py
Products/ZenUtils/metricwriter.py
Products/ZenUtils/tests/test_metricwriter.py

Fix datapoint derivative calculation.

---

Products/DataCollector/SshClient.py
Products/ZenRRD/zencommand.py

DO NOT MERGE except to 5.0.7
Fixes https://jira.zenoss.com/browse/ZEN-19208

Zencommand tasks get stuck

---

bin/zendiag.py

Add callhome data to support bundle.

---

Products/Zuul/infos/metricserver.py

Cherry-picked 5206c59db0f7586b1778b7e09809aedc10dc270e

ZEN-19746 Ensure unique series names on multiple context graphs

---

Products/ZenModel/ZenPack.py

https://jira.zenoss.com/browse/ZEN-19939

ZEN-19939: Fix service paths to not include names

---

Products/ZenModel/ZenPack.py

https://jira.zenoss.com/browse/ZEN-19933

ZEN-19933: Replace references to /hub/collector with /zenoss-application/zenoss-collection/hub/collector

---

Products/DataCollector/CollectorClient.py
Products/DataCollector/SshClient.py

Raise appropriate error in clientFinished

---

bin/zenrun.d/patch.sh

Adds a few clauses zenrun's patch.sh to check that the patch and series
exist, and that there are any patches to rewind and then apply.
This should prevent apply-custom-patches from erroring out with the cryptic
message "No series file found".

Check preconditions in patch.sh before using quilt

---

Products/ZenReports/ReportMail.py

The reportmail command line tool doesn't need this parameter in the URL

ZEN-19426: Clean cache buster out of URL

---

bin/healthchecks/collectorredis/metrics
bin/healthchecks/redis/metrics

Port of #1104 to 5.1.x
Closes ZEN-20238

ZEN-20238 Update redis/collectorredis healthchecks

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/ZenUI3/browser/resources/js/zenoss/viewGraph.js
Products/Zuul/routers/__init__.py

(cherry picked from commit 08d69b4690c873f4bfde0e4c19309b36dfbc9d9e)

ZEN-20047: Improve usability of standalone graph links

---

Products/ZenModel/migrate/addQuiltInstallCommand.py
bin/zenrun.d/quilt.sh

https://jira.zenoss.com/browse/ZEN-19985

ZEN-19985: Quilt must be installable via serviced service run

---

bin/zendiag.py

(cherry picked from commit af20d0d1bf1581b8cf9b175d3637b2f3d789760e)

ZEN-20352: Use tempdir for support bundle generation

---

Products/DataCollector/ApplyDataMap.py

Decorators wrap functions, not function calls.
Fixes ZEN-19701.

Fix applyDataMap issue introduced by 1e76a1f4.

---

bin/zenrun.d/patch.sh

Port of #1097 to support/5.1.x
Closes https://jira.zenoss.com/browse/ZEN-20180

Check prerequisites in apply-custom-patches

---

Products/ZenModel/migrate/enableCommitonUpgrade.py

Port of ZEN-20119 fix to 5.1
Fixes ZEN-20198

ZEN-20198 Zope upgrade CommitOnSuccess=True

---

bin/zendiag.py

(cherry picked from commit 8295d2c6f79e9a29b2c048ed718434c84090ffb1)

ZEN-20433: Do not log exceptions in zendiag subprocesses

---

Products/ZenModel/ZenossInfo.py

(cherry picked from commit b50cf2c23aea16cf327adc679f873557d043d1a0)

ZEN-20260: Display CC version in Zenoss

---

Products/ZenModel/migrate/addQuiltInstallCommand.py
bin/zenrun.d/quilt.sh

Please review branch feature/ZEN-20222

---

bin/zenfunctions

Please review branch feature/ZEN-20304

---

Products/Zuul/__init__.py

Reduce logging from requests package.

---

Products/Zuul/facades/devicefacade.py

Fixes [ZEN-19596](https://jira.zenoss.com/browse/ZEN-19596)

Adds support for Microsoft Windows/Cluster device subclasses 

---

Products/ZenCollector/daemon.py
Products/ZenHub/metricpublisher/publisher.py
Products/ZenRRD/zencommand.py
Products/ZenRRD/zenperfsnmp.py
Products/ZenUtils/metricwriter.py

Fixes ZEN-20005

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js
Products/Zuul/routers/zep.py

See commit messages for more detail. The changes in the two commits are
related, but independent.

Two fixes for events on infrastructure page.

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

fixing https://jira.zenoss.com/browse/ZEN-18627

tell graphPanel to use more specific title if available

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

For "Add a Single Device" dialog box, change title name of "Name or IP" to "Hostname or IP address"

Please review branch feature/ZEN-20428

---

Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js

Production States and Priorities are now sorted in descending numeric order rather than alphabetically.

Please review branch feature/ZEN-20159

---

Products/ZenUtils/ZenDaemon.py

cherry-pick pull-request #1152

Fixes ZEN-20281-3

---

Products/ZenUI3/tooltips/interfaces.py
Products/ZenUI3/tooltips/tooltips.py

Add a utility hook for overriding tooltips

ZEN-20672: Hooks for adding tooltips/help

---

Products/ZenModel/RRDTemplate.py
Products/ZenUI3/browser/resources/js/zenoss/TemplateTreePanel.js

provide more uniqifying path to templates

ZEN-20773: Foreport pull request #1183 from zenoss/feature/ZEN-20677

---

Products/ZenModel/tests/testXmlEdges.py
Products/ZenUtils/NetworkTree.py
Products/ZenUtils/Utils.py

port from 4.2.5:
https://github.com/zenoss/4.2.5-RPS/pull/641/files

ZEN-14768: Blank view when navigating to nodes on network map

---

Products/ZenHub/zenhub.py

Please review branch feature/ZEN-20808

---

Products/ZenUtils/CmdBase.py

Backport of #1207 for ZEN-20505

Changed default log level to Warn

---

Products/ZenUI3/browser/eventconsole/columns.py

Please review branch feature/ZEN-20902

---

Products/ZenUtils/ZenPackInstallFilter.py
Products/ZenUtils/configure.zcml
Products/ZenUtils/zenpack.py

(cherry picked from commit 9d38cf8d49626afec08ecafc556f30515a90b292)

ZEN-18830: Add utility for filtering zp installs

---

Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js

Backport of earlier merge to develop

Production state and  Priority are now sorted by value in DESC order.

---

Products/ZenUI3/browser/resources/js/zenoss/ExtOverrides.js

Backport of https://github.com/zenoss/zenoss-prodbin/pull/1178

Please review branch feature/ZEN-20839

---

Products/Zuul/infos/device.py

For devices modeled with SNMP use snmp status to determine the devices status.

Please review branch feature/ZEN-20499

---

Products/ZenModel/Device.py

cherry-pick pull-request #1226

Fixes ZEN-20922

---

Products/ZenModel/migrate/addTriggerPermsToZenManager.py

https://jira.zenoss.com/browse/ZEN-20832

Grant trigger manager permissions to zen manager role

---

Products/ZenUtils/metricwriter.py

Please review branch feature/ZEN-19002

---

Products/ZenModel/migrate/zminionViaSupervisord.py

ZEN-20670 Run zminion via supervisord

---

Products/ZenModel/configure.zcml

Please review branch feature/ZEN-20969

---

bin/zenrun

Cherry-picked #1262
Fixes [ZEN-19749](https://jira.zenoss.com/browse/ZEN-19749)

Please review branch feature/ZEN-19749

---

Products/ZenUI3/browser/eventconsole/columns.py

Please review branch feature/ZEN-21086

---

Products/ZenModel/migrate/addZenMailHealthCheck.py

Please review branch feature/ZEN-21087

---

Products/ZenModel/migrate/README.md

Added a link to the instructions for running a full migration manually.

Include link to running integration tests

---

Products/ZenModel/BasicDataSource.py

v3 arguments were missing from the snmp commands.  When snmp is configured for v3, the required arguments are added to the command (security name, level, security types).

Added SNMP v3 args to the DataSource command execution

---

Products/Zuul/routers/device.py

Port: https://github.com/zenoss/4.2.5-RPS/pull/558

ZEN-18106: Possible issue with setting attributes on device or organizer

---

Products/ZenEvents/MailProcessor.py

Port: https://github.com/zenoss/4.2.5-RPS/pull/535/files

ZEN-10461: ZenMail does not support Content-Transfer-Encoding Base64

---

Products/ZenUI3/browser/resources/js/zenoss/MIBs.js
Products/ZenUI3/browser/resources/js/zenoss/daemons/view/daemons/Details.js
Products/ZenUI3/browser/resources/js/zenoss/daemons/view/daemons/List.js
Products/ZenUI3/browser/resources/js/zenoss/joblist.js
Products/Zuul/routers/application.py
Products/Zuul/routers/jobs.py
Products/Zuul/routers/mibs.py

Please review branch feature/ZEN-21097

---

Products/ZenUtils/ZenCheckZenDS.py

This inculude the following changes:
- Use argparse instead of optparse
- Add handler to log into file
- Add a lock on process run
- Use consistent name for logging
Ported from: https://github.com/zenoss/4.2.5-RPS/pull/666

ZEN-21162: ZenCheckZenDS.py imporvements

---

Products/ZenModel/migrate/tests/test_fixZopeHealthCheck.py
Products/ZenModel/migrate/tests/zenoss-core-5.0.6_193-fixZopeHealthCheck.json

Unit test for [fixZopeHealthCheck.py](https://github.com/zenoss/zenoss-prodbin/blob/develop/Products/ZenModel/migrate/fixZopeHealthCheck.py)

Add test for fixZopeHealthCheck migration

---

Products/ZenModel/migrate/tests/test_fixZopeHealthCheck.py
Products/ZenModel/migrate/tests/zenoss-core-5.0.6_193-fixZopeHealthCheck.json

Please review branch feature/TA27312-5.1.x

---

Products/ZenUI3/browser/eventconsole/columns.py

Please review branch feature/ZEN-16252

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/view/AddUserView.js

Please review branch feature/ZEN-21226

---

Products/ZenModel/skins/zenmodel/dialog_addUser.pt
Products/ZenUI3/browser/resources/css/zenoss.css

Please review branch feature/ZEN-11737

---

Products/ZenModel/BasicDataSource.py

Please review branch feature/ZEN-21143

---

Products/ZenModel/GraphDefinition.py
Products/ZenUI3/browser/resources/css/zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js
Products/Zuul/infos/metricserver.py

Cherry-Picked From: 9f80b02dcd322c30eb7c0dc4739249ca48bc02e2
(preserve backwards compatablity with zenpack graph definitions
but still allow people to specify the dimensions of a graph)

ZEN-21209: Allow to change graph size

---

Products/ZenModel/migrate/updateZeneventserverHealthCheck.py

support/5.1.x had the tests but not the migration script itself.

Adds updateZeneventserverHealthCheck service migration

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml

Minor updates to ZenModel/data xml and zodb dump to fix zendmd version.
Previously it was reporting version 5.11.12; it should now report 5.1.1.

ZEN-21181 zendmd version is wrong

---

Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

Please review branch feature/ZEN-21287

---

Products/ZenModel/MaintenanceWindow.py

Please review branch feature/ZEN-21245

---

Products/ZenUtils/zenpack.py

ZEN-21297 Link installing zenpacks by path fails

---

Products/ZenModel/migrate/addTriggerPermsToZenManager.py

Ported change fro 5.1.x to develop
Fixes [ZEN-20832](https://jira.zenoss.com/browse/ZEN-20832)

Ported change fro 5.1.x to develop

---

Products/ZenModel/migrate/addTriggerPermsToZenManager.py

Migrations in the branch are currently using 5.1.70.  Changed version so that this migration will run and fix https://jira.zenoss.com/browse/ZEN-21302

moved migration version to the latest version so that it will run

---

bin/zenrun.d/upgrade.sh

Port of #1343 to support/5.1.x

ZEN-21313 zeneventerserver-create-db in upgrade.sh

---

Products/ZenUI3/browser/eventconsole/columns.py

Cherry-picked 67400fee2bf3dbc4d7143faccd8b2845632e8efa

Please review branch feature/ZEN-21316

---

Products/ZenEvents/Schedule.py

cherry-pick commit 20843ccbed03531878d88d647bb87cf6ce476541

Fixes ZEN-21322

---

Products/ZenUI3/browser/eventconsole/columns.py

Changing the help text of the First Seen and Last Seen columns in the event console.

Please review branch feature/ZEN-11521

---

bin/zenfunctions

Fix for typo in usages.  
https://jira.zenoss.com/browse/ZEN-9134

Please review branch feature/ZEN-9134

---

Products/ZenUI3/browser/resources/js/codemirror/codemirror.css
Products/ZenUI3/browser/resources/js/codemirror/codemirror.js
Products/ZenUI3/browser/resources/js/codemirror/mode/meta.js
Products/ZenUI3/browser/resources/js/codemirror/mode/python/LICENSE.txt
Products/ZenUI3/browser/resources/js/codemirror/mode/python/index.html
Products/ZenUI3/browser/resources/js/codemirror/mode/python/python.js

https://jira.zenoss.com/browse/ZEN-21327

upgrade CodeMirror to v5.9.0

---

bin/zenrun.d/upgrade.sh

Port of #1363 to support/5.1.x

CC-1690 Removed zodb as target of upgrade.sh

---

Products/ZenEvents/MailProcessor.py

Please review branch feature/ZEN-21150

---

Products/ZenModel/migrate/README.md
Products/ZenModel/migrate/addTriggerPermsToZenManager.py
Products/ZenModel/migrate/switchLoggingLevel.py

(cherry picked from commit c785668b89b32d1b7bb08cac4985b94120ee1b52)

ZEN-21434: Correct versions of migrate scripts

---

Products/ZenModel/migrate/addZenMailHealthCheck.py
Products/ZenModel/migrate/makeMemcachedUpdates.py
Products/ZenModel/migrate/switchLoggingLevel.py
Products/ZenModel/migrate/updateOpenTSDBConfigs.py
Products/ZenModel/migrate/updateZeneventserverHealthCheck.py
Products/ZenModel/migrate/updateZookeeperConfigs.py
Products/ZenModel/migrate/updateZopeThreadsCount.py

Port of #1376 to support/5.1.x

ZEN-20863 More defensive migration scripts

---

Products/ZenUtils/zenpack.py

ZEN-21297 installing zenpacks by path fails for certain paths

---

Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-zminionViaSupervisord.json
Products/ZenModel/migrate/zminionViaSupervisord.py

The original fix (https://github.com/zenoss/zenoss-prodbin/pull/1162) was incomplete because it referenced new config files.  This PR includes those config files.

ZEN-20646: Add config files to zminion svc

---

Products/ZenUtils/controlplane/application.py
Products/ZenUtils/controlplane/client.py
Products/ZenUtils/controlplane/data.py
Products/ZenUtils/controlplane/tests/test_application.py
Products/Zuul/facades/monitor.py
Products/Zuul/routers/monitor.py

cherry-pick pull-request #1405

Fixes ZEN-21546

---

Products/ZenUI3/browser/resources/js/zenoss/triggers.js
Products/Zuul/facades/triggersfacade.py

Please review branch feature/ZEN-21133

---

Products/ZenModel/migrate/AddEndpointsToZenjobs.py
Products/ZenModel/migrate/addCentralQueryGraphConfigs.py
Products/ZenModel/migrate/addMemcachedService.py
Products/ZenModel/migrate/addQuiltInstallCommand.py
Products/ZenModel/migrate/addZenMailHealthCheck.py
Products/ZenModel/migrate/collectorDaemonsImportZproxy.py
Products/ZenModel/migrate/convertRunsToCommands.py
Products/ZenModel/migrate/duallogchange.py
Products/ZenModel/migrate/enableCommitonUpgrade.py
Products/ZenModel/migrate/fixZopeHealthCheck.py
Products/ZenModel/migrate/makeMemcachedUpdates.py
Products/ZenModel/migrate/removeEmptyGraphdata.py
Products/ZenModel/migrate/switchLoggingLevel.py
Products/ZenModel/migrate/templatizeCollectorEndpoints.py
Products/ZenModel/migrate/updateHBaseForNetcat.py
Products/ZenModel/migrate/updateOpenTSDBConfigs.py
Products/ZenModel/migrate/updateZeneventserverHealthCheck.py
Products/ZenModel/migrate/updateZentrapConfigs.py
Products/ZenModel/migrate/updateZookeeperConfigs.py
Products/ZenModel/migrate/updateZopeThreadsCount.py
Products/ZenModel/migrate/useBeakerInZope.py
Products/ZenModel/migrate/zenmodelerWorkers.py
Products/ZenModel/migrate/zminionViaSupervisord.py

Port of #1409 to support/5.1.x

ZEN-21569 Verbose logging during migrations

---

Products/ZenUI3/browser/resources/js/zenoss/process.js

https://jira.zenoss.com/browse/ZEN-21562

make processes panels vertically resizable

---

Products/ZenModel/tests/testXmlEdges.py
Products/ZenUtils/NetworkTree.py
Products/ZenUtils/Utils.py

Cherry-Picked From: 76d89b41f5dc970c60a14cd7e532e00dba3f7da3

ZEN-16676: Fix blank view when navigating to nodes on network map

---

Products/ZenModel/migrate/addTriggerPermsToZenManager.py

Port of the [ZEN-20832](https://jira.zenoss.com/browse/ZEN-20832) to 5.0.x
Couldn't be cherry-picked as there are changes to ZODB dump.

ZEN-21387: ZenManager cannot create trigger or notification

---

Products/ZenUtils/ZenPackCmd.py

cherry-pick pull-request #1419

Fixes ZEN-21591

---

Products/ZenUI3/browser/eventconsole/columns.py
Products/ZenUI3/browser/eventconsole/grid.py
Products/ZenUI3/browser/resources/css/zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js
Products/ZenUI3/browser/resources/js/zenoss/Renderers.js
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js
Products/Zuul/facades/zepfacade.py
Products/Zuul/routers/zep.py

Add "Status Text" column which shows event status icon and event status text to help distinguish various closed statuses.

add eventStateText column

---

Products/ZenModel/migrate/Migrate.py

Port of #1425 to support/5.1.x

ZEN-21569 Verbose logging during service migration

---

Products/DataCollector/zendisc.py

Please review branch feature/ZEN-21620

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AddUserController.js

https://jira.zenoss.com/browse/ZEN-21664

make enter keypress submit user form in quickstart wizard

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/ComponentPanel.js

https://jira.zenoss.com/browse/ZEN-13045

paginate component grid

---

Products/ZenEvents/Schedule.py
Products/ZenEvents/zenactiond.py
Products/ZenModel/MaintenanceWindow.py
Products/ZenModel/NotificationSubscriptionWindow.py

Cherry-picked pull/1021
Cherry-picked pull/1191

Please review branch feature/ZEN-21062

---

Products/ZenWidgets/skins/zenui/dialog_addZenPack.pt

(cherry picked from commit 54f459ea4b1b9743d6c899e359bfcebf1c1d1b0c)

ZEN-21758: Correct zenpack create modal text

---

Products/ZenModel/actions.py

cherry-pick pull-request #1449

Fixes ZEN-21739

---

Products/ZenModel/tests/testFileSystem.py
Products/ZenModel/tests/testHardDisk.py
Products/ZenModel/tests/testWinService.py

Fixes for the following unit tests (ZEN-21784):
- testGets (Products.ZenModel.tests.testFileSystem.TestFileSystem)
- testGets (Products.ZenModel.tests.testHardDisk.TestHardDisk)
- testGets (Products.ZenModel.tests.testWinService.testWinService)

Please review branch feature/ZEN-21784

---

Products/ZenRelations/ZenPropertyManager.py
Products/ZenRelations/tests/testZenPropertyManager.py

Fix for ZEN-21787, test_setPropertySelect failing in Products.ZenRelations.

Please review branch feature/ZEN-21787

---

Products/ZenUtils/controlplane/tests/test_application.py

Fix for ZEN-21795.  Adding class for mocking back in.

Please review branch feature/ZEN-21795

---

Products/ZenUtils/controlplane/__init__.py
Products/ZenUtils/controlplane/client.py

Please review branch feature/CC-1814.port

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js

Ported-From: https://github.com/zenoss/pm-resmgr-4.2.4/pull/875

ZEN-21838: Make columns Group, System, and Event sortable

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js

Cherry-Picked From: 5cf80df4284f0e73bf8a86608cffec10e894495f

ZEN-21843: Make columns Group, System, and Event sortable

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js

https://jira.zenoss.com/browse/ZEN-21868

add summary to list of filter params by url

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

Additional logic to prevent error "no object firstChild" browser console messages

fixes ZEN-21822

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js

Cherry-Pcked From: 5cf80df4284f0e73bf8a86608cffec10e894495f

ZEN-21842: Make columns Group, System, and Event sortable

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

Please review branch feature/ZEN-21822.port

---

Products/ZenModel/ZenossInfo.py

Please review branch feature/ZEN-21909

---

Products/ZenModel/RRDDataSource.py

Cherry-picked 089e3b6d2f7b570be29c66bfaf2d9934e8c114f6

Please review branch feature/ZEN-21917

---

Products/ZenModel/RRDDataSource.py

Cherry-picked 089e3b6d2f7b570be29c66bfaf2d9934e8c114f6

Please review branch feature/ZEN-21916

---

Products/ZenModel/migrate/tests/common.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-addMemcachedService.json

Please review branch feature/ZEN-21922

---

Products/ZenUtils/controlplane/tests/test_application.py

Please review branch feature/ZEN-21921

---

.clocignore

Excluding low hanging fruit of 3rd party directories and files from sloc (source lines of code) scanning

SLOC exclude file

---

bin/zenfunctions

Please review branch feature/ZEN-21709

---

Products/ZenUI3/browser/templates/quickstart.pt

Addresses ZEN-21997 (5.2 maintenance ticket for ZEN-21964)

Use current year in copyright

---

Products/ZenUtils/controlplane/__init__.py

Fixes ZEN-22005 - Connection refused flare msg in Advanced->Control Center tab

---

Products/ZenModel/data/devices.xml

Port of #1505 to support/5.1.x

ZEN-22048 Syntax error in ethernetCsmacd_64 threshold

---

Products/Zuul/infos/metricserver.py

Fixes https://jira.zenoss.com/browse/ZEN-22056

check context for RRDDataPoint if needed

---

Products/ZenModel/GraphDefinition.py
Products/ZenUI3/browser/resources/css/zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js
Products/Zuul/infos/metricserver.py

The ComponentGraphs page renders incorrectly with the change being reverted.  Could be something that was missed of the cherry-picked code depended on.

Revert ZEN-21209

---

Products/DataCollector/SnmpClient.py

Handle AttributeError from attempting to close connection after auth failure

---

Products/ZenModel/Device.py

Making this change in order to respond to pings even though Device is not
modeled yet and not under /Ping Device Class

ZEN-19385:Device Status Unknown

---

Products/ZenModel/actions.py

Fixes https://jira.zenoss.com/browse/ZEN-15367

ensure actions.json actions None fields dont squash defaults

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

Fixes ZEN-22239 "User cannot create maintenance window despite ZenManager privs to the organizer"

---

Products/Zuul/infos/device.py

…e devices status."
This reverts commit ff514e434d9db97e4c90a61cace72b0ba2d4de0d.

Revert "For devices modeled with SNMP use SNMP status to determine their status"

---

Products/ZenModel/Commandable.py
Products/ZenModel/UserSettings.py
Products/ZenModel/ZenModelBase.py
Products/ZenModel/ZenPackManager.py
Products/ZenModel/dtml/addGroup.dtml
Products/ZenModel/dtml/addUserSettings.dtml
Products/ZenModel/skins/zenmodel/administeredDevices.pt
Products/ZenModel/skins/zenmodel/dialog_addAdministeredDevice.pt
Products/ZenModel/skins/zenmodel/dialog_addAdministeredDeviceClass.pt
Products/ZenModel/skins/zenmodel/dialog_addAdministeredGroup.pt
Products/ZenModel/skins/zenmodel/dialog_addAdministeredLocation.pt
Products/ZenModel/skins/zenmodel/dialog_addAdministeredSystem.pt
Products/ZenModel/skins/zenmodel/dialog_addUser.pt
Products/ZenModel/skins/zenmodel/dialog_addUserCommand.pt
Products/ZenModel/skins/zenmodel/dialog_addUserGroup.pt
Products/ZenModel/skins/zenmodel/dialog_addUserToAGroup.pt
Products/ZenModel/skins/zenmodel/dialog_addUserToGroup.pt
Products/ZenModel/skins/zenmodel/dialog_deleteUserGroups.pt
Products/ZenModel/skins/zenmodel/dialog_deleteUsers.pt
Products/ZenModel/skins/zenmodel/dialog_deleteUsersFromGroup.pt
Products/ZenModel/skins/zenmodel/dialog_installZenPack.pt
Products/ZenModel/skins/zenmodel/dialog_saveUserSettings.pt
Products/ZenModel/skins/zenmodel/editUserSettings.pt
Products/ZenUtils/configure.zcml
Products/ZenUtils/csrf.py
Products/ZenUtils/extdirect/zope/router.py
Products/ZenUtils/patches/pasmonkey.py
Products/ZenWidgets/browser/quickstart/templates/createuser.pt
Products/ZenWidgets/browser/quickstart/userViews.py
Products/ZenWidgets/skins/zenui/dialog_removeZenPacks.pt

Please review branch feature/ZEN-22312

---

Products/Jobber/manager.py
Products/ZenEvents/EventClass.py
Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenModel/IpNetwork.py
Products/ZenModel/Location.py
Products/ZenModel/Manufacturer.py
Products/ZenModel/ManufacturerRoot.py
Products/ZenModel/MibOrganizer.py
Products/ZenModel/MonitorClass.py
Products/ZenModel/OSProcessOrganizer.py
Products/ZenModel/ServiceOrganizer.py
Products/ZenModel/UserSettings.py
Products/ZenModel/ZDeviceLoader.py
Products/ZenModel/ZenossSecurity.py

[Jira](https://jira.zenoss.com/browse/ZEN-15407)

ZEN-15407: Protect models methods

---

Products/Jobber/manager.py
Products/ZenEvents/EventClass.py
Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenModel/IpNetwork.py
Products/ZenModel/Location.py
Products/ZenModel/Manufacturer.py
Products/ZenModel/ManufacturerRoot.py
Products/ZenModel/MibOrganizer.py
Products/ZenModel/MonitorClass.py
Products/ZenModel/OSProcessOrganizer.py
Products/ZenModel/ServiceOrganizer.py
Products/ZenModel/UserSettings.py
Products/ZenModel/ZDeviceLoader.py
Products/ZenModel/ZenossSecurity.py

[Jira](https://jira.zenoss.com/browse/ZEN-18099)
Port of zenoss/zenoss-prodbin#1554

ZEN-18099: Protect models methods

---

Products/ZenModel/DataRoot.py
Products/ZenModel/Device.py
Products/ZenModel/IpNetwork.py
Products/ZenModel/Organizer.py
Products/ZenModel/ZenModelBase.py
Products/ZenModel/skins/zenmodel/Dashboard.pt
Products/ZenUtils/Utils.py

Please review branch feature/ZEN-18100

---

Products/ZenModel/migrate/tests/common.py

adding difflib output to better pinpoint problem test failures

CC-2032 Enhanced DIFF for string comparison failures in unit tests

---

Products/ZenUtils/extdirect/zope/router.py

Please review branch feature/ZEN-22695.port

---

Products/DataCollector/plugins/zenoss/snmp/InterfaceMap.py

Fixes ZEN-22732
https://jira.zenoss.com/browse/ZEN-22732
Happens on certain firmware versions. Reproduced using snmposter
Tested using attached snmpwalks from JIRA

ifindex could be missing, use row index

---

Products/DataCollector/plugins/zenoss/snmp/InterfaceMap.py

https://jira.zenoss.com/browse/ZEN-22732
Happens on certain firmware versions. Reproduced using snmposter
Tested using attached snmpwalks from JIRA

Fixes ZEN-22732

---

Products/ZenUtils/zenpack.py

Port of #1617 to support/5.1.x

ZEN-22820 Some Zenpacks missing in UCSPM 2.0.1 upgrade

---

Products/ZenUtils/zenpack.py

Port of #1621 to support/5.1.x

ZEN-22820 Fix JSON load and stop swallowing exceptions

---

Products/ZenRRD/tests/testzenprocess.py
Products/ZenRRD/zenprocess.py

Please review branch feature/ZEN-16972

---

Products/Zuul/routers/zep.py

port: https://github.com/zenoss/4.2.5-RPS/pull/733/files

ZEN-22811: User with restricted access unable bulk-close events

---

Products/ZenHub/services/DiscoverService.py

port from 425 https://github.com/zenoss/4.2.5-RPS/pull/734

ZEN-22782 zendisc changes the production state of existing devices

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

fixes problem: chart is squished and overlapped by top text.

ZEN-22812 portlet chart renders incorrectly

---

Products/Zuul/routers/zep.py

Please review branch feature/ZEN-22952

---

Products/ZenHub/services/DiscoverService.py

Cherry-picked 2e9e59949b29f98ca6dcd728b91faea913fe8219

Please review branch feature/ZEN-22943

---

Products/Jobber/manager.py

Cherry-picked 7fbb01276589083d17148941a112b52fa80cd896

Please review branch feature/ZEN-22954

---

Products/ZenUI3/browser/resources/js/zenoss/form/configPropertyPanel.js
Products/ZenUI3/browser/resources/js/zenoss/itinfrastructure.js

ZEN-22953 zCommandPassword on 'Add Device' dialogue allows autocomplete

---

Products/ZenModel/Device.py

Making this change in order to respond to pings even though Device is not
modeled yet and not under /Ping Device Class

ZEN-21545:Device Status Unknown

---

Products/ZenModel/migrate/convertRunsToCommands.py

Fixed the constructor of some test services for convertRunsToCommands

Fix Description field in convertRunsToCommands

---

Products/ZenModel/migrate/convertRunsToCommands.py

Port of #1651 to support/5.1.x

Fix command and commit fields in convertRunsToCommands

---

Products/ZenModel/data/default_service.json

Please review branch feature/ZEN-22869

---

bin/quiesce-rabbitmq.sh

ZEN-23223 Pausing RabbitMQ may not be working properly

---

Products/ZenModel/ValueChangeThreshold.py
Products/ZenModel/tests/testValueChangeThreshold.py
Products/ZenUtils/Map.py

Please review branch feature/ZEN-14671

---

Products/ZenUI3/security/security.py

Please review branch feature/ZEN-23021

---

Products/ZenModel/migrate/retryZopeHealthCheck.py

[Jira](https://jira.zenoss.com/browse/ZEN-23053)

ZEN-23053: Zope 'answering' health check retries on failure

---

makefile

Please review branch feature/ZEN-23381

---

Products/ZenUI3/browser/pages.py

Don't include port when setting the cookie's domain

---

Products/ZenUtils/extdirect/zope/router.py

This is a port from https://github.com/zenoss/4.2.5-RPS/pull/741.

ZEN-23488 Fix incorrect Content-Type checking

---

Products/ZenUtils/extdirect/zope/router.py

Please review branch feature/ZEN-23487

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

Please review branch feature/ZEN-23457

---

Products/ZenModel/Device.py
Products/ZenModel/DeviceClass.py
Products/ZenModel/tests/testDevice.py
Products/ZenModel/tests/testDeviceClass.py

(cherry picked from commit b60b6f77d3c1fe8a7e3d00b3be67ddf46ad3f889)

revert ZEN-23447

---

Products/ZenModel/ZenPackLoader.py
Products/ZenUtils/ZenPackCmd.py

Added calling install_bin_files method if a zenpack has one.

ZEN-23180: added a link creation to ZPLBin

---

Products/DataCollector/plugins/zenoss/cmd/linux/netstat_rn.py

Valid mask attribute for IpRouteEntry is routemask.

Fixes ZEN-23173.

---

Products/ZenModel/ZenPackLoader.py

Please review branch feature/ZEN-23699

---

Products/ZenWidgets/ZenTableManager.py

Custom device reports would not sort if the columns were tales
expressions.  Also, the href in the table header was not encoding
parameters correctly which was an issue for columns that were tales
expressions.

Adds sorting to custom device reports

---

Products/ZenRelations/ZenPropertyManager.py

This is the port of zenoss/4.2.5-RPS#754

ZEN-23195 raise ValueError in case of duplicate mapping

---

Products/ZenHub/zenhub.py

Reverts zenoss/zenoss-prodbin#1734

Revert "ZEN-23154: ZenHub Main Process Consumes 100% CPU if Workers are Busy"

---

bin/zenossdbpack

Cherry-picked 39c69d1db77cd8e8281e55a5d2d08d07befe5c0b

Please review branch feature/ZEN-22889

---

Products/ZenUI3/browser/resources/js/zenoss/quickstart/controller/AutoDiscoveryController.js

Cherry-picked 26ca641801a9d32d69c83261d302e5c9122048d4

Please review branch feature/ZEN-23755

---

bin/healthchecks/metrics_answering
bin/healthchecks/query_answering

Please review branch feature/ZEN-23867

---

bin/zenpass

Please review branch feature/ZEN-23494

---

Products/ZenHub/zenhub.py

Please review branch feature/ZEN-23545

---

Products/ZenModel/RRDTemplate.py

Please review branch feature/ZEN-23847

---

Products/ZenUtils/MetricServiceRequest.py

Please review branch feature/ZEN-23841

---

Products/Zuul/routers/zep.py

This is the port from zenoss/zenoss-prodbin#1735

ZEN-23033 User with no global role can see devices in dashboard

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceOverviewPanel.js
Products/Zuul/routers/device.py

This is the port from zenoss/zenoss-prodbin#1710

ZEN-5940 ZenOperator role to change Production state Changes

---

Products/ZenRelations/ZenPropertyManager.py

This is the port from zenoss/zenoss-prodbin#1733

ZEN-23544 raise ValueError in case of duplicate mapping

---

Products/ZenUI3/browser/resources/js/zenoss/EventPanels.js
Products/Zuul/routers/zep.py

Cherry-picked e7195e057b6f3b9c0f4de3211d9c12efe1d93826

Please review branch feature/ZEN-23745

---

Products/ZenUI3/browser/eventconsole/columns.py
Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js
Products/Zuul/facades/zepfacade.py
Products/Zuul/routers/zep.py
bin/zensendevent

(cherry picked from commit a01d2b6ebdc625660298482c4668d7a3816b05a1)

fixes ZEN-23471: Date range filtering not working in 5.x

---

Products/ZenReports/plugins/monitoredcomponents.py

This is the port from zenoss/zenoss-prodbin#1759

ZEN-23992 All monitored components report cause increased memory usage

---

Products/ZenUI3/browser/resources/js/zenoss/MIBs.js
Products/Zuul/routers/mibs.py

Cherry-picked 2d25a61190fbc82ed75277a2a4fa00a8522a279b
Cherry-picked d995386ae476c95df43015a30b84580b0595721e

Please review branch feature/ZEN-23754

---

javascript.mk
makefile

https://jira.zenoss.com/browse/ZEN-23963

Add javascript build

---

Products/ZenRelations/ZenPropertyManager.py

Reverts zenoss/zenoss-prodbin#1751

Revert "ZEN-23544 raise ValueError in case of duplicate mapping"

---

Products/ZenUI3/browser/resources/js/zenoss/ComponentPanel.js

ZEN-24173 port for deep-linking into paginated component tables

---

Products/ZenModel/migrate/tests/common.py
Products/ZenModel/migrate/tests/test_common.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-addMemcachedService.json
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-addZepEndpointToZeneventd.json
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-importMemcachedInZauth.json
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-testCollectorDaemonsImportZproxy.json

Fixes [ZEN-24217](https://jira.zenoss.com/browse/ZEN-24217)

Eliminate false negatives from service migration unit testing framework

---

Products/ZenUI3/browser/eventconsole/columns.py
Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js
Products/Zuul/facades/zepfacade.py
Products/Zuul/routers/zep.py
bin/zensendevent

ZEN-23418: revert old fix

---

Products/Zuul/infos/metricserver.py

Reverts zenoss/zenoss-prodbin#1784

Revert "ZEN-23895: Multi Graph Reports Not showing Graph Group Name in Title"

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

this is port from https://github.com/zenoss/4.2.5-RPS/pull/757

ZEN-24107: increase opacity of disabled elements.

---

Products/ZenCallHome/HostData.py
Products/ZenCallHome/VersionHistory.py
Products/ZenCallHome/ZenossAppData.py
Products/ZenCallHome/__init__.py
Products/ZenCallHome/callhome.py
Products/ZenCallHome/tests/testCallHomeGeneration.py
Products/ZenCallHome/tests/testVersionHistory.py
Products/ZenCallHome/transport/__init__.py
Products/ZenCallHome/transport/crypt/__init__.py
Products/ZenCallHome/transport/cycler.py
Products/ZenCallHome/transport/interfaces.py
Products/ZenCallHome/transport/methods/browserjs.py
Products/ZenCallHome/transport/methods/directpost.py
Products/ZenCallHome/transport/methods/versioncheck.py

The actual change is pretty minor. However I also formatted everything correctly which makes up the majority of the "changes". The only real changes are in ZenCallHome/transport/__init__:CallHome.get_payload, ZenCallHome/transport/method/browserjs.py and the tests (specifically testCallHomeGeneration)

ZEN-24270 Add send time to callhome payload

---

Products/ZenModel/migrate/beakerHttpOnly.py

Fixes https://jira.zenoss.com/browse/ZEN-24248

Fix BeakerHTTPOnly injection and exit if not found

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js
Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassConsole.js

Fixin https://jira.zenoss.com/browse/ZEN-23812

htmlescape text and description for nodes in tree panels

---

Products/Zuul/infos/metricserver.py

This is port from : https://github.com/zenoss/zenoss-prodbin/pull/1796

ZEN-24235: add group name to title in multi graph reports

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

This is port from : https://github.com/zenoss/4.2.5-RPS/pull/757

ZEN-24108: increase opacity of disabled elements.

---

Products/ZenUI3/browser/eventconsole/export.py

port from https://github.com/zenoss/zenoss-prodbin/pull/1790/files

ZEN-24271: event export to csv information overload

---

Products/ZenRelations/ZenPropertyManager.py

Please review branch feature/ZEN-23544-2

---

Products/ZenModel/UserSettings.py

Cherry-picked b100f05050cc7e6ca7df87b5d70cc0aa16b6dded

Please review branch feature/ZEN-24529

---

Products/ZenModel/migrate/beakerHttpOnly.py

Do not merge until UCS202 is released.

Fix migration version

---

Products/ZenCollector/interfaces.py
Products/ZenCollector/scheduler.py
Products/ZenRRD/zencommand.py

(cherry picked from commit 03911f2833f9522f13692e637aae62269cc87ba2)

fixes ZEN-22769: working on resume now

---

bin/healthchecks/metrics_answering
bin/healthchecks/query_answering

This is port from: https://github.com/zenoss/zenoss-prodbin/pull/1547

ZEN-23867: add new healthchecks

---

Products/ZenUtils/MultiPathIndex.py

This is port from : https://github.com/zenoss/zenoss-prodbin/pull/1620

ZEN-24331: use sets

---

Products/ZenCallHome/HostData.py
Products/ZenCallHome/VersionHistory.py
Products/ZenCallHome/ZenossAppData.py
Products/ZenCallHome/__init__.py
Products/ZenCallHome/callhome.py
Products/ZenCallHome/configure.zcml
Products/ZenCallHome/tests/testCallHomeGeneration.py
Products/ZenCallHome/tests/testVersionHistory.py
Products/ZenCallHome/transport/__init__.py
Products/ZenCallHome/transport/crypt/__init__.py
Products/ZenCallHome/transport/cycler.py
Products/ZenCallHome/transport/interfaces.py
Products/ZenCallHome/transport/methods/browserjs.py
Products/ZenCallHome/transport/methods/directpost.py
Products/ZenCallHome/transport/methods/versioncheck.py
bin/runtests

Port of: #1786 #1788 #1789 #1799 #1818

Zen 24260 Callhome fixes

---

Products/ZenUtils/controlplane/client.py

This fix tightens up the URLError handling by matching the error code instead of the string representation of the error.  It also handle the case where the reset occurs while getting the response, in which case a socket.error is thrown instead of URLError.
Fixes [ZEN-24636](https://jira.zenoss.com/browse/ZEN-24363)

Handle connection reset during getresponse

---

Products/DataCollector/SshClient.py

Reverts zenoss/zenoss-prodbin#1846

Revert "ZEN-23374: RHEL/CentOS 7 fails with > 1 zSshConcurrentSessions SSH Ti…"

---

Products/ZenRRD/runner.py
Products/ZenRRD/zencommand.py

Cherry-picked 367a3e2541574209a38911c783ffdf304dd5c76d
Cherry-picked 3dd14c413a67e33259010543db131502bd913c25

Please review branch feature/ZEN-24666

---

Products/DataCollector/SshClient.py

Cherry-picked efb4f959e4680d417082ac5dc0808af6768e3a3d

Please review branch feature/ZEN-24681

---

Products/ZenUtils/zenpack.py

ZEN-24274 Fix install of community/custom ZenPacks during upgrades

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceOverviewPanel.js

https://jira.zenoss.com/browse/ZEN-23951

require user interaction to load device links

---

Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

https://jira.zenoss.com/browse/ZEN-23953

dont try to save browser UI state unless state has actually changed

---

Products/ZenUtils/tests/testFindEggs.py
Products/ZenUtils/zenpack.py

cherry-pick pull-request #1874

Fixes ZEN-24274.1

---

Products/ZenCallHome/transport/methods/browserjs.py
Products/ZenCallHome/transport/methods/directpost.py
Products/ZenCallHome/transport/methods/versioncheck.py

cherry-pick pull-request #1807

Fixes ZEN-23688

---

Products/ZenEvents/SyslogProcessing.py
Products/ZenEvents/tests/testSyslogProcessing.py

cherry-pick pull-request #1876

Fixes ZEN-24722

---

Products/ZenUI3/browser/resources/js/zenoss/triggers.js
Products/Zuul/facades/triggersfacade.py

cherry-pick pull-request #1398
[Jira](https://jira.zenoss.com/browse/ZEN-19522)

Fixes ZEN-19522

---

Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/navigation.zcml

cherry-pick commit 84deed6
[Jira](https://jira.zenoss.com/browse/ZEN-24054)

Fixes ZEN-24054

---

Products/ZenModel/DeviceClass.py
Products/ZenModel/tests/testDeviceClass.py
Products/ZenUtils/tests/test_productionstate.py

Retain production state after moving devices

---

Products/ZenUI3/browser/resources/js/zenoss/devicemanagement/Administration.js

Cherry-picked daf5f23ef8ca88c916e0af47416aac76c8bd40dc

Please review branch feature/ZEN-25408

---

Products/Zuul/facades/triggersfacade.py

Additional fix for filtering triggers from the trigger list.
See [Jira](https://jira.zenoss.com/browse/ZEN-25459)

ZEN-25459 add checking permission to the trigger list

---

Products/Zuul/facades/triggersfacade.py

cherry-pick pull-request #1903
See [Jira](https://jira.zenoss.com/browse/ZEN-24054)

Fixes ZEN-24054-1

---

Products/ZenModel/actions.py

${evt/firstTime} and ${evt/lastTime} in notifications are sent in
UTC.
Take a timezone from user propery and convert time in notification
email to that timezone, and group target list of emails by timezones.
[Jira and demo](https://jira.zenoss.com/browse/ZEN-24535)

ZEN-24535: convert event time in email to timezone from user property

---

Products/ZenModel/actions.py

Reverts zenoss/zenoss-prodbin#1906
Will be done in newer release of 5.1.x

Revert "ZEN-24535: convert event time in email to timezone from user property"

---

Products/ZenModel/migrate/AddHMasterRegionServerGraphConfigs.py
Products/ZenModel/migrate/addHBaseMetricsConfig.py
Products/ZenModel/migrate/tests/test_AddHMasterRegionServerGraphConfigs.py
Products/ZenModel/migrate/tests/zenoss-resmgr-5.1.5-AddHMasterRegionServerGraphConfigs.json

This is migration script and tests for https://github.com/zenoss/zenoss-service/pull/327 and https://github.com/zenoss/zenoss-service/pull/281
[Jira](https://jira.zenoss.com/browse/ZEN-25579)

ZEN-25579: add migration for new HMaster and RegionServer graphs

---

Products/ZenRelations/ZenPropertyManager.py

This is port from : https://github.com/zenoss/4.2.5-RPS/pull/731
[Jira](https://jira.zenoss.com/browse/ZEN-21723)

ZEN-21723: Audit log lacking detail for changes to mapping

---

Products/ZenUtils/tests/testTime.py

Fix failing unit test for ZenUtils.

ZEN-25298: Fix time test

---

Products/ZenModel/migrate/moveProductionStateToBTree.py

ZEN-26008 migration moveProductionStateToBTree not scalable

---

Products/ZenWidgets/ZenTableState.py

Changed order of request parsing for running reports
Added check for adapt=false param given by the report runner

ZEN-25715 Full reports

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

Cherry-picked db21251e28b54afabb80beb659b2e500bdb963bf

Please review branch feature/ZEN-25970

---

Products/ZenWidgets/ZenTableState.py

Cherry-picked #1974
Fixes [ZEN-26149](https://jira.zenoss.com/browse/ZEN-26149)

Cherry picked PR #1974

---

Products/ZenUI3/browser/resources/js/zenoss/devdetail.js

Reverts zenoss/zenoss-prodbin#1964
Reapply after cutting 5.1.10

Revert "Please review branch feature/ZEN-25970"

---

Products/ZenUI3/browser/backcompat.zcml

check permission for users to see Advance things via URL
[Jira](https://jira.zenoss.com/browse/ZEN-22028)

ZEN-22028 Zenuser is able to see Advance things via URL

---

Products/ZenUI3/browser/resources/js/zenoss/manufacturers/ManufacturersPanels.js
Products/Zuul/facades/manufacturersfacade.py

Cherry-picked 1d381273f58db93f37aea59c63fd59b67862d095

Please review branch feature/ZEN-26317

---

Products/Zuul/catalog/global_catalog.py

[Jira](https://jira.zenoss.com/browse/ZEN-22878)
I had to reindex catalog to make it work.

ZEN-22878 Escape names in search results

---

Products/ZenModel/ZVersion.py

bump version to 5.1.4.1 for special support branch

Update Version Number

---

Products/ZenUI3/browser/resources/js/zenoss/BaseGrid.js

port from develop:
https://github.com/zenoss/zenoss-prodbin/pull/2008/files

ZEN-21950: Event View links with Timestamps, timestamps are not saved

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/editUserSettings.pt
Products/ZenUI3/browser/configure.zcml
Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/javascript.zcml

[Jira](https://jira.zenoss.com/browse/ZEN-26321), port of #1999

ZEN-26321 Add date format to user settings

---

Products/Zuul/catalog/global_catalog.py

[Jira](https://jira.zenoss.com/browse/ZEN-25995), port of #1958

ZEN-25995 Escape names in search results

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

[Jira](https://jira.zenoss.com/browse/ZEN-25279)

ZEN-25279:Event Details are Displayed Over Multiple Lines

---

Products/ZenUI3/browser/resources/css/xtheme-zenoss.css

cherry-pick commit 8db6fd9
[Jira](https://jira.zenoss.com/browse/ZEN-26439)

Fixes ZEN-26439

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

port from : https://github.com/zenoss/zenoss-prodbin/pull/2034
[JIRA](https://jira.zenoss.com/browse/ZEN-26459)

ZEN-26459: add listener for Enter Key

---

Products/ZenWidgets/skins/zenui/locationGeoMap.pt
Products/ZenWidgets/skins/zenui/simpleLocationGeoMap.pt

ZEN-26571 Google Map API warning msg

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

fixes ZEN-25282: Event Details Sections are Expanded by Default

---

Products/ZenModel/ManagedEntity.py

Dynamically generating a new wrapper type for every call to `ManagedEntity.__of__` is highly inefficient and unnecessary.  The C Acquisition implementation we use will only ever return an ImplicitAcquisitionWrapper for a ManagedEntity.  Thus, we can statically define our own sub-class of ImplicitAcquisitionWrapper to handle the special case for productionState.

Declare one static wrapper class

---

Products/ZenModel/ManagedEntity.py

ZEN-26621 ManagedEntity.__of__ does not scale

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/editUserSettings.pt
Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

ZEN-24798 Unable to change date format for First Seen/Last Seen columns in Event Console

ZEN-24798 Unable to change date format for First Seen/Last Seen columns in Event Console

---

Products/ZenModel/ManagedEntity.py

ZEN-26623 ManagedEntity.__of__ does not scale

---

Products/ZenModel/IpInterface.py

This is port from https://github.com/zenoss/zenoss-prodbin/pull/2041
[JIRA](https://jira.zenoss.com/browse/ZEN-26580)

ZEN-26580: add ipwrap for matching ip

---

Products/ZenModel/UserSettings.py
Products/ZenModel/skins/zenmodel/editUserSettings.pt

ZEN-26260 Unable to change date format for First Seen/Last Seen columns in Event Console
Port for:
ZEN-24798 Unable to change date format for First Seen/Last Seen columns in Event Console

ZEN-26260 Unable to change date format for First Seen/Last Seen columns in Event Console

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/Zuul/facades/devicefacade.py

Minification fails on ES6 keyword 'let' replace with ES5 keyword 'var'

ZEN-26498 component graph legend improvements

---

Products/ZenRelations/ImportRM.py

Reverts zenoss/zenoss-prodbin#2051

Revert "ZEN-17882: check for existing OIDs when installing zenpack"

---

Products/ZenUI3/browser/resources/js/zenoss/Renderers.js
Products/ZenUI3/browser/resources/js/zenoss/Types.js

This is port from https://github.com/zenoss/zenoss-prodbin/pull/2059

ZEN-26704: add hyperlink tag handling

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

this is port from https://github.com/zenoss/zenoss-prodbin/pull/2068
[JIRA](https://jira.zenoss.com/browse/ZEN-26770)

ZEN-26770: add autoScroll option to expandGraph window

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

this is from https://github.com/zenoss/zenoss-prodbin/pull/2067
[JIRA](https://jira.zenoss.com/browse/ZEN-26769)

ZEN-26769: set drange variable when graph is opened in the new tab

---

Products/ZenUI3/browser/resources/js/zenoss/eventDetail.js

port:
https://github.com/zenoss/zenoss-prodbin/pull/2038

ZEN-26631: auto cleared events have transient severity

---

Products/ZenUI3/browser/resources/js/zenoss/DeviceOverviewPanel.js

port from https://github.com/zenoss/zenoss-prodbin/pull/2042
[Jira](https://jira.zenoss.com/browse/ZEN-26629)

ZEN-26629 XSS on the device's details page

---

Products/ZenUtils/patches/pasmonkey.py

accidentally removed logs, in previous commit.

ZEN-22461.3 Improper Restriction of Excessive Authentication Attempts

---

Products/ZenUI3/browser/javascript.py
Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

ZEN-26260 Unable to change date format for First Seen/Last Seen columns in Event Console part2
This commit was partial by improper cherry picking. This part of code should be merged in order to finalize with fix for this issue.

ZEN-26260 Unable to change date format for First Seen/Last Seen columns in Event Console part2

---

Products/ZenCollector/scheduler.py
Products/ZenModel/migrate/addMissedRunsEventClass.py

https://jira.zenoss.com/secure/attachment/38941/events.png
https://jira.zenoss.com/secure/attachment/38940/cleared.png

ZEN-25764: Alert on missed collection runs

---

Products/ZenCollector/scheduler.py
Products/ZenModel/migrate/addMissedRunsEventClass.py

port:
https://github.com/zenoss/zenoss-prodbin/pull/2066

ZEN-26756: Alert on missed collection runs

---

makefile

(cherry picked from commit b8d94d1ab5b63d41005a4306bb7748625c63d698)

Use tag, instead of branch name, in artifact name

---

Products/ZenUI3/browser/resources/js/zenoss/BackCompatPanel.js
Products/ZenUI3/browser/resources/js/zenoss/Reports.js

port:
https://github.com/zenoss/zenoss-prodbin/pull/2091

ZEN-26830: A single user can crash the UI running reports

---

Products/ZenModel/zenmib.py

This is port from https://github.com/zenoss/zenoss-prodbin/pull/2097
[JIRA](https://jira.zenoss.com/browse/ZEN-26581)

ZEN-26581: update MIB module instead of remove.

---

Products/ZenUtils/AccountLocker/AccountLocker.py

add checker to verify if plugin is already installed.

ZEN-22461 Improper Restriction of Excessive Authentication Attempts

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

ZEN-26818 Use user defined time zone on graphs

---

Products/Zuul/facades/devicefacade.py

Get legends in all-on-same-graph graph to match their respective individual component graph legends.

ZEN-26741 Ledgends in All On Same Component Graph

---

Products/Zuul/facades/devicefacade.py

Reverts zenoss/zenoss-prodbin#2114

Revert "ZEN-26741 Ledgends in All On Same Component Graph"

---

Products/ZenEvents/EventClassInst.py
Products/ZenEvents/events2/processing.py
Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml
Products/ZenModel/migrate/addZEventMaxTransformFailsProperty.py
Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js
Products/Zuul/facades/eventclassesfacade.py
Products/Zuul/interfaces/eventclasses.py
Products/Zuul/routers/eventclasses.py

https://jira.zenoss.com/browse/ZEN-26607

ZEN-26607 Bad Transform Events Can Cause Event Loop

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

added conditional for graph refresh to ensure that the panel is visible before attempting a refresh

ZEN-26884 Graph refreshing even when not visible

---

Products/ZenUI3/browser/resources/css/zenoss.css
Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

backporting the changes for the graph refresh work to 5.2.x

ZEN-26883 5.2.x backport

---

Products/Zuul/infos/template.py

Demo at:
https://jira.zenoss.com/browse/ZEN-26529?focusedCommentId=103363&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-103363

ZEN-26529 DERIVE Data Points Exhibiting COUNTER Behavior in Graphs

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

backporting the graph improvement work for cdk

ZEN-26884 5.2.x backport

---

Products/Zuul/infos/template.py

Port of https://jira.zenoss.com/browse/ZEN-26529
Demo is: https://jira.zenoss.com/browse/ZEN-26529?focusedCommentId=103363&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-103363

ZEN-26449 DERIVE Data Points Exhibiting COUNTER Behavior in Graphs

---

Products/ZenModel/MinMaxThreshold.py

(cherry picked from commit 12f25b46c8750d2defa9acba9ffe9b0bb1db4a97)

Add dev and comp ids in log msg when data source expression is invalid

---

Products/ZenRRD/zencommand.py

fix ZEN-19198

---

Products/ZenHub/services/CommandPerformanceConfig.py
Products/ZenModel/MetricMixin.py
Products/ZenModel/RRDDataSource.py

(cherry picked from commit ec1b3a1fae148696b4c89b1e43ca1a243cc34c27)

ZEN-26936: do not call device() on components more than needed

---

Products/ZenModel/FileSystem.py
Products/ZenReports/tests/testFilesystemsPlugin.py

ZEN-26739 Unable to selectively adjust zFileSystemSizeOffset based on FS type

---

Products/ZenModel/GraphReport.py

port from https://github.com/zenoss/4.2.5-RPS/pull/735

ZEN-26994: Can't add graphs to graph reports

---

Products/ZenEvents/EventClassInst.py
Products/ZenEvents/events2/processing.py
Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml
Products/ZenModel/migrate/addZEventMaxTransformFailsProperty.py
Products/ZenUI3/browser/resources/js/zenoss/eventclasses/ClassPanels.js
Products/Zuul/facades/eventclassesfacade.py
Products/Zuul/interfaces/eventclasses.py
Products/Zuul/routers/eventclasses.py

port of https://github.com/zenoss/zenoss-prodbin/pull/2058
https://jira.zenoss.com/browse/ZEN-26821

ZEN-26821 Bad Transform Events Can Cause Event Loop

---

Products/Zuul/catalog/global_catalog.py

[Jira](https://jira.zenoss.com/browse/ZPS-998)

ZPS-998 Handle escaping 'None'

---

Products/ZenCollector/scheduler.py
Products/ZenStatus/nmap/NmapPingTask.py
Products/ZenStatus/zenping.py

Added a method that automatically runs after the configs are updated which clears out the current ping "Missed Runs" count

ZEN-26850 Missed Pings count fix

---

Products/ZenModel/actions.py

https://jira.zenoss.com/browse/ZEN-27031

ZEN-27031: Don't mess with user provided HTML

---

Products/ZenModel/BatchDeviceLoader.py

Fixes ZEN-26882 "zenbatchload --nocommit still commits changes."

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Additional legend improvements remove redundancy and truncate UUIDs.

ZEN-26741 Legend improvements

---

Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js

Reverts zenoss/zenoss-prodbin#2173

Revert "ZEN-26938: Disallow special characters in data source names."

---

Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/datasource.js

Reverts zenoss/zenoss-prodbin#2174

Revert "ZEN-27042: Disallow special characters in data source names."

---

Products/ZenModel/BatchDeviceLoader.py

fixes ZEN-27056

---

Products/Zuul/infos/metricserver.py

port from https://github.com/zenoss/zenoss-prodbin/pull/2163
[Jira](https://jira.zenoss.com/browse/ZEN-23497)

ZEN-23497 Graph Title Breadcrumb

---

Products/Zuul/facades/templatefacade.py

https://jira.zenoss.com/browse/ZEN-26938

ZEN-26938: Disallow special characters in data source names.

---

Products/Zuul/facades/templatefacade.py

port: https://github.com/zenoss/zenoss-prodbin/pull/2184
jira: https://jira.zenoss.com/browse/ZEN-27042

ZEN-27042: Disallow special characters in data source names.

---

Products/ZenModel/Device.py

Port of #2192 to support/5.2.x

ZEN-26530 Event generation ignoring production state changes

---

Products/ZenModel/skins/zenmodel/editCollection.pt
Products/ZenModel/skins/zenmodel/editMultiGraphReport.pt
Products/ZenWidgets/ZenTableState.py
Products/ZenWidgets/skins/zentablemanager/zenTableNavigation.pt

https://jira.zenoss.com/browse/ZEN-6972
ref to https://github.com/zenoss/zenoss-prodbin/pull/2178

ZEN-6972  Edit page for multi-graph reports doesn't show more than 39 items.

---

Products/ZenUtils/PortScan.py

Fixes unhandled errors in PortScan when destination host is unreachable.

---

Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js
Products/Zuul/routers/template.py

Allow user-defined fractional (non-integer) values for Y axis values.  Allows up to 3 decimal places in axis values.

ZEN-26925 Allow non-integer axis values

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

[Jira](https://jira.zenoss.com/browse/ZEN-27111)

ZEN-27111 Graph range for 'Yesterday' is actually the last 24 hours

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/Zuul/facades/devicefacade.py
Products/Zuul/infos/metricserver.py

Backport fix with alternate legend fix.

ZEN-26498 Component Graph Legends

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js
Products/Zuul/facades/devicefacade.py
Products/Zuul/infos/metricserver.py

Fix problem with flares on component graphs.

ZEN-27126 Flares on component graphs

---

Products/ZenModel/zenmib.py

Here is where this is ported from: https://github.com/zenoss/pm-resmgr-4.2.4/pull/894

ported smidump fixes from 4x to develop

---

Products/DataCollector/SnmpClient.py

When an exception is caught during collection, re-raise the exception so that it is handled properly in an errback.

Create an event when snmp collection fails

---

Products/ZenUI3/browser/resources/js/zenoss/form/graphPanel.js

Cherry-picked https://github.com/zenoss/zenoss-prodbin/pull/2226
[Jira](https://jira.zenoss.com/browse/ZEN-26998)

ZEN-26998 Graph range for 'Yesterday' is actually the last 24 hours

---

Products/ZenModel/Device.py

[JIRA](https://jira.zenoss.com/browse/ZEN-27094)
this is cherry-pick from https://github.com/zenoss/zenoss-prodbin/pull/2201

ZEN-27094: check if device with the same ip exist

---

Products/ZenReports/reports/Device_Reports/Device_Changes.rpt
Products/ZenReports/reports/Device_Reports/Model_Collection_Age.rpt
Products/ZenReports/reports/Device_Reports/New_Devices.rpt

[JIRA](https://jira.zenoss.com/browse/ZEN-27184)
this is cherry-pick from https://github.com/zenoss/zenoss-prodbin/pull/2237

ZEN-27184: set Not Modeled when we get 0 from getSnmpLastCollection

---

Products/ZenRRD/zenprocess.py

https://jira.zenoss.com/browse/ZEN-27276
port of https://github.com/zenoss/zenoss-prodbin/pull/2251

ZEN-27276: OS Process Monitoring (SNMP) Can Send Duplicate Events

---

Products/Zuul/routers/zep.py

port from https://github.com/zenoss/zenoss-prodbin/pull/2243
jira https://jira.zenoss.com/browse/ZEN-27221

ZEN-27221 adding back-end support for the Infrastructure->Details->Events console/grid

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

[Jira & demo](https://jira.zenoss.com/browse/ZEN-27367)

ZEN-27367 Device tree auto refresh is slow and distracting

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

port from https://github.com/zenoss/zenoss-prodbin/pull/2276
[Jira](https://jira.zenoss.com/browse/ZEN-26930)

ZEN-26930 Device tree auto refresh is slow and distracting

---

Products/ZenModel/migrate/addAuditLogFlag.py

Change audit flag migration version to 112.

Bump migration version

---

Products/ZenModel/migrate/addReportingZopesSvcDef.py

- tweak regex that works with unit test and actually finds and inserts zopereports-upstreams declaration
- change user-agent to match  zenreports service per zenoss-service-PR383

ZEN-27191: nginx insertion point regex tweak; update answering HC UA

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml

[JIRA](https://jira.zenoss.com/browse/ZEN-26955)
This is related to other PR https://github.com/zenoss/zenoss-prodbin/pull/2237

ZEN-26955: Update SQL dump according to changes in default Reports

---

Products/ZenModel/data/devices.xml
Products/ZenModel/data/events.xml
Products/ZenModel/data/manufacturers.xml
Products/ZenModel/data/monitorTemplate.xml
Products/ZenModel/data/osprocesses.xml
Products/ZenModel/data/services.xml
Products/ZenModel/migrate/tests/zenoss-resmgr-5.0.6_1-zminionViaSupervisord.json

[JIRA](https://jira.zenoss.com/browse/ZEN-27184)
this additional changes to https://github.com/zenoss/zenoss-prodbin/pull/2268

ZEN-27184: Update SQL dump according to changes in default Reports

---

Products/ZenUtils/ZenPackCmd.py

[Jira](https://jira.zenoss.com/browse/ZEN-27407)
The issue  took place because during the zenpacks installation `pkg_resources` module shows the old version of required zenpack while dmd shows the proper version.
To fix this I replace  `packEntry.load()` instead of `packEntry.resolve()`
From the docs:
`resolve()
Resolve the entry point from its module and attrs, returning the advertised Python object. Raises ImportError if it cannot be obtained.`
http://setuptools.readthedocs.io/en/latest/pkg_resources.html#entrypoint-objects

ZEN-27407 ZenPack dependencies not always installed in correct order

---

Products/ZenModel/skins/zenmodel/editSettings.pt

[Jira](https://jira.zenoss.com/browse/ZEN-27488)

ZEN-27488 'Zenoss Hostname' should be changed in settings

---

Products/ZenModel/skins/zenmodel/editSettings.pt

port from https://github.com/zenoss/zenoss-prodbin/pull/2277
[Jira](https://jira.zenoss.com/browse/ZEN-23197)

ZEN-23197 'Zenoss Hostname' should be changed in settings

---

Products/ZenUI3/browser/resources/js/zenoss/HierarchyTreePanel.js

port from https://github.com/zenoss/zenoss-prodbin/pull/2312
[Jira](https://jira.zenoss.com/browse/ZEN-27394)

ZEN-27394 Tree nodes need a manual refresh to be visible after creation

---

Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

Demo on [Jira](https://jira.zenoss.com/browse/ZEN-24031)
Supplement to #2102

ZEN-24031 Timezone in event details

---

Products/ZenUI3/browser/resources/js/zenoss/zenoss.js

ZEN-26818 Timezone in event details

---

Products/ZenWidgets/browser/quickstart/templates/quickstart_macros.pt

Update copyright year.

---

Products/ZenModel/DeviceOrganizer.py
Products/Zuul/catalog/indexable.py

Added some indexed fields to DeviceOrganizer that were accidentally omitted
Update IP text fields to use the new IP Address field type in modelindex

Changes for AdvancedSearch

---

Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/graph.js
Products/ZenUI3/browser/resources/js/zenoss/monitoringTemplates/threshold.js

ZEN-27322 Flare message when add custom graph to nexus 5k chassis cherry-pick from https://github.com/zenoss/zenoss-prodbin/pull/2300

ZEN-27446 Flare message when add custom graph to nexus 5k chassis

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js
Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js
Products/Zuul/facades/__init__.py

[Jira](https://jira.zenoss.com/browse/ZEN-27630), backport of #2341

ZEN-27630 Filter Device Status column

---

Products/ZenUI3/browser/resources/js/zenoss/DevicePanels.js
Products/ZenUI3/browser/resources/js/zenoss/form/DeviceFields.js
Products/Zuul/facades/__init__.py

[Jira](https://jira.zenoss.com/browse/ZEN-27602)

ZEN-27602 Filter Device Status column

---

Products/ZenEvents/zentrap.py

https://jira.zenoss.com/browse/ZEN-27677

ZEN-27677 Split ifDescr and ifIndex fields in event details of trap

---

Products/ZenEvents/zentrap.py

https://jira.zenoss.com/browse/ZEN-27555
port for https://github.com/zenoss/zenoss-prodbin/pull/2362

ZEN-27555 Split ifDescr and ifIndex fields in event details of trap

---

Products/ZenModel/actions.py

keep emails that don't belong to users in the system

---

Products/Zuul/routers/device.py

[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-26891)

ZEN-26891: remove asterisk characters

---

Products/Zuul/routers/device.py

Reverts zenoss/zenoss-prodbin#2379
Reverting this fix due some unexpected traceback.

Revert "ZEN-26891: remove asterisk characters"

---

Products/ZenModel/IpNetwork.py

When searching the cache for a network, we check to make sure it has the correct basenet.  This will always be true if MultiRealmIP is not installed, but if it is the base network will be the realm.

Make network cache work with MultiRealmIP zenpack
